#!/usr/bin/env node
// Generate TypeScript definitions for the Affinity's scripting SDK.

import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  existsSync,
  readdirSync,
  statSync,
} from "node:fs";
import { dirname, join, resolve, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";

const HERE = dirname(fileURLToPath(import.meta.url));
const DEFAULT_JSLIB = "/Applications/Affinity.app/Contents/Resources/JSLib";

const NATIVE_MODULES = [
  "affinity:application",
  "affinity:brushes",
  "affinity:buffer",
  "affinity:colours",
  "affinity:commands",
  "affinity:common",
  "affinity:dom",
  "affinity:fills",
  "affinity:fonts",
  "affinity:fs",
  "affinity:geometry",
  "affinity:hatches",
  "affinity:layereffects",
  "affinity:linestyles",
  "affinity:network",
  "affinity:raster",
  "affinity:story",
  "affinity:timers",
  "affinity:ui",
];

const COLLECTION_ELEMENT_TYPES = {
  DialogGroupControls: "DialogControl",
  DialogColumnGroups: "DialogGroup",
  DialogColumns: "DialogColumn",
  DialogColumnStackColumns: "DialogColumn",
  Layers: "Node",
  NodeChildrenOnly: "Node",
  NodeChildren: "Node",
  NodeDescendents: "Node",
  DirectoryEntries: "DirectoryEntry",
  RecursiveDirectoryEntries: "DirectoryEntry",
  SpanCollection: "any",
  RangeCollection: "number",
};

const FACTORY_FUNCTIONS = {
  createTypedDialogControl: "DialogControl",
  createTypedNode: "Node",
  createTypedShape: "Shape",
  createTypedFill: "Fill",
  createTypedLayerEffect: "LayerEffect",
  createTypedSubSelection: "SubSelection",
  createTypedGlyph: "Glyph",
  createTypedRasterObject: "RasterObject",
  createTypedQRPayload: "QRPayload",
};

const HEADER = "// Auto-generated by tools/generate_types.py. Do not edit.\n";

// --------------------------------------------------------------------------- //
// Token helpers
// --------------------------------------------------------------------------- //

const isKind = (t, k) => !!t && t[0] === k;
const isPunct = (t, v) => !!t && t[0] === "punct" && t[1] === v;
const isIdent = (t, v) =>
  !!t && t[0] === "ident" && (v === undefined || t[1] === v);

// --------------------------------------------------------------------------- //
// Lexer
// --------------------------------------------------------------------------- //

function skipString(src, i) {
  const q = src[i];
  i += 1;
  while (i < src.length) {
    if (src[i] === "\\") {
      i += 2;
      continue;
    }
    if (src[i] === q) return i + 1;
    i += 1;
  }
  return i;
}

function skipTemplate(src, i) {
  i += 1;
  while (i < src.length) {
    const c = src[i];
    if (c === "\\") {
      i += 2;
      continue;
    }
    if (c === "`") return i + 1;
    if (c === "$" && src[i + 1] === "{") {
      i = skipInterp(src, i + 2);
      continue;
    }
    i += 1;
  }
  return i;
}

function skipInterp(src, i) {
  let depth = 1;
  while (i < src.length && depth > 0) {
    const c = src[i];
    if (c === "{") depth += 1;
    else if (c === "}") depth -= 1;
    else if (c === '"' || c === "'") {
      i = skipString(src, i);
      continue;
    } else if (c === "`") {
      i = skipTemplate(src, i);
      continue;
    } else if (c === "/" && src[i + 1] === "/") {
      const j = src.indexOf("\n", i);
      i = j === -1 ? src.length : j + 1;
      continue;
    } else if (c === "/" && src[i + 1] === "*") {
      const j = src.indexOf("*/", i + 2);
      i = j === -1 ? src.length : j + 2;
      continue;
    }
    i += 1;
  }
  return i;
}

function lex(src) {
  const tokens = [];
  let i = 0;
  const n = src.length;
  while (i < n) {
    const c = src[i];
    if (/\s/.test(c)) {
      i += 1;
      continue;
    }
    if (c === "/" && src[i + 1] === "/") {
      const j = src.indexOf("\n", i);
      i = j === -1 ? n : j + 1;
      continue;
    }
    if (c === "/" && src[i + 1] === "*") {
      const j = src.indexOf("*/", i + 2);
      i = j === -1 ? n : j + 2;
      continue;
    }
    if (c === '"' || c === "'") {
      const j = skipString(src, i);
      tokens.push(["string", src.slice(i, j)]);
      i = j;
      continue;
    }
    if (c === "`") {
      const j = skipTemplate(src, i);
      tokens.push(["template", src.slice(i, j)]);
      i = j;
      continue;
    }
    if (/[0-9]/.test(c)) {
      let j = i;
      while (j < n && /[0-9a-zA-Z._]/.test(src[j])) j += 1;
      tokens.push(["number", src.slice(i, j)]);
      i = j;
      continue;
    }
    if (/[a-zA-Z_#$]/.test(c)) {
      let j = i;
      while (j < n && /[0-9a-zA-Z_#$]/.test(src[j])) j += 1;
      tokens.push(["ident", src.slice(i, j)]);
      i = j;
      continue;
    }
    if (src.startsWith("...", i)) {
      tokens.push(["punct", "..."]);
      i += 3;
      continue;
    }
    tokens.push(["punct", c]);
    i += 1;
  }
  tokens.push(["eof", ""]);
  return tokens;
}

// --------------------------------------------------------------------------- //
// Token helpers
// --------------------------------------------------------------------------- //

function skipGroup(toks, i, open, close) {
  let depth = 0;
  while (i < toks.length) {
    if (isPunct(toks[i], open)) depth += 1;
    else if (isPunct(toks[i], close)) {
      depth -= 1;
      if (depth === 0) return i + 1;
    }
    i += 1;
  }
  return i;
}

function skipToSemicolon(toks, i) {
  let depth = 0;
  while (i < toks.length) {
    const t = toks[i];
    if (isKind(t, "string") || isKind(t, "template")) {
      i += 1;
      continue;
    }
    const v = t[1];
    if ("([{".includes(v)) depth += 1;
    else if (")]}".includes(v)) {
      if (depth === 0) return i;
      depth -= 1;
    } else if (v === ";" && depth === 0) return i + 1;
    i += 1;
  }
  return i;
}

function splitParams(raw) {
  const groups = [[]];
  let depth = 0;
  for (const t of raw) {
    const v = t[1];
    if ("([{".includes(v)) depth += 1;
    else if (")]}".includes(v)) depth -= 1;
    if (isPunct(t, ",") && depth === 0) groups.push([]);
    else groups[groups.length - 1].push(t);
  }
  const params = [];
  for (const g of groups) {
    if (g.length === 0) continue;
    params.push(parseParam(g));
  }
  return params;
}

function parseParam(g) {
  let isRest = false;
  if (isPunct(g[0], "...") && g.length > 1 && isKind(g[1], "ident")) {
    isRest = true;
  }
  const lhs = [];
  let depth = 0;
  let eqIdx = -1;
  for (let i = 0; i < g.length; i += 1) {
    const t = g[i];
    const v = t[1];
    if ("([{".includes(v)) depth += 1;
    else if (")]}".includes(v)) depth -= 1;
    if (isPunct(t, "=") && depth === 0) {
      eqIdx = i;
      break;
    }
    lhs.push(t);
  }
  let name = "arg";
  if (isRest && lhs.length > 1 && isKind(lhs[1], "ident")) name = lhs[1][1];
  else if (lhs.length > 0 && isKind(lhs[0], "ident")) name = lhs[0][1];

  let type = null;
  let optional = true;
  if (eqIdx !== -1 && eqIdx + 1 < g.length) {
    const val = g[eqIdx + 1];
    if (val[1] === "true" || val[1] === "false") type = "boolean";
    else if (val[0] === "number") type = "number";
    else if (val[0] === "string" || val[0] === "template") type = "string";
    else if (val[1] === "null") type = "any";
    else if (val[0] === "ident") {
      // Check if it's Mod.Enum.Val or Enum.Val
      const restOfExpr = g.slice(eqIdx + 1).map((t) => t[1]);
      if (restOfExpr.length >= 3 && restOfExpr[1] === ".") {
        let candidate = null;
        if (restOfExpr.length >= 5 && restOfExpr[3] === ".") {
          candidate = restOfExpr[2]; // e.g. Mod.Enum.Val -> Enum
        } else {
          candidate = restOfExpr[0]; // e.g. Enum.Val -> Enum
        }
        if (candidate && /^[A-Z]/.test(candidate)) {
          type = candidate;
        } else {
          type = null;
        }
      } else {
        type = null;
      }
    }
  } else {
    if (name === "callback") type = "(...args: any[]) => any";
    else if (/^(?:is|has|should)[A-Z]/.test(name)) type = "boolean";
    else if (/(?:Count|Index|Length|Dpi|Width|Height)$/.test(name)) type = "number";
    else if (name === "text" || name === "name" || name === "path" || name === "url" || name === "desc") type = "string";
  }
  return { name, type, optional, isRest };
}

function union(types) {
  const concrete = [...types].filter((t) => t !== null).sort();
  const hasNull = types.has(null);
  if (concrete.length === 1) return concrete[0] + (hasNull ? " | null" : "");
  if (concrete.length > 1) return concrete.join(" | ") + (hasNull ? " | null" : "");
  return null;
}

function inferReturn(body, memberName = "", clsName = "", registry = null, enumsCatalog = null) {
  const assigned = new Map();
  const rets = [];
  const n = body.length;
  let hasReturn = false;

  // Special: .map(..).flat() chaining in Dialog/DialogColumn/DialogColumnStack
  const rawStr = body.map((t) => t[1]).join("");
  if (rawStr.includes(".map(") && rawStr.includes(".flat()")) {
    if (rawStr.includes("group.controls") || rawStr.includes(".controls.toArray()")) {
      return "DialogControl[]";
    }
    if (rawStr.includes("column.groups") || rawStr.includes(".groups.toArray()")) {
      return "DialogGroup[]";
    }
  }
  for (let i = 0; i < n; i += 1) {
    const t = body[i];
    if (isIdent(t, "return") && i + 1 < n) {
      hasReturn = true;
      const nxt = body[i + 1];
      // return new Mod.Class(...) or return new Class(...)
      if (isIdent(nxt, "new") && i + 2 < n && isKind(body[i + 2], "ident")) {
        if (i + 4 < n && isPunct(body[i + 3], ".") && isKind(body[i + 4], "ident")) {
          rets.push(["new", body[i + 4][1]]);
        } else {
          rets.push(["new", body[i + 2][1]]);
        }
      } else if (isIdent(nxt, "this")) {
        const nxt2 = i + 2 < n ? body[i + 2] : null;
        const nxt3 = i + 3 < n ? body[i + 3] : null;
        if (isPunct(nxt2, ".") && isKind(nxt3, "ident")) {
          rets.push(["this_prop", nxt3[1]]);
        } else if (!isPunct(nxt2, ".") && !isPunct(nxt2, "[")) {
          rets.push(["this"]);
        }
      } else if (isKind(nxt, "ident") && FACTORY_FUNCTIONS[nxt[1]]) {
        rets.push(["type", FACTORY_FUNCTIONS[nxt[1]]]);
      } else if (isKind(nxt, "ident") && nxt[1].endsWith("Api") && i + 3 < n && isPunct(body[i + 2], ".") && isKind(body[i + 3], "ident")) {
        rets.push(["api", nxt[1], body[i + 3][1]]);
      } else if (isIdent(nxt, "true") || isIdent(nxt, "false")) {
        rets.push(["type", "boolean"]);
      } else if (isPunct(nxt, "!")) {
        rets.push(["type", "boolean"]);
      } else if (nxt[0] === "number") {
        rets.push(["type", "number"]);
      } else if (nxt[0] === "string" || nxt[0] === "template") {
        rets.push(["type", "string"]);
      } else if (isKind(nxt, "ident")) {
        rets.push(["var", nxt[1]]);
      }
    } else if (isIdent(t, "this") && i + 3 < n && isPunct(body[i + 1], ".") && isKind(body[i + 2], "ident") && isPunct(body[i + 3], "=")) {
      const prop = body[i + 2][1];
      const j = i + 4;
      if (j + 1 < n && isIdent(body[j], "new") && isKind(body[j + 1], "ident")) {
        if (!assigned.has(prop)) assigned.set(prop, new Set());
        if (j + 3 < n && isPunct(body[j + 2], ".") && isKind(body[j + 3], "ident")) {
          assigned.get(prop).add(body[j + 3][1]);
        } else {
          assigned.get(prop).add(body[j + 1][1]);
        }
      }
    } else if (isKind(t, "ident") && i + 1 < n && isPunct(body[i + 1], "=")) {
      const j = i + 2;
      if (j + 1 < n && isIdent(body[j], "new") && isKind(body[j + 1], "ident")) {
        if (!assigned.has(t[1])) assigned.set(t[1], new Set());
        if (j + 3 < n && isPunct(body[j + 2], ".") && isKind(body[j + 3], "ident")) {
          assigned.get(t[1]).add(body[j + 3][1]);
        } else {
          assigned.get(t[1]).add(body[j + 1][1]);
        }
      } else if (j + 1 < n && isKind(body[j], "ident") && FACTORY_FUNCTIONS[body[j][1]]) {
        if (!assigned.has(t[1])) assigned.set(t[1], new Set());
        assigned.get(t[1]).add(FACTORY_FUNCTIONS[body[j][1]]);
      } else if (j < n && isIdent(body[j], "null")) {
        if (!assigned.has(t[1])) assigned.set(t[1], new Set());
        assigned.get(t[1]).add(null);
      }
    }
  }

  for (const r of rets) {
    if (r[0] === "new") return r[1];
    if (r[0] === "type") return r[1];
    if (r[0] === "this") return "this";
    if (r[0] === "this_prop") {
      const u = union(assigned.get(r[1]) || new Set());
      if (u) return u;
    }
    if (r[0] === "var") {
      const u = union(assigned.get(r[1]) || new Set());
      if (u) return u;
    }
    if (r[0] === "api") {
      const [, apiName, methodName] = r;
      const inferred = inferFromApiOrMember(methodName, apiName, clsName, enumsCatalog);
      if (inferred) return inferred;
    }
  }

  // If method has no returns, or if memberName suggests a type
  if (!hasReturn && memberName.startsWith("set")) return "this";
  if (memberName) {
    const inferred = inferFromApiOrMember(memberName, "", clsName, enumsCatalog);
    if (inferred) return inferred;
  }
  return null;
}

function inferFromApiOrMember(name, apiName = "", clsName = "", enumsCatalog = null) {
  // Booleans
  if (/^(?:is|has|should|can)[A-Z]/.test(name) || /^(?:getIs|getHas|getShould|getCan)/.test(name) || name === "isRetina" || name === "isPortrait" || name === "isTransparent" || name === "isFacingPages" || name === "saveHistory" || name === "linkTextFiles" || name === "preserveTextStyles") {
    return "boolean";
  }
  // Numbers
  if (/(?:Count|Index|Length|Dpi|Width|Height|Proportion|Factor|Precision|ID|Id)$/.test(name) || /^(?:getCount|getIndex|getLength|getDpi|getWidth|getHeight|getDrawingScale|getPageWidth|getPageHeight|getInitialWidth|getPrecision|getPaddingFactor|getWidthProportion|getItemID)/.test(name) || name === "dpi" || name === "viewDpi" || name === "drawingScale" || name === "pageWidth" || name === "pageHeight" || name === "initialWidth" || name === "precision" || name === "paddingFactor" || name === "widthProportion" || name === "itemID" || name === "controlID") {
    return "number";
  }
  // Strings
  if (/(?:Name|Title|Description|Path|Version|Uuid)$/.test(name) || /^(?:getName|getTitle|getDescription|getPath|getVersion)/.test(name) || name === "label" || name === "text" || name === "title" || name === "description") {
    return "string";
  }
  // Void methods
  if (name === "show" && clsName === "Dialog") {
    return "void";
  }
  if (name === "runModal" && clsName === "Dialog") {
    return "DialogResult";
  }
  // Enums from catalog
  if (enumsCatalog) {
    const matchedEnum = matchEnumFromCatalog(name, clsName, enumsCatalog);
    if (matchedEnum) return matchedEnum;
  }
  return null;
}

function matchEnumFromCatalog(name, clsName, enumsCatalog) {
  const clean = name.replace(/^get/, "");
  const p = clean.toLowerCase();
  for (const [mod, modEnums] of Object.entries(enumsCatalog)) {
    for (const enumName of Object.keys(modEnums)) {
      const en = enumName.toLowerCase();
      if (p === en || p + "type" === en) return enumName;
      if (p.endsWith("s") && p.slice(0, -1) + "type" === en) return enumName;
      if (clsName) {
        const clsPrefix = clsName.replace(/(?:Item|Control|Node|Command)$/, "").toLowerCase();
        if (clsPrefix + p === en || clsPrefix + p + "type" === en) return enumName;
      }
    }
  }
  return null;
}

function skipBody(toks, i, memberName = "", clsName = "", registry = null, enumsCatalog = null) {
  const end = skipGroup(toks, i, "{", "}");
  return [inferReturn(toks.slice(i + 1, end - 1), memberName, clsName, registry, enumsCatalog), end];
}

// --------------------------------------------------------------------------- //
// Parsing
// --------------------------------------------------------------------------- //

function parseMembers(toks, clsName = "", registry = null, enumsCatalog = null) {
  const members = [];
  let i = 0;
  const n = toks.length;
  while (i < n) {
    let t = toks[i];
    if (isPunct(t, ";")) {
      i += 1;
      continue;
    }
    let isStatic = false;
    if (isIdent(t, "static")) {
      isStatic = true;
      i += 1;
      if (i >= n) break;
      t = toks[i];
    }
    if (isIdent(t, "async")) {
      i += 1;
      if (i >= n) break;
      t = toks[i];
    }
    if (isIdent(t, "get") || isIdent(t, "set")) {
      const kind = t[1];
      const nxt = i + 1 < n ? toks[i + 1] : null;
      if (nxt && isKind(nxt, "ident")) {
        const mem = {
          name: nxt[1],
          kind,
          static: isStatic,
          params: [],
          returns: null,
        };
        members.push(mem);
        i += 2;
        if (i < n && isPunct(toks[i], "(")) i = skipGroup(toks, i, "(", ")");
        if (i < n && isPunct(toks[i], "{")) {
          const [ret, j] = skipBody(toks, i, mem.name, clsName, registry, enumsCatalog);
          i = j;
          if (kind === "get") mem.returns = ret;
        }
        continue;
      }
      if (isPunct(nxt, "[")) {
        i = skipGroup(toks, i + 1, "[", "]");
        if (i < n && isPunct(toks[i], "(")) i = skipGroup(toks, i, "(", ")");
        if (i < n && isPunct(toks[i], "{")) i = skipGroup(toks, i, "{", "}");
        continue;
      }
    }
    if (isIdent(t, "constructor")) {
      i += 1;
      let params = [];
      if (i < n && isPunct(toks[i], "(")) {
        const end = skipGroup(toks, i, "(", ")");
        params = splitParams(toks.slice(i + 1, end - 1));
        i = end;
      }
      if (i < n && isPunct(toks[i], "{")) i = skipGroup(toks, i, "{", "}");
      members.push({
        name: "constructor",
        kind: "method",
        static: false,
        params,
        returns: null,
      });
      continue;
    }
    if (isKind(t, "ident") && t[1].startsWith("#")) {
      i += 1;
      if (i < n && isPunct(toks[i], "(")) {
        i = skipGroup(toks, i, "(", ")");
        if (i < n && isPunct(toks[i], "{")) i = skipGroup(toks, i, "{", "}");
      } else if (i < n && isPunct(toks[i], "=")) {
        i = skipToSemicolon(toks, i + 1);
      }
      continue;
    }
    if (isPunct(t, "[")) {
      i = skipGroup(toks, i, "[", "]");
      if (i < n && isPunct(toks[i], "(")) {
        i = skipGroup(toks, i, "(", ")");
        if (i < n && isPunct(toks[i], "{")) i = skipGroup(toks, i, "{", "}");
      } else if (i < n && isPunct(toks[i], "=")) i = skipToSemicolon(toks, i);
      continue;
    }
    if (isPunct(t, "*")) {
      i += 1;
      if (i < n && isKind(toks[i], "ident")) {
        const name = toks[i][1];
        i += 1;
        if (i < n && isPunct(toks[i], "(")) {
          const end = skipGroup(toks, i, "(", ")");
          members.push({
            name,
            kind: "method",
            static: isStatic,
            params: splitParams(toks.slice(i + 1, end - 1)),
            returns: null,
          });
          i = end;
        }
        if (i < n && isPunct(toks[i], "{")) i = skipGroup(toks, i, "{", "}");
      }
      continue;
    }
    if (isKind(t, "ident")) {
      const name = t[1];
      i += 1;
      if (i < n && isPunct(toks[i], "(")) {
        const end = skipGroup(toks, i, "(", ")");
        const mem = {
          name,
          kind: "method",
          static: isStatic,
          params: splitParams(toks.slice(i + 1, end - 1)),
          returns: null,
        };
        members.push(mem);
        i = end;
        if (i < n && isPunct(toks[i], "{")) {
          const [ret, j] = skipBody(toks, i, mem.name, clsName, registry, enumsCatalog);
          i = j;
          mem.returns = ret;
        }
        continue;
      }
      i = skipToSemicolon(toks, i);
      members.push({
        name,
        kind: "field",
        static: isStatic,
        params: [],
        returns: null,
      });
      continue;
    }
    i += 1;
  }
  return members;
}

function parseClass(toks, i, registry = null, enumsCatalog = null) {
  const name = toks[i + 1][1];
  let j = i + 2;
  let parent = null;
  if (isIdent(toks[j], "extends")) {
    parent = toks[j + 1][1];
    j += 2;
  }
  if (!isPunct(toks[j], "{")) return [{ name, parent, members: [] }, j];
  const end = skipGroup(toks, j, "{", "}");
  const members = parseMembers(toks.slice(j + 1, end - 1), name, registry, enumsCatalog);
  return [{ name, parent, members }, end];
}

function parseAssign(toks, i, registry = null, enumsCatalog = null) {
  const isDefine = toks[i + 2][1] === "defineProperties";
  i += 3;
  if (!isPunct(toks[i], "(")) return ["", false, [], i];
  i += 1;
  const parts = [];
  while (i < toks.length && !isPunct(toks[i], ",")) {
    if (isPunct(toks[i], ".")) {
      i += 1;
      continue;
    }
    if (isKind(toks[i], "ident")) parts.push(toks[i][1]);
    else if (isPunct(toks[i], ")")) return ["", false, [], i];
    i += 1;
  }
  if (!isPunct(toks[i], ",")) return ["", false, [], i];
  i += 1;
  if (!isPunct(toks[i], "{")) return ["", false, [], i];
  const bodyEnd = skipGroup(toks, i, "{", "}");
  if (parts.length === 0 || parts[0] === "module" || parts[0] === "exports")
    return ["", false, [], bodyEnd];
  const target = parts[0];
  const isProto = parts.length >= 2 && parts[parts.length - 1] === "prototype";
  const members = parseAssignBody(toks.slice(i + 1, bodyEnd - 1), isDefine, target, registry, enumsCatalog);
  return [target, isProto, members, bodyEnd];
}

function parseAssignBody(toks, isDefine, target = "", registry = null, enumsCatalog = null) {
  const members = [];
  let i = 0;
  const n = toks.length;
  while (i < n) {
    if (isPunct(toks[i], ",") || isPunct(toks[i], ";")) {
      i += 1;
      continue;
    }
    if (!isKind(toks[i], "ident")) {
      i += 1;
      continue;
    }
    const name = toks[i][1];
    i += 1;
    if (i < n && isPunct(toks[i], ":")) i += 1;
    if (isDefine) {
      if (i < n && isPunct(toks[i], "{")) {
        const end = skipGroup(toks, i, "{", "}");
        const inner = toks.slice(i + 1, end - 1);
        let j = 0;
        while (j < inner.length) {
          if (
            isKind(inner[j], "ident") &&
            (inner[j][1] === "get" || inner[j][1] === "set")
          ) {
            const kind = inner[j][1];
            j += 1;
            if (j < inner.length && isPunct(inner[j], "("))
              j = skipGroup(inner, j, "(", ")");
            let ret = null;
            if (j < inner.length && isPunct(inner[j], "{")) {
              const r = skipBody(inner, j, name, target, registry, enumsCatalog);
              ret = r[0];
              j = r[1];
            }
            members.push({
              name,
              kind,
              static: false,
              params: [],
              returns: ret,
            });
          } else j += 1;
        }
        i = end;
      } else i = skipToSemicolon(toks, i);
      continue;
    }
    if (i < n && isIdent(toks[i], "function")) {
      i += 1;
      let params = [];
      if (i < n && isPunct(toks[i], "(")) {
        const end = skipGroup(toks, i, "(", ")");
        params = splitParams(toks.slice(i + 1, end - 1));
        i = end;
      }
      let ret = null;
      if (i < n && isPunct(toks[i], "{")) {
        const r = skipBody(toks, i, name, target, registry, enumsCatalog);
        ret = r[0];
        i = r[1];
      }
      members.push({
        name,
        kind: "method",
        static: false,
        params,
        returns: ret,
      });
      continue;
    }
    if (i < n && isPunct(toks[i], "(")) {
      const end = skipGroup(toks, i, "(", ")");
      const params = splitParams(toks.slice(i + 1, end - 1));
      i = end;
      let ret = null;
      if (i < n && isPunct(toks[i], "{")) {
        const r = skipBody(toks, i, name, target, registry, enumsCatalog);
        ret = r[0];
        i = r[1];
      }
      members.push({
        name,
        kind: "method",
        static: false,
        params,
        returns: ret,
      });
      continue;
    }
    if (i < n && isPunct(toks[i], "=")) {
      i = skipToComma(toks, i);
      continue;
    }
    i = skipToComma(toks, i);
  }
  return members;
}

function skipToComma(toks, i) {
  let depth = 0;
  while (i < toks.length) {
    const t = toks[i];
    if (isKind(t, "string") || isKind(t, "template")) {
      i += 1;
      continue;
    }
    const v = t[1];
    if ("([{".includes(v)) depth += 1;
    else if (")]}".includes(v)) {
      if (depth === 0) return i;
      depth -= 1;
    } else if (v === "," && depth === 0) return i + 1;
    i += 1;
  }
  return i;
}

function parseStaticAssign(toks, i) {
  const target = toks[i][1];
  if (!isPunct(toks[i + 1], ".") || !isKind(toks[i + 2], "ident"))
    return ["", "", [], false, i + 1];
  const name = toks[i + 2][1];
  let j = i + 3;
  if (!isPunct(toks[j], "=")) return ["", "", [], false, i + 1];
  j += 1;
  const isFn = j < toks.length && isIdent(toks[j], "function");
  if (isFn) j += 1;
  if (j < toks.length && isPunct(toks[j], "(")) {
    const end = skipGroup(toks, j, "(", ")");
    const params = splitParams(toks.slice(j + 1, end - 1));
    j = end;
    if (j < toks.length && isPunct(toks[j], "{"))
      j = skipGroup(toks, j, "{", "}");
    return [target, name, params, isFn, j];
  }
  if (isFn) return [target, name, [], true, j];
  j = skipToSemicolon(toks, j);
  return [target, name, [], false, j];
}

function parseFunction(toks, i) {
  const name = toks[i + 1][1];
  let j = i + 2;
  let params = [];
  if (isPunct(toks[j], "(")) {
    const end = skipGroup(toks, j, "(", ")");
    params = splitParams(toks.slice(j + 1, end - 1));
    j = end;
  }
  if (j < toks.length && isPunct(toks[j], "{"))
    j = skipGroup(toks, j, "{", "}");
  return [name, params, j];
}

const RE_REQUIRE_DESTRUCT =
  /\b(?:const|let|var)\s*\{([^{}]*)\}\s*=\s*require\(\s*(['"])([^'"]+)\2\s*\)/g;
const RE_REQUIRE_SINGLE =
  /\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*require\(\s*(['"])([^'"]+)\3\s*\)/g;
const RE_EXPORT = /\b(?:module\.)?exports\.([A-Za-z_$][\w$]*)\s*=\s*([^;\n]+)/g;
const RE_CLASS = /\bclass\s+([A-Za-z_$][\w$]*)/g;

function sourceModule(spec) {
  if (spec.startsWith("affinity:")) return spec;
  if (spec.startsWith("./") || spec.startsWith("../")) {
    let stem = spec.replace(/\/+$/, "");
    if (stem.endsWith(".js")) stem = stem.slice(0, -3);
    return stem.split("/").pop();
  }
  return null;
}

function parseModule(name, src, registry = null, enumsCatalog = null) {
  const m = {
    name,
    classes: new Map(),
    funcs: new Map(),
    exportNames: [],
    importOrigin: new Map(),
    augmented: new Map(),
  };

  for (const mm of src.matchAll(RE_REQUIRE_DESTRUCT)) {
    const mod = sourceModule(mm[3]);
    if (mod === null) continue;
    for (let raw of mm[1].split(",")) {
      raw = raw.trim();
      if (!raw) continue;
      const ident = raw.split(":").pop().trim();
      if (/^[A-Za-z_$][\w$]*$/.test(ident)) m.importOrigin.set(ident, mod);
    }
  }
  for (const mm of src.matchAll(RE_REQUIRE_SINGLE)) {
    const mod = sourceModule(mm[3]);
    if (mod !== null) m.importOrigin.set(mm[1], mod);
  }

  const toks = lex(src);
  let i = 0;
  const n = toks.length;
  while (i < n) {
    const t = toks[i];
    if (isIdent(t, "class")) {
      const [cls, j] = parseClass(toks, i, registry, enumsCatalog);
      m.classes.set(cls.name, cls);
      i = j;
      continue;
    }
    if (
      isIdent(t, "Object") &&
      i + 2 < n &&
      isPunct(toks[i + 1], ".") &&
      isKind(toks[i + 2], "ident") &&
      (toks[i + 2][1] === "assign" || toks[i + 2][1] === "defineProperties")
    ) {
      const [target, isProto, members, j] = parseAssign(toks, i, registry, enumsCatalog);
      i = j;
      if (target) {
        if (!m.classes.has(target))
          m.classes.set(target, { name: target, parent: null, members: [] });
        if (isProto) m.classes.get(target).members.push(...members);
        else
          for (const mem of members) {
            mem.static = true;
            m.classes.get(target).members.push(mem);
          }
      }
      continue;
    }
    if (isIdent(t, "function")) {
      const [fname, params, j] = parseFunction(toks, i);
      m.funcs.set(fname, params);
      i = j;
      continue;
    }
    if (
      isKind(t, "ident") &&
      !["Object", "module", "exports", "this"].includes(t[1])
    ) {
      const nxt1 = i + 1 < n ? toks[i + 1] : null;
      const nxt2 = i + 2 < n ? toks[i + 2] : null;
      const nxt3 = i + 3 < n ? toks[i + 3] : null;
      if (
        isPunct(nxt1, ".") &&
        nxt2 &&
        isKind(nxt2, "ident") &&
        isPunct(nxt3, "=")
      ) {
        const [target, sname, params, isFn, j] = parseStaticAssign(toks, i);
        i = j;
        if (target && sname) {
          if (!m.classes.has(target))
            m.classes.set(target, { name: target, parent: null, members: [] });
          const kind = isFn ? "method" : "field";
          m.classes
            .get(target)
            .members.push({
              name: sname,
              kind,
              static: true,
              params,
              returns: null,
            });
        }
        continue;
      }
    }
    i += 1;
  }

  for (const em of src.matchAll(RE_EXPORT)) {
    const exportName = em[1];
    const rhs = em[2].trim();
    if (!m.exportNames.includes(exportName)) m.exportNames.push(exportName);
    if (
      /^[A-Za-z_$][\w$]*$/.test(rhs) &&
      !m.classes.has(rhs) &&
      !m.funcs.has(rhs)
    ) {
      if (!m.importOrigin.has(rhs)) m.importOrigin.set(rhs, "");
    }
  }
  return m;
}

// --------------------------------------------------------------------------- //
// Emitter
// --------------------------------------------------------------------------- //

function tsParams(params) {
  if (params.length === 0) return "";
  return params
    .map((p) => {
      if (typeof p === "string") {
        if (p === "callback") return "callback?: (...args: any[]) => any";
        return `${p}?: any`;
      }
      const prefix = p.isRest ? "..." : "";
      const opt = p.optional && !p.isRest ? "?" : "";
      const type = p.type || "any";
      return `${prefix}${p.name}${opt}: ${type}`;
    })
    .join(", ");
}

function emitClass(cls, indent, localNames, overrides) {
  const pad = "  ".repeat(indent);
  const out = [];
  if (cls.parent)
    out.push(`${pad}export class ${cls.name} extends ${cls.parent} {`);
  else out.push(`${pad}export class ${cls.name} {`);

  const order = [];
  const kindByKey = new Map();
  const paramsByKey = new Map();
  const returnsByKey = new Map();
  for (const mem of cls.members) {
    if (mem.name === "constructor") continue;
    const key = `${mem.static}\u0000${mem.name}`;
    if (!kindByKey.has(key)) {
      order.push([mem.name, mem.static]);
      kindByKey.set(key, mem.kind);
      paramsByKey.set(key, mem.params);
      returnsByKey.set(key, mem.returns);
    } else {
      const prev = kindByKey.get(key);
      if (prev === "get" && mem.kind === "set") kindByKey.set(key, "set");
      else if (mem.kind === "get" && prev === "set") {
        /* keep writable */
      } else if (mem.kind === "method" && (prev === "get" || prev === "set"))
        kindByKey.set(key, "method");
      if (mem.params.length) paramsByKey.set(key, mem.params);
      if (mem.returns) returnsByKey.set(key, mem.returns);
    }
  }

  const ctor = cls.members.find(
    (mem) => mem.name === "constructor" && !mem.static,
  );
  if (ctor === undefined) out.push(`${pad}  constructor(...args: any[]);`);
  else out.push(`${pad}  constructor(${tsParams(ctor.params)});`);

  const retType = (key) => {
    const r = returnsByKey.get(key);
    if (r === "this") return "this";
    if (!r) return "any";
    return r;
  };

  const clsOv = overrides?.classes?.[cls.name] || {};
  for (const [name, isStatic] of order) {
    const prefix = isStatic ? "static " : "";
    const key = `${isStatic}\u0000${name}`;
    const kind = kindByKey.get(key);
    const ov = clsOv[name];
    if (ov) {
      out.push(`${pad}  ${ov.raw}`);
      continue;
    }
    if (kind === "method") {
      let paramsList = paramsByKey.get(key) || [];
      // If method is setFoo(v) and property foo exists with a known type, infer v's type
      if (name.startsWith("set") && name.length > 3 && paramsList.length === 1 && (!paramsList[0].type || paramsList[0].type === "any")) {
        const propName = name[3].toLowerCase() + name.slice(4);
        const propKey = `false\u0000${propName}`;
        const propType = returnsByKey.get(propKey);
        if (propType && propType !== "any") {
          paramsList = [{ ...paramsList[0], type: propType }];
        }
      }
      const params = tsParams(paramsList);
      const ret = retType(key);
      out.push(`${pad}  ${prefix}${name}(${params}): ${ret};`);
    } else if (kind === "get") {
      out.push(`${pad}  ${prefix}readonly ${name}: ${retType(key)};`);
    } else {
      out.push(`${pad}  ${prefix}${name}: ${retType(key)};`);
    }
  }
  if (overrides?.classes?.[cls.name]) {
    for (const [name, mem] of Object.entries(overrides.classes[cls.name])) {
      const key = `${mem.static}\u0000${name}`;
      if (!kindByKey.has(key)) {
        out.push(`${pad}  ${mem.raw}`);
      }
    }
  }

  out.push(`${pad}}`);
  return out;
}

function emitEnum(name, entries, indent) {
  const pad = "  ".repeat(indent);
  const out = [
    `${pad}export type ${name} = AffinityEnumValue;`,
    `${pad}export const ${name}: {`,
  ];
  for (const [k] of entries)
    out.push(`${pad}  readonly ${k}: AffinityEnumValue;`);
  out.push(
    `${pad}  readonly keys: readonly string[];`,
    `${pad}  readonly values: readonly number[];`,
    `${pad}  readonly entries: readonly (readonly [string, number])[];`,
    `${pad}  readonly isEnum: true;`,
    `${pad}  parse(value: number): AffinityEnumValue;`,
    `${pad}};`,
  );
  return out;
}

function emitStruct(name, fields, indent, structRanges, structSizes) {
  const pad = "  ".repeat(indent);
  const out = [
    `${pad}export class ${name} {`,
    `${pad}  constructor(...args: any[]);`,
  ];
  const ranges = structRanges[name] || {};
  const sizes = structSizes[name] || {};
  if (fields) {
    for (const f of fields) {
      const rng = ranges[f];
      const size = sizes[f];
      if (rng !== undefined) {
        out.push(`${pad}  /** ${rng} */`);
        out.push(`${pad}  ${f}: number;`);
      } else if (size !== undefined) {
        const sizeExpr = size.size.replace(/^\[|\]$/g, "");
        const element = size.element || "number";
        out.push(`${pad}  /** array size: ${sizeExpr} */`);
        out.push(`${pad}  ${f}: ${element}[];`);
      } else {
        out.push(`${pad}  ${f}: any;`);
      }
    }
  } else {
    out.push(`${pad}  [key: string]: any;`);
  }
  out.push(`${pad}}`);
  return out;
}

function emitNativeModule(
  name,
  enums,
  structs,
  exports,
  api,
  paramRanges,
  structRanges,
  structSizes,
) {
  const lines = [`declare module '${name}' {`];
  for (const enumName of Object.keys(enums).sort())
    lines.push(...emitEnum(enumName, enums[enumName], 1));
  for (const structName of Object.keys(structs).sort())
    lines.push(
      ...emitStruct(
        structName,
        structs[structName],
        1,
        structRanges,
        structSizes,
      ),
    );
  const apiMap = api[name] || {};
  const other = exports.filter((n) => !(n in enums) && !(n in structs));
  for (const n of other.sort()) {
    const methods = apiMap[n];
    if (methods) {
      lines.push(`  export const ${n}: {`);
      const methodRanges = paramRanges[n] || {};
      for (const method of methods) {
        if (Object.hasOwn(methodRanges, method)) {
          const comment = Object.entries(methodRanges[method])
            .map(([p, r]) => `${p}: ${r}`)
            .join("; ");
          lines.push(`    /** ${comment} */`);
        }
        lines.push(`    ${method}(...args: any[]): any;`);
      }
      lines.push("  };");
    } else {
      lines.push(`  export const ${n}: any;`);
    }
  }
  lines.push("}");
  return lines;
}

function classifyExport(name, m, enumsByMod, structsByMod) {
  if (m.classes.has(name) || m.augmented.has(name)) return ["class", m.name];
  if (m.funcs.has(name)) return ["func", m.name];
  const src = m.importOrigin.get(name);
  if (src) {
    if (src.startsWith("affinity:")) {
      if (name in (enumsByMod[src] || {})) return ["native", src];
      if (name in (structsByMod[src] || {})) return ["native", src];
      return ["value", m.name];
    }
    return ["jslib", src];
  }
  return ["value", m.name];
}

function moduleBody(m, registry, enumsByMod, structsByMod, overrides, indent) {
  const pad = "  ".repeat(indent);
  const lines = [];

  const imported = new Map();
  const nativeImported = new Map();
  const localNames = new Set([...m.classes.keys(), ...m.augmented.keys()]);

  for (const cls of [...m.classes.values(), ...m.augmented.values()]) {
    if (cls.parent && cls.parent !== cls.name) {
      const src = registry.get(cls.parent);
      if (src && src !== m.name) imported.set(cls.parent, src);
    }
    for (const mem of cls.members) {
      if (mem.returns) {
        const tokens = mem.returns.split(/[^A-Za-z0-9_$]+/).filter(Boolean);
        for (const tok of tokens) {
          if (tok === "this" || tok === "any" || tok === "boolean" || tok === "number" || tok === "string" || tok === "null" || tok === "undefined" || tok === "void" || tok === "Function") continue;
          if (localNames.has(tok)) continue;
          const jslibSrc = registry.get(tok);
          if (jslibSrc && jslibSrc !== m.name) {
            imported.set(tok, jslibSrc);
          } else {
            let found = false;
            for (const [mod, modEnums] of Object.entries(enumsByMod)) {
              if (tok in modEnums) {
                nativeImported.set(tok, mod);
                found = true;
                break;
              }
            }
            if (!found && structsByMod) {
              for (const [mod, modStructs] of Object.entries(structsByMod)) {
                if (tok in modStructs) {
                  nativeImported.set(tok, mod);
                  break;
                }
              }
            }
          }
        }
      }
      for (const p of mem.params) {
        if (p.type) {
          const tokens = p.type.split(/[^A-Za-z0-9_$]+/).filter(Boolean);
          for (const tok of tokens) {
            if (tok === "this" || tok === "any" || tok === "boolean" || tok === "number" || tok === "string" || tok === "null" || tok === "undefined" || tok === "void" || tok === "Function") continue;
            if (localNames.has(tok)) continue;
            const jslibSrc = registry.get(tok);
            if (jslibSrc && jslibSrc !== m.name) {
              imported.set(tok, jslibSrc);
            } else {
              let found = false;
              for (const [mod, modEnums] of Object.entries(enumsByMod)) {
                if (tok in modEnums) {
                  nativeImported.set(tok, mod);
                  found = true;
                  break;
                }
              }
              if (!found && structsByMod) {
                for (const [mod, modStructs] of Object.entries(structsByMod)) {
                  if (tok in modStructs) {
                    nativeImported.set(tok, mod);
                    break;
                  }
                }
              }
            }
          }
        }
      }
    }
  }

  for (const [pname, src] of [...imported.entries()].sort())
    lines.push(`${pad}import { ${pname} } from '/${src}';`);
  for (const [pname, src] of [...nativeImported.entries()].sort())
    lines.push(`${pad}import { ${pname} } from '${src}';`);
  if (imported.size || nativeImported.size) lines.push("");

  for (const cls of m.augmented.values()) {
    cls.parent = null;
    lines.push(...emitClass(cls, indent, localNames, overrides));
    lines.push("");
  }
  for (const cname of [...m.classes.keys()].sort()) {
    lines.push(
      ...emitClass(m.classes.get(cname), indent, localNames, overrides),
    );
    lines.push("");
  }

  for (const name of m.exportNames) {
    const [kind, src] = classifyExport(name, m, enumsByMod, structsByMod);
    if (kind === "class") continue;
    if (kind === "native")
      lines.push(`${pad}export { ${name} } from '${src}';`);
    else if (kind === "jslib")
      lines.push(`${pad}export { ${name} } from '/${src}';`);
    else if (kind === "func")
      lines.push(
        `${pad}export function ${name}(${tsParams(m.funcs.get(name))}): any;`,
      );
    else lines.push(`${pad}export const ${name}: any;`);
  }

  const extraTypes = overrides?.extraTypes || [];
  for (const extra of extraTypes) {
    lines.push("");
    for (const eline of extra.split("\n")) {
      lines.push(eline ? `${pad}${eline}` : "");
    }
  }
  return lines;
}

const GLOBALS = `\
declare function alert(message?: any): void;
declare function confirm(message?: any): boolean;
declare function prompt(message?: any, defaultValue?: any): string | null;
declare function alertAsync(message?: any): Promise<void>;
declare function confirmAsync(message?: any): Promise<boolean>;
declare function promptAsync(message?: any, defaultValue?: any): Promise<string | null>;
declare function quit(): void;

interface AffinityEnumValue {
  readonly value: number;
  equals(other: AffinityEnumValue): boolean;
  toString(): string;
}

declare var environment: {
  readonly logLevel: any;
  readonly SDKVersion: string;
  readonly V8Version: string;
  quit(): void;
  getHeapStatistics(): any;
  postTask(callback: () => void): void;
};
declare var console: any;

interface TextDecoder {
  decode(input?: any, options?: any): string;
}
declare var TextDecoder: {
  prototype: TextDecoder;
  new (encoding?: string): TextDecoder;
};
declare module '*.json' {
  const value: any;
  export = value;
}
`;

function getJsconfig(
  typesRelDir = "./node_modules/affinity-script-types/types",
) {
  return `\
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "moduleResolution": "node",
    "checkJs": true,
    "allowJs": true,
    "noEmit": true,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "strictNullChecks": false,
    "useUnknownInCatchVariables": false,
    "types": [],
    "paths": {
      "/*": ["${typesRelDir}/*"],
      "/*.js": ["${typesRelDir}/*"]
    }
  },
  "include": ["**/*.js", "${typesRelDir}/**/*.d.ts"]
}
`;
}

const JSCONFIG = getJsconfig();

// --------------------------------------------------------------------------- //
// Orchestration
// --------------------------------------------------------------------------- //

function loadCatalog(which) {
  return JSON.parse(readFileSync(join(HERE, `affinity_${which}.json`), "utf8"));
}

function loadOverrides() {
  const overridesDir = join(HERE, "overrides");
  const overridesByMod = {};
  if (!existsSync(overridesDir)) return overridesByMod;

  for (const file of readdirSync(overridesDir)) {
    if (!file.endsWith(".d.ts")) continue;
    const modName = file.slice(0, -5);
    const content = readFileSync(join(overridesDir, file), "utf8");
    const parsed = { classes: {}, extraTypes: [] };

    let current = [];
    let depth = 0;

    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!depth && (!trimmed || trimmed.startsWith("//") || trimmed.startsWith("import ")))
        continue;
      current.push(line);
      for (const ch of line) {
        if (ch === "{") depth++;
        else if (ch === "}") depth--;
      }
      if (depth === 0 && current.length) {
        const block = current.join("\n").trim();
        current = [];
        const m = block.match(/^export\s+(?:abstract\s+)?class\s+([A-Za-z_$][\w$]*)(?:\s+extends\s+[A-Za-z_$][\w$]*)?\s*\{([\s\S]*)\}$/);
        if (m) {
          const members = {};
          for (const mline of m[2].split("\n")) {
            const raw = mline.trim().replace(/;$/, "");
            if (!raw || raw.startsWith("//")) continue;
            const isStatic = /\bstatic\s+/.test(raw);
            const nameMatch = raw.replace(/\b(?:static|readonly)\s+/g, "").match(/^([A-Za-z_$][\w$]*)/);
            if (nameMatch) {
              members[nameMatch[1]] = { raw: raw + ";", static: isStatic };
            }
          }
          parsed.classes[m[1]] = members;
        } else {
          parsed.extraTypes.push(block);
        }
      }
    }
    overridesByMod[modName] = parsed;
  }
  return overridesByMod;
}

function discoverJslib(jslib) {
  return readdirSync(jslib)
    .filter((f) => f.endsWith(".js"))
    .sort()
    .map((f) => join(jslib, f));
}

function buildRegistry(files) {
  const registry = new Map();
  for (const f of files) {
    const src = readFileSync(f, "utf8");
    for (const m of src.matchAll(RE_CLASS)) {
      if (!registry.has(m[1])) registry.set(m[1], basename(f, ".js"));
    }
  }
  return registry;
}

function finalize(m, structs) {
  for (const cname of [...m.classes.keys()]) {
    const src = m.importOrigin.get(cname) || "";
    if (src.startsWith("affinity:") && cname in (structs[src] || {})) {
      const cls = m.classes.get(cname);
      m.classes.delete(cname);
      for (const fld of structs[src][cname] || [])
        cls.members.unshift({
          name: fld,
          kind: "field",
          static: false,
          params: [],
          returns: null,
        });
      cls.parent = null;
      m.augmented.set(cname, cls);
    }
  }
  return m;
}

function generate(jslib, outDir) {
  const enums = loadCatalog("catalog");
  const structs = loadCatalog("structs");
  const exports = loadCatalog("exports");
  const api = loadCatalog("api");
  const overrides = loadOverrides();
  const paramRanges = loadCatalog("param_ranges");
  const structRanges = loadCatalog("struct_ranges");
  const structSizes = loadCatalog("struct_array_sizes");
  const files = discoverJslib(jslib);
  const registry = buildRegistry(files);

  const typesDir = join(outDir, "types");
  mkdirSync(typesDir, { recursive: true });

  writeFileSync(join(typesDir, "globals.d.ts"), HEADER + GLOBALS, "utf8");

  const nativeLines = [HEADER];
  for (const mod of NATIVE_MODULES) {
    nativeLines.push(
      ...emitNativeModule(
        mod,
        enums[mod] || {},
        structs[mod] || {},
        exports[mod] || [],
        api,
        paramRanges,
        structRanges,
        structSizes,
      ),
    );
    nativeLines.push("");
  }
  writeFileSync(
    join(typesDir, "affinity-native.d.ts"),
    nativeLines.join("\n"),
    "utf8",
  );

  const modules = files.map((f) =>
    finalize(parseModule(basename(f, ".js"), readFileSync(f, "utf8"), registry, enums), structs),
  );

  for (const m of modules) {
    const lines = [
      HEADER,
      ...moduleBody(m, registry, enums, structs, overrides[m.name] || {}, 0),
    ];
    writeFileSync(
      join(typesDir, `${m.name}.d.ts`),
      lines.join("\n") + "\n",
      "utf8",
    );
  }

  const bundled = [HEADER, GLOBALS];
  for (const mod of NATIVE_MODULES) {
    bundled.push(
      ...emitNativeModule(
        mod,
        enums[mod] || {},
        structs[mod] || {},
        exports[mod] || [],
        api,
        paramRanges,
        structRanges,
        structSizes,
      ),
    );
    bundled.push("");
  }
  for (const m of modules) {
    bundled.push(`declare module '/${m.name}' {`);
    bundled.push(...moduleBody(m, registry, enums, structs, overrides[m.name] || {}, 1));
    bundled.push("}");
    bundled.push("");
  }
  writeFileSync(join(typesDir, "affinity.d.ts"), bundled.join("\n"), "utf8");

}

function installConfig(targetDir = process.env.INIT_CWD || process.cwd(), force = false) {
  const cfg = join(targetDir, "jsconfig.json");
  if (!existsSync(cfg) || force) {
    writeFileSync(cfg, getJsconfig("./node_modules/affinity-script-types/types"), "utf8");
    console.log(`[affinity-script-types] wrote ${cfg}`);
  }
}

function main(argv) {
  const isPostinstall =
    argv.includes("--postinstall") ||
    process.env.npm_lifecycle_event === "postinstall";
  const isInit = argv.includes("init") || argv.includes("--init");
  const force = argv.includes("--force");

  if (isInit) {
    const targetDir = process.env.INIT_CWD || process.cwd();
    installConfig(resolve(targetDir), force);
    return 0;
  }

  if (isPostinstall) {
    // When installed as a dependency, ship with pre-generated types inside the package.
    // Postinstall simply ensures jsconfig.json is created in the consumer project.
    const targetDir = process.env.INIT_CWD;
    if (targetDir && resolve(targetDir) !== resolve(HERE)) {
      installConfig(resolve(targetDir), false);
      return 0;
    }
  }

  let jslib = DEFAULT_JSLIB;
  let outDir = process.env.INIT_CWD || join(homedir(), "AffinityScripts");
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--jslib") jslib = argv[++i];
    else if (argv[i] === "--out-dir") outDir = argv[++i];
  }

  let reason = null;
  try {
    if (!statSync(jslib).isDirectory()) reason = "not a directory";
  } catch {
    reason = "not found";
  }
  if (reason === null) {
    try {
      if (!readdirSync(jslib).some((f) => f.endsWith(".js")))
        reason = "empty (no .js modules found)";
    } catch {
      reason = "unreadable";
    }
  }

  if (reason !== null) {
    console.warn("");
    console.warn(
      "[affinity-script-types] Could not regenerate type definitions.",
    );
    console.warn(
      `[affinity-script-types] Affinity's scripting SDK was ${reason} at: ${jslib}`,
    );
    console.warn(
      "[affinity-script-types] Pre-shipped types inside node_modules/affinity-script-types/types remain available.",
    );
    console.warn("");
    return 0;
  }

  try {
    generate(jslib, resolve(outDir));
  } catch (err) {
    console.warn(
      `[affinity-script-types] type generation failed: ${err && err.message ? err.message : err}`,
    );
    return 0;
  }
  console.log(
    `[affinity-script-types] generated types/ in ${resolve(outDir)}`,
  );
  return 0;
}
if (import.meta.url === `file://${process.argv[1]}`)
  process.exit(main(process.argv.slice(2)));
