// Auto-generated by tools/generate_types.py. Do not edit.

export class AppDocuments {
  constructor(...args: any[]);
  readonly all: any;
  readonly current: any;
  load(path?: any): any;
}

export class Application {
  constructor();
  readonly documents: any;
  alert(message?: any, title?: any): any;
  confirm(message?: any, title?: any): any;
  prompt(message?: any, title?: any, initialText?: any): any;
  chooseFile(): any;
  alertAsync(message?: any, title?: any, callback?: any): any;
  confirmAsync(message?: any, title?: any, callback?: any): any;
  promptAsync(message?: any, title?: any, initialText?: any, callback?: any): any;
  chooseFileAsync(callback?: any): any;
  readonly compileDate: any;
  readonly platformName: any;
  readonly shortVersion: any;
  readonly version: any;
  readonly buildVersion: any;
  readonly majorVersion: any;
  readonly minorVersion: any;
  readonly revisionVersion: any;
  readonly documentVersion: any;
  readonly buildKind: any;
  readonly productCopyrightMessage: any;
  readonly productFullName: any;
  readonly productLongName: any;
  readonly productPrimaryFileExtension: any;
  readonly productVersionName: any;
  readonly productShortName: any;
  readonly suiteFullName: any;
  readonly uiParadigm: any;
  readonly argC: any;
  readonly argV: any;
  readonly args: any;
  readonly settings: any;
  readonly getUserDesktopPath: any;
  readonly userDesktopPath: any;
}

export class ApplicationSettings {
  constructor(...args: any[]);
  loadPSDWithEditableText: any;
  readonly undoLimit: any;
}

export const app: any;
export { BuildKind } from 'affinity:application';
export { UiParadigm } from 'affinity:application';
