// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class ArtboardInterface extends HandleObject {
  constructor(handle?: any);
  isSameObject(other?: any): any;
  readonly isArtboardInterface: any;
  isArtboardEnabled: any;
  readonly description: any;
  readonly baseBox: any;
  readonly spreadBaseBox: any;
  readonly topOfPageMargin: any;
  readonly artboardProperties: any;
  readonly node: any;
  readonly physicalRootInterface: any;
  readonly physicalRootProperties: any;
  readonly pageCount: any;
  setArtboardEnabled(enabled?: any, preview?: any): any;
}

