// Auto-generated by tools/generate_types.py. Do not edit.

import { ArtboardProperties } from '/artboardproperties';
import { HandleObject } from '/handleobject';
import { PhysicalRootInterface } from '/physicalrootinterface';

export class ArtboardInterface extends HandleObject {
  constructor(handle?: any);
  isSameObject(other?: any): boolean;
  readonly isArtboardInterface: boolean;
  isArtboardEnabled: boolean;
  readonly description: string;
  readonly baseBox: any;
  readonly spreadBaseBox: any;
  readonly topOfPageMargin: any;
  readonly artboardProperties: ArtboardProperties;
  readonly node: any;
  readonly physicalRootInterface: PhysicalRootInterface;
  readonly physicalRootProperties: any;
  readonly pageCount: number;
  setArtboardEnabled(enabled?: any, preview?: any): any;
}

