// Auto-generated by tools/generate_types.py. Do not edit.

import { FillDescriptor } from '/fills';
import { HandleObject } from '/handleobject';
import { MarginsInterface } from '/marginsinterface';
import { PhysicalRootPropertiesInterface } from '/physicalrootpropertiesinterface';

export class ArtboardProperties extends HandleObject {
  constructor(handle?: any);
  readonly isArtboardProperties: boolean;
  getMarginBox(behaviour?: any): any;
  readonly marginFill: FillDescriptor;
  readonly marginsInterface: MarginsInterface;
  readonly physicalRootPropertiesInterface: PhysicalRootPropertiesInterface;
  readonly node: any;
}

export { EffectiveMarginBehaviour } from 'affinity:dom';
