// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { MarginsInterface } from '/marginsinterface';
import { PhysicalRootPropertiesInterface } from '/physicalrootpropertiesinterface';

export class ArtboardProperties extends HandleObject {
  constructor(handle?: any);
  readonly isArtboardProperties: boolean;
  readonly marginFill: any;
  readonly marginsInterface: MarginsInterface;
  readonly physicalRootPropertiesInterface: PhysicalRootPropertiesInterface;
  readonly node: any;
}

