// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class ArtboardProperties extends HandleObject {
  constructor(handle?: any);
  readonly isArtboardProperties: any;
  getMarginBox(behaviour?: any): any;
  readonly marginFill: any;
  readonly marginsInterface: any;
  readonly physicalRootPropertiesInterface: any;
  readonly node: any;
}

export { EffectiveMarginBehaviour } from 'affinity:dom';
