// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class BlendModeInterface extends HandleObject {
  constructor(handle?: any);
  readonly isBlendModeInterface: any;
  readonly blendMode: any;
  readonly blendOptions: BlendOptions;
  readonly antialiasingMode: any;
  readonly node: any;
  setBlendMode(blendMode?: any, setPassthrough?: any): any;
}

export class BlendOptions extends HandleObject {
  constructor(handle?: any);
  readonly isBlendOptions: any;
  gamma: any;
  masterSourceLayerRanges: any;
  masterUnderlyingCompositionRanges: any;
  getChannelSourceLayerRanges(channel?: any): any;
  setChannelSourceLayerRanges(channel?: any, spline?: any): any;
  getChannelUnderlyingCompositionRanges(channel?: any): any;
  setChannelUnderlyingCompositionRanges(channel?: any, spline?: any): any;
}

export { BlendMode } from 'affinity:common';
export { AntialiasingMode } from 'affinity:dom';
