// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { Spline } from '/geometry';
import { AntialiasingMode } from 'affinity:dom';
import { BlendMode } from 'affinity:common';

export class BlendModeInterface extends HandleObject {
  constructor(handle?: any);
  readonly isBlendModeInterface: boolean;
  readonly blendMode: BlendMode;
  readonly blendOptions: BlendOptions;
  readonly antialiasingMode: AntialiasingMode;
  readonly node: any;
  setBlendMode(blendMode?: any, setPassthrough?: any): any;
}

export class BlendOptions extends HandleObject {
  constructor(handle?: any);
  readonly isBlendOptions: boolean;
  gamma: any;
  masterSourceLayerRanges: Spline;
  masterUnderlyingCompositionRanges: Spline;
  getChannelSourceLayerRanges(channel?: any): Spline;
  setChannelSourceLayerRanges(channel?: any, spline?: any): this;
  getChannelUnderlyingCompositionRanges(channel?: any): Spline;
  setChannelUnderlyingCompositionRanges(channel?: any, spline?: any): this;
}

export { BlendMode } from 'affinity:common';
export { AntialiasingMode } from 'affinity:dom';
