// Auto-generated by tools/generate_types.py. Do not edit.

import { FillDescriptor } from '/fills';
import { HandleObject } from '/handleobject';
import { ContentType } from 'affinity:dom';
import { SubSelectionType } from 'affinity:dom';

export class BrushFillInterface extends HandleObject {
  constructor(handle?: any);
  readonly isBrushFillInterface: boolean;
  readonly isNoFill: boolean;
  getIsVisible(minAlpha?: any): boolean;
  domainTransform(): any;
  readonly contentType: ContentType;
  readonly descriptorCount: number;
  getDescriptor(index?: any, obeyScaleWithObject?: boolean): FillDescriptor;
  getCurrentDescriptor(obeyScaleWithObject?: boolean): FillDescriptor;
  readonly currentIndex: number;
  enumerateDescriptors(callback?: (...args: any[]) => any, obeyScaleWithObject?: boolean): any;
  readonly subSelectionCount: number;
  getSubSelection(index?: any): SubSelectionType;
  readonly node: any;
  setCurrentDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): this;
  currentDescriptor: any;
  getAllDescriptors(obeyScaleWithObject?: boolean): any;
  isAnchoredToSpread: boolean;
  setIsAnchoredToSpread(anchored?: any, applyToAllFills?: any, preview?: any): any;
  fillDescriptor: any;
  readonly allDescriptors: any;
}

export { ContentType } from 'affinity:dom';
