// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class BrushFillInterface extends HandleObject {
  constructor(handle?: any);
  readonly isBrushFillInterface: any;
  readonly isNoFill: any;
  getIsVisible(minAlpha?: any): any;
  domainTransform(): any;
  readonly contentType: any;
  readonly descriptorCount: any;
  getDescriptor(index?: any, obeyScaleWithObject?: any): any;
  getCurrentDescriptor(obeyScaleWithObject?: any): any;
  readonly currentIndex: any;
  enumerateDescriptors(callback?: (...args: any[]) => any, obeyScaleWithObject?: any): any;
  readonly subSelectionCount: any;
  getSubSelection(index?: any): any;
  readonly node: any;
  setCurrentDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): any;
  currentDescriptor: any;
  getAllDescriptors(obeyScaleWithObject?: any): any;
  isAnchoredToSpread: any;
  setIsAnchoredToSpread(anchored?: any, applyToAllFills?: any, preview?: any): any;
  fillDescriptor: any;
  readonly allDescriptors: any;
}

export { ContentType } from 'affinity:dom';
