// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class Buffer extends HandleObject {
  constructor(handle?: any);
  static create(sz?: any): Buffer;
  clone(): Buffer;
  span(start?: any, end?: any): Buffer;
  slice(start?: any, end?: any): Buffer;
  readonly size: any;
  readonly arrayBuffer: any;
  equals(other?: any): any;
  compare(other?: any): any;
  compareSome(start1?: any, end1?: any, other?: any, start2?: any, end2?: any): any;
  undefined
  readonly length: any;
  readonly buffer: any;
  readonly array: any;
  readonly items: any;
  concat(other?: any): any;
  reverse(): this;
  static utf16(str?: any): any;
  static utf8(str?: any): any;
}

