// Auto-generated by tools/generate_types.py. Do not edit.

export class Collection {
  constructor(genFunc?: any);
  readonly generator: any;
  static empty(): any;
  static fibonacci(i?: any, j?: any): Collection;
  static of(items?: any): SpanCollection;
  static over(seq?: any): SpanCollection;
  static random(): Collection;
  static range(start?: any, count?: any): RangeCollection;
  append(others?: any): Collection;
  entries(): Collection;
  filter(predicate?: any, thisArg?: any): Collection;
  flat(depth?: any, flattenStrings?: any): Collection;
  keys(): Collection;
  lastN(num?: any): Collection;
  map(mapFunc?: any, thisArg?: any): Collection;
  notNull(noCoercion?: any): any;
  repeat(num?: any): Collection;
  repeatForever(): Collection;
  reverse(): Collection;
  skip(num?: any): Collection;
  skipWhile(whileFunc?: any, thisArg?: any): Collection;
  some(predicate?: any, thisArg?: any): any;
  take(num?: any): Collection;
  takeWhile(whileFunc?: any, thisArg?: any): Collection;
  zip(other?: any): Collection;
  leftZip(other?: any): Collection;
  rightZip(other?: any): Collection;
  all(predicate?: any, thisArg?: any): any;
  any(predicate?: any, thisArg?: any): any;
  at(index?: any): any;
  countIf(predicate?: any, thisArg?: any): any;
  readonly first: any;
  forEach(callback?: (...args: any[]) => any, thisArg?: any): any;
  readonly last: any;
  readonly length: any;
  readonly isEmpty: any;
  none(predicate?: any, thisArg?: any): any;
  reduce(reduceFunc?: any, initialValue?: any): any;
  join(sep?: any): any;
  toArray(): any;
}

export class RangeCollection extends Collection {
  constructor(start?: any, length?: any, decrementing?: any);
  reverse(): RangeCollection;
  skip(num?: any): RangeCollection;
  take(num?: any): RangeCollection;
  at(index?: any): any;
  readonly first: any;
  readonly last: any;
  readonly length: any;
  readonly isEmpty: any;
}

export class SpanCollection extends Collection {
  constructor(span?: any, begin?: any, end?: any);
  readonly first: any;
  readonly last: any;
  readonly length: any;
  take(num?: any): SpanCollection;
  skip(num?: any): SpanCollection;
  reverse(): SpanCollection;
  at(index?: any): any;
  readonly isEmpty: any;
}

