// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class CompoundOperationInterface extends HandleObject {
  constructor(handle?: any);
  readonly isCompoundOperationInterface: any;
  readonly compoundOperation: any;
  readonly node: any;
}

export { CompoundOperation } from 'affinity:dom';
