// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { CompoundOperation } from 'affinity:dom';

export class CompoundOperationInterface extends HandleObject {
  constructor(handle?: any);
  readonly isCompoundOperationInterface: boolean;
  readonly compoundOperation: CompoundOperation;
  readonly node: any;
}

export { CompoundOperation } from 'affinity:dom';
