// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { ConfigurationValueType } from 'affinity:common';

export class ConfigurationItem extends HandleObject {
  constructor(handle?: any);
  static createFromJsonString(jsonStr?: any, allowComments?: boolean): any;
  readonly valueType: ConfigurationValueType;
  readonly isObject: boolean;
  readonly isArray: boolean;
  readonly isString: boolean;
  readonly isNumber: boolean;
  readonly isFloat: boolean;
  readonly isUint: boolean;
  readonly isInt: boolean;
  readonly isBool: boolean;
  readonly isNull: boolean;
  readonly isBinary: boolean;
  readonly isPrimitive: boolean;
  readonly isStructured: boolean;
  readonly string: any;
  readonly float: any;
  readonly int: any;
  readonly uint: any;
  readonly bool: any;
  readonly value: ConfigurationValueType;
  stringOrDefault(defaultValue?: any): any;
  floatOrDefault(defaultValue?: any): any;
  intOrDefault(defaultValue?: any): any;
  uintOrDefault(defaultValue?: any): any;
  boolOrDefault(defaultValue?: any): any;
  getArrayLength(): number;
  getArrayItem(index?: any): any;
  readonly propertyCount: number;
  hasProperty(name?: string): boolean;
  getProperty(name?: string): any;
  getPropertyString(name?: string): any;
  getPropertyStringOrDefault(name?: string, defaultValue?: any): any;
  getPropertyFloat(name?: string): any;
  getPropertyFloatOrDefault(name?: string, defaultValue?: any): any;
  getPropertyInt(name?: string): any;
  getPropertyIntOrDefault(name?: string, defaultValue?: any): any;
  getPropertyUint(name?: string): any;
  getPropertyUintOrDefault(name?: string, defaultValue?: any): any;
  getPropertyBool(name?: string): any;
  getPropertyBoolOrDefault(name?: string, defaultValue?: any): any;
  enumerateProperties(callback?: (...args: any[]) => any): any;
  enumeratePropertyNames(callback?: (...args: any[]) => any): any;
  enumerateItems(callback?: (...args: any[]) => any): any;
  readonly properties: any;
  readonly propertyNames: any;
  readonly items: any;
}

export class ConfigurationProperty {
  constructor(name?: string, item?: any);
}

export { ConfigurationValueType } from 'affinity:common';
