// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class CurvesInterface extends HandleObject {
  constructor(handle?: any);
  readonly polyCurve: any;
  readonly corneredPolyCurve: any;
  readonly polyPolyCurves: any;
  readonly windingOrder: any;
  readonly domainTransform: any;
  getSubSelectionCount(subSelectionType?: any): any;
  getSubSelection(subSelectionType?: any, index?: any): any;
  readonly node: any;
  readonly isMutable: any;
}

export { SubSelectionType } from 'affinity:dom';
export { WindingOrder } from 'affinity:geometry';
