// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class DescriptionInterface extends HandleObject {
  constructor(handle?: any);
  userDescription: any;
  readonly description: any;
  readonly defaultDescription: any;
  readonly defaultDescriptionForDisplay: any;
  getTagColour(inferFromAncestors?: any): any;
  tagColour: any;
  getDescription(descriptionOnEmpty?: any): any;
  readonly node: any;
  setUserDescription(description?: any, preview?: any): any;
  setTagColour(colour?: any, preview?: any): any;
  setUserDescriptionAsync(description?: any, callback?: (...args: any[]) => any, preview?: any): any;
  setTagColourAsync(colour?: any, callback?: (...args: any[]) => any, preview?: any): any;
}

