// Auto-generated by tools/generate_types.py. Do not edit.

import { Collection } from '/collection';
import { HandleObject } from '/handleobject';

export class Dialog extends HandleObject {
  constructor(handle?: any);
  readonly columns: any;
  static create(text?: any): Dialog;
  show(): any;
  runModal(): any;
  findControl(ctrlID?: any): any;
  initialWidth: any;
  addColumn(): DialogColumn;
  readonly groups: any;
  readonly controls: any;
  setIsResizable(value?: any): this;
  isResizable: any;
  readonly isRunningModal: any;
  setOnControlValueChangedHandler(handler?: any): this;
  onControlValueChangedHandler: any;
  setItemsVisibility(showIDs?: any, hideIDs?: any): this;
  [key: string]: any;
}

export class DialogBoolControl extends DialogControl {
  constructor(handle?: any);
  value: any;
  setValue(value?: any): this;
}

export class DialogButton extends DialogControl {
  constructor(handle?: any);
  isFullWidth: any;
  setIsFullWidth(b?: any): this;
  alignment: any;
  setAlignment(alignment?: any): this;
  onClickHandler: any;
  setOnClickHandler(handler?: any): this;
}

export class DialogButtonSet extends DialogEnumControl {
  constructor(handle?: any);
  isFullWidth: any;
  setIsFullWidth(b?: any): this;
}

export class DialogCheckBox extends DialogBoolControl {
  constructor(handle?: any);
  isFullWidth: any;
  setIsFullWidth(b?: any): this;
}

export class DialogColourPicker extends DialogControl {
  constructor(handle?: any);
  isFullWidth: any;
  setIsFullWidth(b?: any): this;
  value: any;
  allowPickNone: any;
  setAllowPickNone(b?: any): this;
  allowNoise: any;
  setAllowNoise(b?: any): this;
}

export class DialogColumn extends DialogItem {
  constructor(handle?: any);
  readonly groups: any;
  widthProportion: any;
  setWidthProportion(value?: any): this;
  paddingFactor: any;
  setPaddingFactor(value?: any): this;
  readonly columnIndex: any;
  addGroup(name?: any): DialogGroup;
  readonly controls: any;
}

export class DialogColumnGroups extends Collection {
  constructor(columnHandle?: any);
  readonly length: any;
  at(index?: any): DialogGroup;
}

export class DialogColumnStack extends DialogItem {
  constructor(handle?: any);
  readonly columns: any;
  addColumn(): DialogColumn;
}

export class DialogColumnStackColumns extends Collection {
  constructor(columnStackHandle?: any);
  readonly length: any;
  at(index?: any): DialogColumn;
}

export class DialogColumns extends Collection {
  constructor(dialogHandle?: any);
  readonly length: any;
  at(index?: any): DialogColumn;
}

export class DialogComboBox extends DialogEnumControl {
  constructor(handle?: any);
  isFullWidth: any;
  setIsFullWidth(b?: any): this;
}

export class DialogControl extends DialogItem {
  constructor(handle?: any);
  readonly controlID: any;
  readonly controlType: any;
  isEnabled: any;
  setIsEnabled(enabled?: any): this;
  readonly label: any;
  setIsEnabledBy(ctrlOrCtrlID?: any): this;
  setIsEnabledByWithSelectedIndex(ctrlOrCtrlID?: any, index?: any): this;
  setIsDisabledBy(ctrlOrCtrlID?: any): this;
  setIsDisabledByWithSelectedIndex(ctrlOrCtrlID?: any, index?: any): this;
  setIsEnabledByControlID(ctrlID?: any): this;
  setIsDisabledByControlID(ctrlID?: any): this;
  setIsEnabledByControlIDWithSelectedIndex(ctrlID?: any, item?: any): this;
  setIsDisabledByControlIDWithSelectedIndex(ctrlID?: any, item?: any): this;
  description: any;
  setDescription(value?: any): this;
  onValueChangedHandler: any;
  setOnValueChangedHandler(handler?: any): this;
}

export class DialogEnumControl extends DialogControl {
  constructor(handle?: any);
  selectedIndex: any;
  setSelectedIndex(index?: any): this;
}

export class DialogFillEditor extends DialogControl {
  constructor(handle?: any);
  isFullWidth: any;
  setIsFullWidth(b?: any): this;
  fill: any;
  setFill(fill?: any): this;
  isStrokeFill: any;
  setIsStrokeFill(b?: any): this;
}

export class DialogFontPicker extends DialogControl {
  constructor(handle?: any);
  isFullWidth: any;
  setIsFullWidth(b?: any): this;
  text: any;
  setText(text?: any): this;
  font: any;
  setFont(font?: any): this;
  fontFamily: any;
  setFontFamily(fontFamily?: any): this;
  fontCollection: any;
  setFontCollection(fontCollection?: any): this;
}

export class DialogGroup extends DialogItem {
  constructor(handle?: any);
  readonly controls: any;
  readonly label: any;
  readonly column: DialogColumn;
  enableSeparator: any;
  setEnableSeparator(enable?: any): this;
  addButtonSet(label?: any, items?: any, initialItem?: any): DialogButtonSet;
  addCheckBox(label?: any, initialValue?: any): DialogCheckBox;
  addComboBox(label?: any, items?: any, initialItem?: any): DialogComboBox;
  addRadioGroup(label?: any, items?: any, initialItem?: any): DialogRadioGroup;
  addStaticText(label?: any, text?: any): DialogStaticText;
  addTextBox(label?: any, text?: any): DialogTextBox;
  addSwitch(label?: any, initialValue?: any): DialogSwitch;
  addUnitValueEditor(label?: any, units?: any, displayUnits?: any, initialValue?: any, minValue?: any, maxValue?: any): DialogUnitValueEditor;
  addUserUnitValueEditor(label?: any, units?: any, displayUnits?: any, initialValue?: any, minValue?: any, maxValue?: any): DialogUnitValueEditor;
  addSpatialAnchor(label?: any, initialValue?: any): DialogSpatialAnchor;
  addColourPicker(label?: any, initialValue?: any): DialogColourPicker;
  addFontPicker(label?: any): DialogFontPicker;
  addFillEditor(label?: any, initialFill?: any): DialogFillEditor;
  addStrokeEditor(label?: any, initialLineStyleDescriptor?: any): DialogStrokeEditor;
  addColumnStack(): DialogColumnStack;
  addButton(label?: any): DialogButton;
}

export class DialogGroupControls extends Collection {
  constructor(groupHandle?: any);
  readonly length: any;
  at(index?: any): any;
}

export class DialogItem extends HandleObject {
  constructor(handle?: any);
  readonly itemID: any;
  readonly itemType: any;
  isVisible: any;
  setIsVisible(visible?: any): this;
}

export class DialogRadioGroup extends DialogEnumControl {
  constructor(handle?: any);
  isFullWidth: any;
  setIsFullWidth(b?: any): this;
}

export class DialogSpatialAnchor extends DialogControl {
  constructor(handle?: any);
  value: any;
}

export class DialogStaticText extends DialogTextControl {
  constructor(handle?: any);
}

export class DialogStrokeEditor extends DialogControl {
  constructor(handle?: any);
  isFullWidth: any;
  setIsFullWidth(b?: any): this;
  stroke: any;
  setStroke(stroke?: any): this;
}

export class DialogSwitch extends DialogBoolControl {
  constructor(handle?: any);
}

export class DialogTextBox extends DialogTextControl {
  constructor(handle?: any);
  isMultiLine: any;
  setIsMultiLine(value?: any): this;
  rowSpan: any;
  setRowSpan(rowSpan?: any): this;
}

export class DialogTextControl extends DialogControl {
  constructor(handle?: any);
  isFullWidth: any;
  setIsFullWidth(b?: any): this;
  text: any;
  setText(text?: any): this;
  textHorizontalAlignment: any;
  setTextHorizontalAlignment(alignment?: any): this;
}

export class DialogUnitValueEditor extends DialogControl {
  constructor(handle?: any);
  isFullWidth: any;
  setIsFullWidth(b?: any): this;
  value: any;
  setValue(value?: any): this;
  readonly units: any;
  noMinValue: any;
  setNoMinValue(value?: any): this;
  noMaxValue: any;
  setNoMaxValue(value?: any): this;
  showPopupSlider: any;
  setShowPopupSlider(value?: any): this;
  precision: any;
  setPrecision(precision?: any): this;
}

export { DialogItemType } from 'affinity:ui';
export { DialogResult } from 'affinity:ui';
export { HorizontalAlignment } from 'affinity:common';
export { SpatialAnchor } from 'affinity:dom';
export { UnitType } from 'affinity:common';
export { UserUnitType } from 'affinity:common';
export const DialogControlType: any;
