// Auto-generated by tools/generate_types.py. Do not edit.

import { Collection } from '/collection';
import { Fill } from '/fills';
import { Font } from '/fonts';
import { FontCollection } from '/fonts';
import { FontFamily } from '/fonts';
import { HandleObject } from '/handleobject';
import { DialogItemType } from 'affinity:ui';
import { DialogResult } from 'affinity:ui';
import { SpatialAnchor } from 'affinity:dom';
import { UnitType } from 'affinity:common';

export class Dialog extends HandleObject {
  constructor(handle?: any);
  readonly columns: DialogColumns;
  static create(text?: string): Dialog;
  show(): void;
  runModal(): DialogResult;
  findControl(ctrlID?: any): DialogControl;
  initialWidth: number;
  addColumn(): DialogColumn;
  readonly groups: DialogGroup[];
  readonly controls: DialogControl[];
  setIsResizable(value?: boolean): this;
  isResizable: boolean;
  readonly isRunningModal: boolean;
  setOnControlValueChangedHandler(handler?: any): this;
  onControlValueChangedHandler: any;
  setItemsVisibility(showIDs?: any, hideIDs?: any): this;
}

export class DialogBoolControl extends DialogControl {
  constructor(handle?: any);
  value: any;
  setValue(value?: any): this;
}

export class DialogButton extends DialogControl {
  constructor(handle?: any);
  isFullWidth: boolean;
  setIsFullWidth(b?: boolean): this;
  alignment: any;
  setAlignment(alignment?: any): this;
  onClickHandler: any;
  setOnClickHandler(handler?: any): this;
}

export class DialogButtonSet extends DialogEnumControl {
  constructor(handle?: any);
  isFullWidth: boolean;
  setIsFullWidth(b?: boolean): this;
}

export class DialogCheckBox extends DialogBoolControl {
  constructor(handle?: any);
  isFullWidth: boolean;
  setIsFullWidth(b?: boolean): this;
}

export class DialogColourPicker extends DialogControl {
  constructor(handle?: any);
  isFullWidth: boolean;
  setIsFullWidth(b?: boolean): this;
  value: any;
  allowPickNone: any;
  setAllowPickNone(b?: boolean): this;
  allowNoise: any;
  setAllowNoise(b?: boolean): this;
}

export class DialogColumn extends DialogItem {
  constructor(handle?: any);
  readonly groups: DialogColumnGroups;
  widthProportion: number;
  setWidthProportion(value?: number): this;
  paddingFactor: number;
  setPaddingFactor(value?: number): this;
  readonly columnIndex: number;
  addGroup(name?: string): DialogGroup;
  readonly controls: DialogControl[];
}

export class DialogColumnGroups extends Collection {
  constructor(columnHandle?: any);
  readonly length: number;
  at(index?: any): DialogGroup;
}

export class DialogColumnStack extends DialogItem {
  constructor(handle?: any);
  readonly columns: DialogColumnStackColumns;
  addColumn(): DialogColumn;
}

export class DialogColumnStackColumns extends Collection {
  constructor(columnStackHandle?: any);
  readonly length: number;
  at(index?: any): DialogColumn;
}

export class DialogColumns extends Collection {
  constructor(dialogHandle?: any);
  readonly length: number;
  at(index?: any): DialogColumn;
}

export class DialogComboBox extends DialogEnumControl {
  constructor(handle?: any);
  isFullWidth: boolean;
  setIsFullWidth(b?: boolean): this;
}

export class DialogControl extends DialogItem {
  constructor(handle?: any);
  readonly controlID: number;
  readonly controlType: any;
  isEnabled: boolean;
  setIsEnabled(enabled?: boolean): this;
  readonly label: string;
  setIsEnabledBy(ctrlOrCtrlID?: any): this;
  setIsEnabledByWithSelectedIndex(ctrlOrCtrlID?: any, index?: any): this;
  setIsDisabledBy(ctrlOrCtrlID?: any): this;
  setIsDisabledByWithSelectedIndex(ctrlOrCtrlID?: any, index?: any): this;
  setIsEnabledByControlID(ctrlID?: any): this;
  setIsDisabledByControlID(ctrlID?: any): this;
  setIsEnabledByControlIDWithSelectedIndex(ctrlID?: any, item?: any): this;
  setIsDisabledByControlIDWithSelectedIndex(ctrlID?: any, item?: any): this;
  description: string;
  setDescription(value?: string): this;
  onValueChangedHandler: any;
  setOnValueChangedHandler(handler?: any): this;
}

export class DialogEnumControl extends DialogControl {
  constructor(handle?: any);
  selectedIndex: number;
  setSelectedIndex(index?: number): this;
}

export class DialogFillEditor extends DialogControl {
  constructor(handle?: any);
  isFullWidth: boolean;
  setIsFullWidth(b?: boolean): this;
  fill: Fill;
  setFill(fill?: Fill): this;
  isStrokeFill: boolean;
  setIsStrokeFill(b?: boolean): this;
}

export class DialogFontPicker extends DialogControl {
  constructor(handle?: any);
  isFullWidth: boolean;
  setIsFullWidth(b?: boolean): this;
  text: string;
  setText(text?: string): this;
  font: Font;
  setFont(font?: Font): this;
  fontFamily: FontFamily;
  setFontFamily(fontFamily?: FontFamily): this;
  fontCollection: FontCollection;
  setFontCollection(fontCollection?: FontCollection): this;
}

export class DialogGroup extends DialogItem {
  constructor(handle?: any);
  readonly controls: DialogGroupControls;
  readonly label: string;
  readonly column: DialogColumn;
  enableSeparator: any;
  setEnableSeparator(enable?: boolean): this;
  addButtonSet(label?: any, items?: any, initialItem?: any): DialogButtonSet;
  addCheckBox(label?: any, initialValue?: any): DialogCheckBox;
  addComboBox(label?: any, items?: any, initialItem?: any): DialogComboBox;
  addRadioGroup(label?: any, items?: any, initialItem?: any): DialogRadioGroup;
  addStaticText(label?: any, text?: string): DialogStaticText;
  addTextBox(label?: any, text?: string): DialogTextBox;
  addSwitch(label?: any, initialValue?: any): DialogSwitch;
  addUnitValueEditor(label?: any, units?: any, displayUnits?: any, initialValue?: any, minValue?: any, maxValue?: any): DialogUnitValueEditor;
  addUserUnitValueEditor(label?: any, units?: any, displayUnits?: any, initialValue?: any, minValue?: any, maxValue?: any): DialogUnitValueEditor;
  addSpatialAnchor(label?: any, initialValue?: SpatialAnchor): DialogSpatialAnchor;
  addColourPicker(label?: any, initialValue?: any): DialogColourPicker;
  addFontPicker(label?: any): DialogFontPicker;
  addFillEditor(label?: any, initialFill?: any): DialogFillEditor;
  addStrokeEditor(label?: any, initialLineStyleDescriptor?: any): DialogStrokeEditor;
  addColumnStack(): DialogColumnStack;
  addButton(label?: any): DialogButton;
}

export class DialogGroupControls extends Collection {
  constructor(groupHandle?: any);
  readonly length: number;
  at(index?: any): DialogControl;
}

export class DialogItem extends HandleObject {
  constructor(handle?: any);
  readonly itemID: number;
  readonly itemType: DialogItemType;
  isVisible: boolean;
  setIsVisible(visible?: boolean): this;
}

export class DialogRadioGroup extends DialogEnumControl {
  constructor(handle?: any);
  isFullWidth: boolean;
  setIsFullWidth(b?: boolean): this;
}

export class DialogSpatialAnchor extends DialogControl {
  constructor(handle?: any);
  value: any;
}

export class DialogStaticText extends DialogTextControl {
  constructor(handle?: any);
}

export class DialogStrokeEditor extends DialogControl {
  constructor(handle?: any);
  isFullWidth: boolean;
  setIsFullWidth(b?: boolean): this;
  stroke: any;
  setStroke(stroke?: any): this;
}

export class DialogSwitch extends DialogBoolControl {
  constructor(handle?: any);
}

export class DialogTextBox extends DialogTextControl {
  constructor(handle?: any);
  isMultiLine: boolean;
  setIsMultiLine(value?: boolean): this;
  rowSpan: any;
  setRowSpan(rowSpan?: any): this;
}

export class DialogTextControl extends DialogControl {
  constructor(handle?: any);
  isFullWidth: boolean;
  setIsFullWidth(b?: boolean): this;
  text: string;
  setText(text?: string): this;
  textHorizontalAlignment: any;
  setTextHorizontalAlignment(alignment?: any): this;
}

export class DialogUnitValueEditor extends DialogControl {
  constructor(handle?: any);
  isFullWidth: boolean;
  setIsFullWidth(b?: boolean): this;
  value: any;
  setValue(value?: any): this;
  readonly units: UnitType;
  noMinValue: boolean;
  setNoMinValue(value?: boolean): this;
  noMaxValue: boolean;
  setNoMaxValue(value?: boolean): this;
  showPopupSlider: any;
  setShowPopupSlider(value?: boolean): this;
  precision: number;
  setPrecision(precision?: number): this;
}

export { DialogItemType } from 'affinity:ui';
export { DialogResult } from 'affinity:ui';
export { HorizontalAlignment } from 'affinity:common';
export { SpatialAnchor } from 'affinity:dom';
export { UnitType } from 'affinity:common';
export { UserUnitType } from 'affinity:common';
export const DialogControlType: any;
