// Auto-generated by tools/generate_types.py. Do not edit.

import { ColourProfile } from '/colours';
import { DrawingScale } from '/drawingscale';
import { FillDescriptor } from '/fills';
import { HandleObject } from '/handleobject';
import { UnitType } from 'affinity:common';

export class ArtboardDocumentProperties extends HandleObject {
  constructor(handle?: any);
  static create(): ArtboardDocumentProperties;
  margin: any;
  setMargin(margin?: any): this;
  useMargin: any;
  setUseMargin(useMargin?: any): this;
  drawingScale: DrawingScale;
  setDrawingScale(drawingScale?: DrawingScale): this;
  useDrawingScale: any;
  setUseDrawingScale(useDrawingScale?: any): this;
  dimensions: any;
  setDimensions(dimensions?: any): this;
  anchorType: any;
  setAnchorType(anchorType?: any): this;
}

export class DocumentProperties extends HandleObject {
  constructor(handle?: any);
  static create(): DocumentProperties;
  readonly colourFormat: any;
  readonly colourProfile: ColourProfile;
  setColourFormatAndProfile(rasterFormat?: any, colourProfile?: any): this;
  units: UnitType;
  shouldReflowPages: boolean;
  readonly dpi: number;
  readonly viewDpi: number;
  setDpi(dpi?: any, viewDpi?: number): this;
  drawingScale: DrawingScale;
  pageWidth: number;
  pageHeight: number;
  margin: any;
  marginFill: FillDescriptor;
  bleed: any;
  bleedFill: FillDescriptor;
  includeMargins: any;
  isRetina: boolean;
  isPortrait: boolean;
  isTransparent: boolean;
  saveHistory: boolean;
  isFacingPages: boolean;
  isFullSpreadStart: boolean;
  isVerticalStack: boolean;
  imageResourcePolicy: any;
  linkTextFiles: boolean;
  preserveTextStyles: boolean;
  assignColourProfile: any;
  resamplerType: any;
}

export class SpreadDocumentProperties extends ArtboardDocumentProperties {
  constructor(handle?: any);
  static create(): SpreadDocumentProperties;
  useMasterMargin: any;
  setUseMasterMargin(useMasterMargin?: any): this;
  useMasterDrawingScale: any;
  setUseMasterDrawingScale(useMasterDrawingScale?: any): this;
  reflowPages: any;
  setReflowPages(reflowPages?: any): this;
  resamplerType: any;
  setResamplerType(resamplerType?: any): this;
}

export { ImagePlacement } from 'affinity:dom';
export { RasterFormat } from 'affinity:raster';
export { RasterResamplerType } from 'affinity:raster';
export { SpatialAnchor } from 'affinity:dom';
export { UnitType } from 'affinity:common';
