// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class ArtboardDocumentProperties extends HandleObject {
  constructor(handle?: any);
  static create(): ArtboardDocumentProperties;
  margin: any;
  setMargin(margin?: any): this;
  useMargin: any;
  setUseMargin(useMargin?: any): this;
  drawingScale: any;
  setDrawingScale(drawingScale?: any): this;
  useDrawingScale: any;
  setUseDrawingScale(useDrawingScale?: any): this;
  dimensions: any;
  setDimensions(dimensions?: any): this;
  anchorType: any;
  setAnchorType(anchorType?: any): this;
}

export class DocumentProperties extends HandleObject {
  constructor(handle?: any);
  static create(): DocumentProperties;
  readonly colourFormat: any;
  readonly colourProfile: any;
  setColourFormatAndProfile(rasterFormat?: any, colourProfile?: any): any;
  units: any;
  shouldReflowPages: any;
  readonly dpi: any;
  readonly viewDpi: any;
  setDpi(dpi?: any, viewDpi?: any): any;
  drawingScale: any;
  pageWidth: any;
  pageHeight: any;
  margin: any;
  marginFill: any;
  bleed: any;
  bleedFill: any;
  includeMargins: any;
  isRetina: any;
  isPortrait: any;
  isTransparent: any;
  saveHistory: any;
  isFacingPages: any;
  isFullSpreadStart: any;
  isVerticalStack: any;
  imageResourcePolicy: any;
  linkTextFiles: any;
  preserveTextStyles: any;
  assignColourProfile: any;
  resamplerType: any;
}

export class SpreadDocumentProperties extends ArtboardDocumentProperties {
  constructor(handle?: any);
  static create(): SpreadDocumentProperties;
  useMasterMargin: any;
  setUseMasterMargin(useMasterMargin?: any): this;
  useMasterDrawingScale: any;
  setUseMasterDrawingScale(useMasterDrawingScale?: any): this;
  reflowPages: any;
  setReflowPages(reflowPages?: any): this;
  resamplerType: any;
  setResamplerType(resamplerType?: any): this;
}

export { ImagePlacement } from 'affinity:dom';
export { RasterFormat } from 'affinity:raster';
export { RasterResamplerType } from 'affinity:raster';
export { SpatialAnchor } from 'affinity:dom';
export { UnitType } from 'affinity:common';
