// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class DrawingScale extends HandleObject {
  constructor(handle?: any);
  undefined
  readonly leftValue: any;
  readonly rightValue: any;
  static enumerateDefaults(units?: any, callback?: (...args: any[]) => any): any;
  static getDefaults(units?: any): any;
  static createFromIntegers(left?: any, right?: any, simplifyFaction?: any): DrawingScale;
  static create(leftUnitValue?: any, rightUnitValue?: any): DrawingScale;
  static createFromString(str?: any, simplifyFraction?: any, simplifyDecimalPlaces?: any, allowOneToOne?: any): DrawingScale;
  static readonly identity: any;
}

export { UnitType } from 'affinity:common';
