// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class EditabilityInterface extends HandleObject {
  constructor(handle?: any);
  readonly isEditable: boolean;
  readonly isLocalEditable: boolean;
  readonly isMasterEditable: boolean;
  readonly node: any;
}

