// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { ExportScaleSizeType } from 'affinity:dom';

export class ExportConfig extends HandleObject {
  constructor(handle?: any);
  appendFormat(exportFormat?: any): any;
  deleteFormat(index?: any): any;
  replaceFormat(index?: any, exportFormat?: any): any;
  readonly formatCount: number;
  enumerateFormats(callback?: (...args: any[]) => any): any;
  readonly formats: any;
}

export class ExportFormat extends HandleObject {
  constructor(handle?: any);
  appendSize(exportSize?: any): any;
  deleteSize(index?: any): any;
  replaceSize(index?: any, exportSize?: any): any;
  readonly sizeCount: number;
  enumerateSizes(callback?: (...args: any[]) => any): any;
  readonly sizes: any;
  static createWithFileExportOptions(fileExportOptions?: any): ExportFormat;
}

export class ExportScale extends HandleObject {
  constructor(handle?: any);
  readonly sizeType: ExportScaleSizeType;
  readonly hasMultiplier: boolean;
  readonly multiplier: any;
  readonly size: ExportScaleSizeType;
  readonly width: number;
  readonly height: number;
  static createWithPreset(exportScalePreset?: any): ExportScale;
  static createWithMultiplier(multiplier?: any): ExportScale;
  static createWithWidth(width?: any): ExportScale;
  static createWithHeight(height?: any): ExportScale;
  static createWithSquare(size?: any): ExportScale;
  static createWithMultiplierSquare(multiplier?: any, size?: any): ExportScale;
  static createWithWidthHeight(width?: any, height?: any): ExportScale;
}

export class ExportSize extends HandleObject {
  constructor(handle?: any);
  readonly exportScale: ExportScale;
  setExportScale(exportScale?: ExportScale): any;
  static createWithExportScale(exportScale?: any): ExportSize;
}

export { ExportScalePreset } from 'affinity:dom';
export { ExportScaleSizeType } from 'affinity:dom';
