// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class ExportableInterface extends HandleObject {
  constructor(handle?: any);
  readonly exportConfig: any;
  readonly node: any;
}

