// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class BitmapFill extends Fill {
  constructor(handle?: any);
  static create(bitmap?: any, extendType?: any, resamplerType?: any, ignoreAlpha?: any): BitmapFill;
  static fromFill(fill?: any): BitmapFill;
  clone(): BitmapFill;
  readonly bitmap: any;
  extendType: any;
  readonly isIgnoreAlpha: any;
  isKOnly: any;
  profile: any;
  upsamplerType: any;
}

export class Fill extends HandleObject {
  constructor(handle?: any);
  clone(): Fill;
  alpha: any;
  readonly fillType: any;
  readonly hasNonFullAlpha: any;
  readonly hasFlatAlpha: any;
  readonly hasNoise: any;
  intensity: any;
  readonly isVisible: any;
  readonly isSpatiallyInvariant: any;
  readonly meanAlpha: any;
  noise: any;
  tint: any;
}

export class FillDescriptor extends HandleObject {
  constructor(handle?: any);
  clone(): FillDescriptor;
  cloneWithNewFill(fill?: any): FillDescriptor;
  cloneWithNewIsScaleWithObject(isScaleWithObject?: any): FillDescriptor;
  cloneWithNewTransform(transform?: any): FillDescriptor;
  cloneWithNewTransformInfo(transform?: any, isAnchoredToSpread?: any): FillDescriptor;
  cloneWithNewBlendMode(blendMode?: any): FillDescriptor;
  cloneWithNewIsAnchoredToSpread(isAnchoredToSpread?: any): FillDescriptor;
  readonly fill: any;
  readonly fillType: any;
  readonly blendMode: any;
  readonly transform: any;
  readonly isScaleWithObject: any;
  readonly isAnchoredToSpread: any;
  getTransformInfo(): any;
  static createNone(): FillDescriptor;
  static createSolid(solidFill?: any, blendMode?: any): FillDescriptor;
  static create(fill?: any, scaleWithObject?: any, transform?: any, blendMode?: any, anchoredToSpread?: any): FillDescriptor;
}

export class GradientFill extends Fill {
  constructor(handle?: any);
  static create(gradient?: any, gradientType?: any): GradientFill;
  static createDefault(): GradientFill;
  static fromFill(fill?: any): GradientFill;
  clone(): GradientFill;
  cloneWithNewGradient(gradient?: any): GradientFill;
  cloneWithNewGradientFillType(gradientFillType?: any): GradientFill;
  readonly gradient: any;
  readonly gradientFillType: any;
}

export class HatchFill extends Fill {
  constructor(handle?: any);
  static create(pattern?: any, units?: any, penColour?: any, brushColour?: any, lineWeight?: any): HatchFill;
  clone(): HatchFill;
  pattern: any;
  units: any;
  penColour: any;
  brushColour: any;
  lineWeight: any;
}

export class NoFill extends Fill {
  constructor(handle?: any);
  static create(): NoFill;
  static fromFill(fill?: any): NoFill;
  clone(): NoFill;
}

export class SolidFill extends Fill {
  constructor(handle?: any);
  static create(colour?: any): SolidFill;
  static createDefault(): SolidFill;
  static fromFill(fill?: any): SolidFill;
  clone(): SolidFill;
  colour: any;
}

export { BlendMode } from 'affinity:common';
export function createTypedFill(fillHandle?: any): any;
export { FillMask } from 'affinity:fills';
export { FillType } from 'affinity:fills';
export { GradientFillType } from 'affinity:fills';
export { RasterExtendType } from 'affinity:raster';
export { RasterResamplerType } from 'affinity:raster';
export { UnitType } from 'affinity:common';
