// Auto-generated by tools/generate_types.py. Do not edit.

import { Colour } from '/colours';
import { Gradient } from '/colours';
import { HandleObject } from '/handleobject';
import { HatchPattern } from '/hatch';
import { RasterObject } from '/rasterobject';
import { BlendMode } from 'affinity:common';
import { FillType } from 'affinity:fills';
import { GradientFillType } from 'affinity:fills';
import { UnitType } from 'affinity:common';

export class BitmapFill extends Fill {
  constructor(handle?: any);
  static create(bitmap?: any, extendType?: any, resamplerType?: any, ignoreAlpha?: any): BitmapFill;
  static fromFill(fill?: any): BitmapFill;
  clone(): BitmapFill;
  readonly bitmap: RasterObject;
  extendType: any;
  readonly isIgnoreAlpha: boolean;
  isKOnly: boolean;
  profile: any;
  upsamplerType: any;
}

export class Fill extends HandleObject {
  constructor(handle?: any);
  clone(): Fill;
  alpha: any;
  readonly fillType: FillType;
  readonly hasNonFullAlpha: boolean;
  readonly hasFlatAlpha: boolean;
  readonly hasNoise: boolean;
  intensity: any;
  readonly isVisible: boolean;
  readonly isSpatiallyInvariant: boolean;
  readonly meanAlpha: any;
  noise: any;
  tint: any;
}

export class FillDescriptor extends HandleObject {
  constructor(handle?: any);
  clone(): FillDescriptor;
  cloneWithNewFill(fill?: any): FillDescriptor;
  cloneWithNewIsScaleWithObject(isScaleWithObject?: boolean): FillDescriptor;
  cloneWithNewTransform(transform?: any): FillDescriptor;
  cloneWithNewTransformInfo(transform?: any, isAnchoredToSpread?: boolean): FillDescriptor;
  cloneWithNewBlendMode(blendMode?: any): FillDescriptor;
  cloneWithNewIsAnchoredToSpread(isAnchoredToSpread?: boolean): FillDescriptor;
  readonly fill: Fill;
  readonly fillType: FillType;
  readonly blendMode: BlendMode;
  readonly transform: any;
  readonly isScaleWithObject: boolean;
  readonly isAnchoredToSpread: boolean;
  getTransformInfo(): any;
  static createNone(): FillDescriptor;
  static createSolid(solidFill?: any, blendMode?: any): FillDescriptor;
  static create(fill?: any, scaleWithObject?: any, transform?: any, blendMode?: any, anchoredToSpread?: any): FillDescriptor;
}

export class GradientFill extends Fill {
  constructor(handle?: any);
  static create(gradient?: any, gradientType?: any): GradientFill;
  static createDefault(): GradientFill;
  static fromFill(fill?: any): GradientFill;
  clone(): GradientFill;
  cloneWithNewGradient(gradient?: any): GradientFill;
  cloneWithNewGradientFillType(gradientFillType?: any): GradientFill;
  readonly gradient: Gradient;
  readonly gradientFillType: GradientFillType;
}

export class HatchFill extends Fill {
  constructor(handle?: any);
  static create(pattern?: any, units?: any, penColour?: any, brushColour?: any, lineWeight?: number): HatchFill;
  clone(): HatchFill;
  pattern: HatchPattern;
  units: UnitType;
  penColour: any;
  brushColour: any;
  lineWeight: any;
}

export class NoFill extends Fill {
  constructor(handle?: any);
  static create(): NoFill;
  static fromFill(fill?: any): NoFill;
  clone(): NoFill;
}

export class SolidFill extends Fill {
  constructor(handle?: any);
  static create(colour?: any): SolidFill;
  static createDefault(): SolidFill;
  static fromFill(fill?: any): SolidFill;
  clone(): SolidFill;
  colour: Colour;
}

export { BlendMode } from 'affinity:common';
export function createTypedFill(fillHandle?: any): any;
export { FillMask } from 'affinity:fills';
export { FillType } from 'affinity:fills';
export { GradientFillType } from 'affinity:fills';
export { RasterExtendType } from 'affinity:raster';
export { RasterResamplerType } from 'affinity:raster';
export { UnitType } from 'affinity:common';
