// Auto-generated by tools/generate_types.py. Do not edit.

import { Colour } from '/colours';
import { Gradient } from '/colours';
import { HandleObject } from '/handleobject';
import { HatchPattern } from '/hatch';
import { Mesh } from '/geometry';
import { RasterObject } from '/rasterobject';
import { BlendMode } from 'affinity:common';
import { FillType } from 'affinity:fills';
import { GradientFillType } from 'affinity:fills';
import { UnitType } from 'affinity:common';

export class BitmapFill extends Fill {
  constructor(handle?: any);
  static create(bitmap?: any, extendType?: any, resamplerType?: any, ignoreAlpha?: any): BitmapFill;
  static fromFill(fill?: any): BitmapFill;
  clone(): BitmapFill;
  readonly bitmap: RasterObject;
  extendType: any;
  readonly isIgnoreAlpha: boolean;
  isKOnly: boolean;
  profile: any;
  upsamplerType: any;
}

export class ColourMesh extends Mesh {
  constructor(handle?: any);
  static createDefaultNone(): ColourMesh;
  static createDefaultWhite(): ColourMesh;
  static createFromColour(colour?: any, size?: any): ColourMesh;
  static createFromGradient(gradient?: any, isRadial?: boolean): ColourMesh;
  clone(): ColourMesh;
  getNodeColour(xIndex?: number, yIndex?: number): any;
  setNodeColour(xIndex?: number, yIndex?: number, colour?: any): this;
}

export class DiffusionCurveSet extends HandleObject {
  constructor(handle?: any);
  static create(): DiffusionCurveSet;
  static createDefault(colourA?: any, colourB?: any): DiffusionCurveSet;
  clone(): DiffusionCurveSet;
  readonly curveCount: number;
  addCurve(points?: any, leftColour?: any, rightColour?: any): any;
  removeCurve(index?: any): any;
  getCurvePointCount(index?: any): number;
  getCurvePoint(index?: any, pointIndex?: number): any;
  getCurvePoints(index?: any): any;
  setCurvePoints(index?: any, points?: any): this;
  getCurveColour(index?: any, side?: any): any;
  setCurveColour(index?: any, side?: any, colour?: any): this;
  getCurveBlur(index?: any): any;
  setCurveBlur(index?: any, blur?: any): this;
  getCurveStrength(index?: any): any;
  setCurveStrength(index?: any, strength?: any): this;
  getCurvePressure(index?: any): any;
  setCurvePressure(index?: any, curve?: any): this;
  backgroundColour: any;
  backgroundStrength: any;
  getCurveKind(index?: any): any;
  getCurveParametric(index?: any): any;
  setCurveEllipse(index?: any, centre?: any, radiusX?: any, radiusY?: any, rotation?: number): this;
  setCurveArc(index?: any, centre?: any, radiusX?: any, radiusY?: any, rotation?: any, angle0?: any, angle1?: any): this;
  setCurveLine(index?: any, start?: any, end?: any): this;
  addEllipse(centre?: any, radiusX?: any, radiusY?: any, rotation?: number, leftColour?: any, rightColour?: any): any;
  addArc(centre?: any, radiusX?: any, radiusY?: any, rotation?: any, angle0?: any, angle1?: any, leftColour?: any, rightColour?: any): any;
  addLine(start?: any, end?: any, leftColour?: any, rightColour?: any): any;
  getCurveNodeCount(index?: any): number;
  getCurveNodeSmooth(index?: any, node?: any): any;
  setCurveNodeSmooth(index?: any, node?: any, smooth?: any): this;
}

export class DiffusionFill extends Fill {
  constructor(handle?: any);
  static create(curveSet?: any): DiffusionFill;
  static createDefault(): DiffusionFill;
  static fromFill(fill?: any): DiffusionFill;
  clone(): DiffusionFill;
  cloneWithNewCurves(curveSet?: any): DiffusionFill;
  readonly curveSet: DiffusionCurveSet;
}

export class Fill extends HandleObject {
  constructor(handle?: any);
  clone(): Fill;
  alpha: any;
  readonly fillType: FillType;
  readonly hasNonFullAlpha: boolean;
  readonly hasFlatAlpha: boolean;
  readonly hasNoise: boolean;
  intensity: any;
  readonly isVisible: boolean;
  readonly isSpatiallyInvariant: boolean;
  readonly meanAlpha: any;
  noise: any;
  tint: any;
}

export class FillDescriptor extends HandleObject {
  constructor(handle?: any);
  clone(): FillDescriptor;
  cloneWithNewFill(fill?: any): FillDescriptor;
  cloneWithNewIsScaleWithObject(isScaleWithObject?: boolean): FillDescriptor;
  cloneWithNewTransform(transform?: any): FillDescriptor;
  cloneWithNewTransformInfo(transform?: any, isAnchoredToSpread?: boolean): FillDescriptor;
  cloneWithNewBlendMode(blendMode?: any): FillDescriptor;
  cloneWithNewIsAnchoredToSpread(isAnchoredToSpread?: boolean): FillDescriptor;
  readonly fill: Fill;
  readonly fillType: FillType;
  readonly blendMode: BlendMode;
  readonly transform: any;
  readonly isScaleWithObject: boolean;
  readonly isAnchoredToSpread: boolean;
  getTransformInfo(): any;
  static createNone(): FillDescriptor;
  static createSolid(solidFill?: any, blendMode?: any): FillDescriptor;
  static create(fill?: any, scaleWithObject?: any, transform?: any, blendMode?: any, anchoredToSpread?: any): FillDescriptor;
}

export class GradientFill extends Fill {
  constructor(handle?: any);
  static create(gradient?: any, gradientType?: any): GradientFill;
  static createDefault(): GradientFill;
  static fromFill(fill?: any): GradientFill;
  clone(): GradientFill;
  cloneWithNewGradient(gradient?: any): GradientFill;
  cloneWithNewGradientFillType(gradientFillType?: any): GradientFill;
  readonly gradient: Gradient;
  readonly gradientFillType: GradientFillType;
}

export class HatchFill extends Fill {
  constructor(handle?: any);
  static create(pattern?: any, units?: any, penColour?: any, brushColour?: any, lineWeight?: number): HatchFill;
  clone(): HatchFill;
  pattern: HatchPattern;
  units: UnitType;
  penColour: any;
  brushColour: any;
  lineWeight: any;
}

export class MeshFill extends Fill {
  constructor(handle?: any);
  static create(colourMesh?: any): MeshFill;
  static fromFill(fill?: any): MeshFill;
  clone(): MeshFill;
  readonly colourMesh: ColourMesh;
}

export class NoFill extends Fill {
  constructor(handle?: any);
  static create(): NoFill;
  static fromFill(fill?: any): NoFill;
  clone(): NoFill;
}

export class SolidFill extends Fill {
  constructor(handle?: any);
  static create(colour?: any): SolidFill;
  static createDefault(): SolidFill;
  static fromFill(fill?: any): SolidFill;
  clone(): SolidFill;
  colour: Colour;
}

export { BlendMode } from 'affinity:common';
export function createTypedFill(fillHandle?: any): any;
export { DiffusionCurveKind } from 'affinity:fills';
export { DiffusionCurveParametric } from 'affinity:fills';
export { DiffusionCurveSide } from 'affinity:fills';
export { FillMask } from 'affinity:fills';
export { FillType } from 'affinity:fills';
export { GradientFillType } from 'affinity:fills';
export function makeFillDescriptor(fillDescriptor?: any): any;
export { RasterExtendType } from 'affinity:raster';
export { RasterResamplerType } from 'affinity:raster';
export { TransformInfo } from 'affinity:fills';
export { UnitType } from 'affinity:common';
