// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { FontWeight } from 'affinity:fonts';

export class Font extends HandleObject {
  constructor(handle?: any);
  clone(): Font;
  readonly isValid: boolean;
  readonly isNormal: boolean;
  readonly isBold: boolean;
  readonly isVariableBold: boolean;
  readonly isItalic: boolean;
  readonly isVariableItalic: boolean;
  readonly isBoldAvailable: boolean;
  readonly isItalicAvailable: boolean;
  readonly weight: FontWeight;
  readonly normalizedWeight: any;
  readonly width: number;
  readonly normalizedWidth: number;
  readonly isCondensed: boolean;
  readonly isExpanded: boolean;
  readonly panose: Panose;
  readonly postscriptName: string;
  readonly familyName: string;
  readonly ribbiFamily: any;
  readonly wwsFamily: any;
  readonly postscriptPrefix: any;
  readonly traitsName: string;
  readonly variableBold: any;
  readonly variableItalic: any;
  undefined
  readonly isSerif: boolean;
  readonly isSansSerif: boolean;
  readonly isMonospaced: boolean;
  static enumerate(callback?: (...args: any[]) => any): any;
  static readonly all: any;
  static createEmpty(): Font;
  static createDefault(): Font;
  static createDefaultMonospaced(): Font;
  static createDefaultSymbol(): Font;
  static create(family?: any, weight?: any, isItalic?: boolean, width?: any): Font;
  getDistance(other?: any): any;
}

export class FontCollection extends HandleObject {
  constructor(handle?: any);
  readonly displayName: string;
  static enumerateCollections(callback?: (...args: any[]) => any): any;
  static readonly all: any;
}

export class FontFamily extends HandleObject {
  constructor(handle?: any);
  clone(): FontFamily;
  readonly name: string;
  readonly fontCount: number;
  readonly length: any;
  getFont(index?: any): Font;
  enumerateFonts(callback?: (...args: any[]) => any): any;
  readonly fonts: any;
  static enumerate(callback?: (...args: any[]) => any): any;
  static readonly all: any;
  readonly hasVariations: boolean;
  readonly hasFixed: boolean;
}

export class Panose extends HandleObject {
  constructor(handle?: any);
  clone(): Panose;
  is(type?: any): any;
  readonly isSerif: boolean;
  readonly isSansSerif: boolean;
  readonly isMonospaced: boolean;
  readonly isEmpty: boolean;
  undefined
  getDistance(other?: any): any;
}

export { FontWeight } from 'affinity:fonts';
export { FontWidth } from 'affinity:fonts';
export { PanoseType } from 'affinity:fonts';
