// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class Font extends HandleObject {
  constructor(handle?: any);
  clone(): Font;
  readonly isValid: any;
  readonly isNormal: any;
  readonly isBold: any;
  readonly isVariableBold: any;
  readonly isItalic: any;
  readonly isVariableItalic: any;
  readonly isBoldAvailable: any;
  readonly isItalicAvailable: any;
  readonly weight: any;
  readonly normalizedWeight: any;
  readonly width: any;
  readonly normalizedWidth: any;
  readonly isCondensed: any;
  readonly isExpanded: any;
  readonly panose: Panose;
  readonly postscriptName: any;
  readonly familyName: any;
  readonly ribbiFamily: any;
  readonly wwsFamily: any;
  readonly postscriptPrefix: any;
  readonly traitsName: any;
  readonly variableBold: any;
  readonly variableItalic: any;
  toString(): any;
  readonly isSerif: any;
  readonly isSansSerif: any;
  readonly isMonospaced: any;
  static enumerate(callback?: any): any;
  static readonly all: any;
  static createEmpty(): Font;
  static createDefault(): Font;
  static createDefaultMonospaced(): Font;
  static createDefaultSymbol(): Font;
  static create(family?: any, weight?: any, isItalic?: any, width?: any): Font;
  getDistance(other?: any): any;
}

export class FontCollection extends HandleObject {
  constructor(handle?: any);
  readonly displayName: any;
  static enumerateCollections(callback?: any): any;
  static readonly all: any;
}

export class FontFamily extends HandleObject {
  constructor(handle?: any);
  clone(): FontFamily;
  readonly name: any;
  readonly fontCount: any;
  readonly length: any;
  getFont(index?: any): Font;
  enumerateFonts(callback?: any): any;
  readonly fonts: any;
  static enumerate(callback?: any): any;
  static readonly all: any;
  readonly hasVariations: any;
  readonly hasFixed: any;
}

export class Panose extends HandleObject {
  constructor(handle?: any);
  clone(): Panose;
  is(type?: any): any;
  readonly isSerif: any;
  readonly isSansSerif: any;
  readonly isMonospaced: any;
  readonly isEmpty: any;
  toString(): any;
  getDistance(other?: any): any;
}

export { FontWeight } from 'affinity:fonts';
export { FontWidth } from 'affinity:fonts';
export { PanoseType } from 'affinity:fonts';
