// Auto-generated by tools/generate_types.py. Do not edit.

import { Collection } from '/collection';
import { HandleObject } from '/handleobject';

export class Directory {
  constructor(path?: any);
  readonly path: any;
  readonly entries: DirectoryEntries;
}

export class DirectoryEntries extends Collection {
  constructor(path?: any, resolveSymlink?: any);
  readonly all: RecursiveDirectoryEntries;
  readonly files: any;
  readonly filePaths: any;
}

export class DirectoryIterator extends HandleObject {
  constructor(handle?: any);
  static at(path?: any): DirectoryIterator;
  isDone(): any;
  next(): any;
  readonly path: any;
  readonly fileSize: any;
  getFileSize(asBigInt?: any): any;
  readonly fileStatus: FileStatus;
  readonly symlinkStatus: FileStatus;
  entry(resolveSymlink?: any): any;
  readonly done: any;
}

export class File extends HandleObject {
  constructor(path?: any, mode?: any);
  static length(path?: any): File;
  static size(path?: any): any;
  open(path?: any, mode?: any): any;
  seek(offset?: any, origin?: any): any;
  read(buffer?: any, length?: any): any;
  write(buffer?: any, length?: any): any;
  writeStringAsUtf8(str?: any): any;
  writeStringAsUtf16(str?: any): any;
  writeString(str?: any): any;
  tell(): any;
  readonly isEof: any;
  readonly isOpen: any;
  flush(): any;
  getLength(asBigInt?: any): any;
  close(): any;
  seekAsync(offset?: any, origin?: any, callback?: any): any;
  readAsync(buffer?: any, offset?: any, length?: any, position?: any, callback?: any): any;
  writeAsync(buffer?: any, offset?: any, length?: any, position?: any, callback?: any): any;
  writeStringAsUtf8Async(str?: any, position?: any, callback?: any): any;
  writeStringAsUtf16Async(str?: any, position?: any, callback?: any): any;
  writeStringAsync(str?: any, position?: any, callback?: any): any;
  tellAsync(callback?: any): any;
  isEofAsync(callback?: any): any;
  flushAsync(callback?: any): any;
  getLengthAsync(callback?: any, asBigInt?: any): any;
  closeAsync(cancelOps?: any, callback?: any): any;
  position: any;
  readonly length: any;
  readonly size: any;
  static readAll(path?: any): any;
  static readAllAsync(path?: any, callback?: any): File;
  readonly promises: any;
}

export class FilePromises {
  constructor(file?: any);
  readonly file: any;
  seek(offset?: any, origin?: any): any;
  read(buffer?: any, offset?: any, length?: any, position?: any): any;
  write(buffer?: any, offset?: any, length?: any, position?: any): any;
  tell(): any;
  isEof(): any;
  flush(): any;
  getLength(asBigInt?: any): any;
  readonly position: any;
  readonly eof: any;
  readonly length: any;
}

export class FileStatus extends HandleObject {
  constructor(handle?: any);
  readonly permissions: any;
  readonly type: any;
  readonly statusString: any;
  clone(): FileStatus;
}

export class FileSystemPromises {
  constructor(...args: any[]);
  static areEquivalent(path1?: any, path2?: any): any;
  static copy(path1?: any, path2?: any, options?: any): any;
  static copyFile(path1?: any, path2?: any, options?: any): any;
  static createDirectories(path?: any): any;
  static createDirectory(path?: any): any;
  static createDirectorySymlink(target?: any, link?: any): any;
  static createSymlink(target?: any, link?: any): any;
  static exists(path?: any): any;
  static getAbsolute(path?: any): any;
  static getCanonical(path?: any): any;
  static getFileSize(path?: any): any;
  static getFileStatus(path?: any): any;
  static getHardLinkCount(path?: any): any;
  static getSpace(path?: any, useBigInts?: any): any;
  static getSymlinkStatus(path?: any): any;
  static getWeaklyCanonical(path?: any): any;
  static isBlockFile(path?: any): any;
  static isCharacterFile(path?: any): any;
  static isDirectory(path?: any): any;
  static isEmpty(path?: any): any;
  static isFifo(path?: any): any;
  static isOther(path?: any): any;
  static isRegularFile(path?: any): any;
  static isSocket(path?: any): any;
  static isSymlink(path?: any): any;
  static readSymlink(path?: any): any;
  static remove(path?: any): any;
  static removeAll(path?: any): any;
  static rename(oldPath?: any, newPath?: any): any;
  static resizeFile(path?: any, newSize?: any): any;
  static setFilePermissions(path?: any, filePermissions?: any, permOptions?: any): any;
  static open(path?: any, mode?: any): any;
  static readAll(path?: any): any;
}

export class RecursiveDirectoryEntries extends Collection {
  constructor(path?: any, resolveSymlink?: any);
  readonly files: any;
  readonly filePaths: any;
}

export { CopyOptions } from 'affinity:fs';
export { FileOrigin } from 'affinity:fs';
export { FilePermissions } from 'affinity:fs';
export { PathType } from 'affinity:fs';
export { PermOptions } from 'affinity:fs';
export const FileSystemApi: any;
export const fs: any;
export const promises: any;
