// Auto-generated by tools/generate_types.py. Do not edit.

import { Collection } from '/collection';
import { HandleObject } from '/handleobject';
import { SpanCollection } from '/collection';
import { CurveCornerType } from 'affinity:geometry';
import { CurveNodeType } from 'affinity:geometry';
import { Point } from 'affinity:geometry';
import { Vector } from 'affinity:geometry';

export class Transform {
  constructor(...args: any[]);
  data: any;
  setIdentity(): this;
  assign(source?: any): this;
  compose(data?: any): this;
  scale(x?: any, y?: any): this;
  shear(x?: any, y?: any): this;
  rotate(rads?: any): this;
  translate(x?: any, y?: any): this;
  invert(): this;
  decompose(): any;
  applyToPoint(pt?: any): any;
  applyToVector(vec?: any): any;
  premultiplyBy(other?: any): this;
  postmultiplyBy(other?: any): this;
  premultipliedBy(other?: any): Transform;
  postmultipliedBy(other?: any): Transform;
  multiply(other?: any): Transform;
  around(x?: any, y?: any): any;
  about(x?: any, y?: any): any;
  clone(): Transform;
  scaled(x?: any, y?: any): any;
  sheared(x?: any, y?: any): any;
  rotated(rads?: any): any;
  translated(x?: any, y?: any): any;
  undefined
  readonly xAxis: Vector;
  readonly yAxis: Vector;
  readonly origin: Point;
  readonly inverted: any;
  static multiply(a?: any, b?: any): Transform;
  static add(a?: any, b?: any): Transform;
  static subtract(a?: any, b?: any): Transform;
  static createIdentity(): Transform;
  static createTranslate(x?: any, y?: any): Transform;
  static createRotate(rads?: any): Transform;
  static createScale(x?: any, y?: any): Transform;
  static createShear(x?: any, y?: any): Transform;
}

export class CubicBezier {
  constructor(...args: any[]);
  start: any;
  c1: any;
  c2: any;
  end: any;
  assign(source?: any): this;
  makeLine(ptA?: any, ptB?: any): this;
  reverse(): this;
  transform(xf?: any): this;
  evaluate(t?: any): any;
  getCurvature(t?: any): any;
  getNormal(t?: any, normalise?: boolean): any;
  getTangent(t?: any, normalise?: boolean): any;
  getClosestPoint(pt?: any): any;
  split(t?: any): any;
  splitLeft(t?: any): any;
  splitRight(t?: any): any;
  getParamAtLength(length?: any): number;
  clone(): CubicBezier;
  undefined
  reversed(): any;
  transformed(xf?: any): any;
  readonly length: number;
  readonly boundingBox: any;
  readonly controlBox: any;
  static createLine(ptA?: any, ptB?: any): any;
}

export class Curve extends HandleObject {
  constructor(handle?: any);
  static create(): Curve;
  static createLine(p1?: any, p2?: any): Curve;
  static createLineXY(x1?: any, y1?: any, x2?: any, y2?: any): Curve;
  static createRectangle(rc?: any): Curve;
  static createEllipse(rc?: any): Curve;
  static createDiamond(rc?: any): Curve;
  static createLozenge(p1?: any, p2?: any, radius?: any): Curve;
  static createLozengeXY(x1?: any, y1?: any, x2?: any, y2?: any, radius?: any): Curve;
  static createPrecisionUnitCircle(): Curve;
  clone(): Curve;
  transform(xf?: any): this;
  translate(dx?: any, dy?: any): any;
  readonly pointCount: number;
  readonly length: number;
  readonly isClockwise: boolean;
  readonly isEmpty: boolean;
  readonly isClosed: boolean;
  readonly isRectangle: boolean;
  readonly isEllipse: boolean;
  readonly isStraightLine: boolean;
  readonly isPolyline: boolean;
  isRectangleTolerance(tolerance?: any): boolean;
  isEllipseTolerance(tolerance?: any): boolean;
  isStraightLineTolerance(tolerance?: any): boolean;
  isPolylineTolerance(tolerance?: any): boolean;
  getApproxBoundingBox(transform?: any): any;
  getExactBoundingBox(transform?: any): any;
  getBoundingBox(transform?: any): any;
  readonly path: string;
  readonly points: number;
  getPoint(pointIndex?: number): Point;
  setPoint(pointIndex?: number, point?: any): this;
  setPointXY(pointIndex?: number, x?: any, y?: any): this;
  getSubPath(pointIndex?: number, count?: any): string;
  getCorner(pointID?: any): CurveCornerType;
  setCorner(pointID?: any, cornerData?: any, force?: any): this;
  cut(isParametric?: boolean, distance?: any): any;
  getCubicBezier(pointIndex?: number): any;
  readonly firstOnCurvePointIndex: number;
  getNextOnCurvePointIndex(pointIndex?: number, allowWrapIfClosed?: any): number;
  getPreviousOnCurvePointIndex(pointIndex?: number, allowWrapIfClosed?: any): number;
  readonly lastOnCurvePointIndex: number;
  readonly beziers: Collection;
  readonly nodeCount: number;
  getNode(pointIndex?: number): CurveNodeType;
  appendNode(node?: any): any;
  enumerateNodes(callback?: (...args: any[]) => any): any;
  readonly nodes: any;
  makeClosed(): any;
  generatePolygon(tolerance?: any): any;
  readonly exactBoundingBox: any;
  readonly approxBoundingBox: any;
  readonly boundingBox: any;
}

export class CurveBuilder extends HandleObject {
  constructor(handle?: any);
  static create(): CurveBuilder;
  clone(): CurveBuilder;
  begin(point?: any): this;
  beginXY(x?: any, y?: any): this;
  lineTo(point?: any): this;
  lineToXY(x?: any, y?: any): this;
  lineRelative(vector?: any): this;
  lineRelativeXY(dx?: any, dy?: any): this;
  close(): this;
  createCurve(): Curve;
  transform(xf?: any): this;
  translate(dx?: any, dy?: any): any;
  rotate(angle?: any): any;
  scale(x?: any, y?: any): any;
  versineTo(point?: any, versine?: any): this;
  versineToXY(x?: any, y?: any, versine?: any): this;
  versineRelative(vector?: any, versine?: any): this;
  versineRelativeXY(dx?: any, dy?: any, versine?: any): this;
  addArc(startAngle?: any, endAngle?: any, radius?: any, reverse?: any): this;
  addBezier(c0?: any, c1?: any, end?: any): this;
  addBezierXY(c0x?: any, c0y?: any, c1x?: any, c1y?: any, endx?: any, endy?: any): this;
  addEllipse(startAngle?: any, endAngle?: any, majorRadius?: any, minorRadius?: any, rotation?: any, reverse?: any): this;
  setCorner(pointID?: any, cornerData?: any, force?: any): this;
  bulgeTo(point?: any, bulge?: any): this;
  bulgeToXY(x?: any, y?: any, bulge?: any): this;
  bulgeRelative(vector?: any, bulge?: any): this;
  bulgeRelativeXY(dx?: any, dy?: any, bulge?: any): this;
}

export class PolyCurve extends HandleObject {
  constructor(handle?: any);
  static create(): PolyCurve;
  clone(): PolyCurve;
  clear(): any;
  transform(xf?: any): this;
  readonly curveCount: number;
  getApproxBoundingBox(transform?: any): any;
  getExactBoundingBox(transform?: any): any;
  getControlBoundingBox(transform?: any): any;
  getBoundingBox(transform?: any): any;
  at(index?: any): Curve;
  readonly curves: SpanCollection;
  addCurve(curve?: any): any;
  removeEmptyCurves(): any;
  readonly approxBoundingBox: any;
  readonly exactBoundingBox: any;
  readonly controlBoundingBox: any;
  readonly boundingBox: any;
}

export class PolyCurveCurves extends HandleObject {
  constructor(polyCurveHandle?: any);
  at(index?: any): Curve;
  readonly length: number;
}

export class PolyPolyCurve extends HandleObject {
  constructor(handle?: any);
  clone(): PolyPolyCurve;
  containsPoint(point?: any, allowUnclosed?: any, windingOrder?: any, performBoundsCheck?: any): any;
  intersectsRectangle(transform?: any, rectangle?: any, closeCurves?: any): any;
  isNearPoint(point?: any, xTolerance?: any, yTolerance?: any, expansionTolerance?: any): boolean;
  isNearRectangle(rectangle?: any, tolerance?: any): boolean;
  readonly hasJoins: boolean;
  readonly hasCorners: boolean;
  readonly hasCurves: boolean;
  readonly polyCurveCount: number;
  getPolyCurve(index?: any): PolyCurve;
  getPolyCurveTransform(index?: any): any;
  getTransformedPolyCurve(index?: any): PolyCurve;
  getApproxBoundingBox(transform?: any): any;
  getExactBoundingBox(transform?: any): any;
  getBoundingBox(transform?: any): any;
  addRectangle(rectangle?: any, transform?: any): any;
  addPolyCurve(polyCurve?: any, transform?: any): any;
  addPolyPolyCurve(polyPolyCurve?: any, transform?: any): any;
  transform(xf?: any): this;
  readonly polyCurves: SpanCollection;
  readonly approxBoundingBox: any;
  readonly exactBoundingBox: any;
  readonly boundingBox: any;
}

export class PolyPolyCurvePolyCurves extends HandleObject {
  constructor(polyPolyCurveHandle?: any);
  at(index?: any): PolyCurve;
  readonly length: number;
}

export class Polygon extends HandleObject {
  constructor(handle?: any);
  static create(): Polygon;
  static createLine(p1?: any, p2?: any): Polygon;
  static createLineXY(x1?: any, y1?: any, x2?: any, y2?: any): Polygon;
  static createTriangle(p1?: any, p2?: any, p3?: any): Polygon;
  static createTriangleXY(x1?: any, y1?: any, x2?: any, y2?: any, x3?: any, y3?: any): Polygon;
  static createRectangle(rect?: any): Polygon;
  readonly isEmpty: boolean;
  readonly isClosed: boolean;
  readonly isRectangle: boolean;
  readonly isClockwise: boolean;
  getBoundingBox(transform?: any): any;
  readonly boundingBox: any;
  readonly pointCount: number;
  getPoint(pointIndex?: number): any;
  enumeratePoints(callback?: (...args: any[]) => any): any;
  clear(): any;
  addPoint(point?: any): any;
  addPointXY(x?: any, y?: any): any;
  insertPoint(pointIndex?: number, point?: any): any;
  insertPointXY(pointIndex?: number, x?: any, y?: any): any;
  close(): any;
  reverse(): any;
  clone(): Polygon;
}

export class Spline extends HandleObject {
  constructor(handle?: any);
  static create(): Spline;
  static createFromProfile(profile?: any): Spline;
  static createFromPoints(points?: any): Spline;
  clone(): Spline;
  readonly pointCount: number;
  isLinear: boolean;
  getPoint(pointIndex?: number): any;
  insertPoint(point?: any): any;
  insertPointXY(x?: any, y?: any): any;
  replaceOrInsertPoint(point?: any): any;
  replaceOrInsertPointXY(x?: any, y?: any): any;
  findPoint(point?: any): any;
  findPointXY(x?: any, y?: any): any;
  removePoint(pointIndex?: number): any;
  clear(): any;
  points(): any;
}

export class TransformBuilder {
  constructor();
  translate(xy?: any): any;
  translateXY(x?: any, y?: any): this;
  scale(xy?: any): any;
  scaleXY(x?: any, y?: any): this;
  rotate(rads?: any): this;
  shear(xy?: any): any;
  shearXY(x?: any, y?: any): this;
  readonly transform: any;
}

export function intersectRanges(a1?: any, a2?: any, b1?: any, b2?: any): any;
export function intersectRects(rc1?: any, rc2?: any): any;
export function pointInRect(rc?: any, pt?: any): any;
export function rangesIntersect(a1?: any, a2?: any, b1?: any, b2?: any): any;
export function rectsIntersect(rc1?: any, rc2?: any): any;
export function unionRanges(a1?: any, a2?: any, b1?: any, b2?: any): any;
export function unionRects(rc1?: any, rc2?: any): any;
export function valueInRange(r1?: any, r2?: any, value?: any): any;
export { CurveCornerData } from 'affinity:geometry';
export { CurveCornerType } from 'affinity:geometry';
export { CurveNode } from 'affinity:geometry';
export { CurveNodeStyle } from 'affinity:geometry';
export { CurveNodeType } from 'affinity:geometry';
export { Point } from 'affinity:geometry';
export { Rectangle } from 'affinity:geometry';
export { Size } from 'affinity:geometry';
export { SizeInt } from 'affinity:geometry';
export { SplineProfile } from 'affinity:geometry';
export { TransformData } from 'affinity:geometry';
export { Vector } from 'affinity:geometry';
export { WindingOrder } from 'affinity:geometry';
