// Auto-generated by tools/generate_types.py. Do not edit.
declare function alert(message?: any): void;
declare function confirm(message?: any): boolean;
declare function prompt(message?: any, defaultValue?: any): string | null;
declare function alertAsync(message?: any): Promise<void>;
declare function confirmAsync(message?: any): Promise<boolean>;
declare function promptAsync(message?: any, defaultValue?: any): Promise<string | null>;
declare function quit(): void;

interface AffinityEnumValue {
  readonly value: number;
  equals(other: AffinityEnumValue): boolean;
  toString(): string;
}

declare var environment: {
  readonly logLevel: any;
  readonly SDKVersion: string;
  readonly V8Version: string;
  quit(): void;
  getHeapStatistics(): any;
  postTask(callback: () => void): void;
};
declare var console: any;

interface TextDecoder {
  decode(input?: any, options?: any): string;
}
declare var TextDecoder: {
  prototype: TextDecoder;
  new (encoding?: string): TextDecoder;
};
declare module '*.json' {
  const value: any;
  export = value;
}
