// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class AnchorGlyph extends Glyph {
  constructor(handle?: any);
  readonly isAnchorGlyph: any;
  clone(): AnchorGlyph;
  static fromGlyph(glyph?: any): AnchorGlyph;
}

export class CapturedDateTimeGlyph extends FormattableFieldGlyph {
  constructor(handle?: any);
  readonly isCapturedDateTimeGlyph: any;
  readonly dateTime: any;
  clone(): CapturedDateTimeGlyph;
}

export class CharGlyph extends Glyph {
  constructor(handle?: any);
  readonly isCharGlyph: any;
  static create(char32?: any): CharGlyph;
  clone(): CharGlyph;
  readonly char32: any;
  readonly baseChar32: any;
  readonly string: any;
}

export class CrossReferenceGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isCrossReferenceGlyph: any;
  readonly targetType: any;
  readonly isTargetDifferentChapter: any;
  readonly usesStyles: any;
  clone(): CrossReferenceGlyph;
  static create(): CrossReferenceGlyph;
  static fromGlyph(glyph?: any): CrossReferenceGlyph;
}

export class CrossReferenceSubGlyph extends Glyph {
  constructor(handle?: any);
  readonly isCrossReferenceSubGlyph: any;
  clone(): CrossReferenceSubGlyph;
  static create(crossReferenceSubGlyphType?: any): CrossReferenceSubGlyph;
  static fromGlyph(glyph?: any): CrossReferenceSubGlyph;
}

export class CustomFieldGlyph extends FormattableFieldGlyph {
  constructor(handle?: any);
  readonly isCustomFieldGlyph: any;
  static fromGlyph(glyph?: any): CustomFieldGlyph;
  clone(): CustomFieldGlyph;
}

export class DataMergeFieldGlyph extends DataMergeGlyph {
  constructor(handle?: any);
  readonly isDataMergeFieldGlyph: any;
  readonly dataMergeFieldId: any;
  clone(): DataMergeFieldGlyph;
}

export class DataMergeGlyph extends FormattableFieldGlyph {
  constructor(handle?: any);
  readonly isDataMergeGlyph: any;
  clone(): DataMergeGlyph;
}

export class DataMergeSourceGlyph extends DataMergeGlyph {
  constructor(handle?: any);
  readonly isDataMergeSourceGlyph: any;
  readonly dataMergeSourceType: any;
  clone(): DataMergeSourceGlyph;
}

export class DocumentFieldGlyph extends FormattableFieldGlyph {
  constructor(handle?: any);
  readonly isDocumentFieldGlyph: any;
  readonly documentFieldType: any;
  clone(): DocumentFieldGlyph;
}

export class FieldGlyph extends Glyph {
  constructor(handle?: any);
  readonly isFieldGlyph: any;
  clone(): FieldGlyph;
  readonly fieldName: any;
}

export class FillerTextGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isFillerTextGlyph: any;
  readonly fillerTextType: any;
  readonly sourceBegin: any;
  clone(): FillerTextGlyph;
  static fromGlyph(glyph?: any): FillerTextGlyph;
  static create(fillerTextType?: any, sourceBegin?: any): FillerTextGlyph;
}

export class FormattableFieldGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isFormattableFieldGlyph: any;
  readonly fieldDataType: any;
  clone(): FormattableFieldGlyph;
}

export class Glyph extends HandleObject {
  constructor(handle?: any);
  static GlyphType: any;
  static HardBreakType: any;
  static SoftBreakType: any;
  static WordPartType: any;
  readonly isGlyph: any;
  clone(): Glyph;
  readonly isConsolidated: any;
  readonly isMarking: any;
  readonly isZeroWidth: any;
  readonly isJustificationSpace: any;
  readonly isParagraphBreak: any;
  readonly isSoftBreak: any;
  readonly canSoftBreakBefore: any;
  readonly canSoftBreakAfter: any;
  readonly isAlphaNumeric: any;
  readonly isAlpha: any;
  readonly isNumeric: any;
  readonly isUppercase: any;
  readonly isLowercase: any;
  readonly isStoryTerminator: any;
  readonly isDeletable: any;
  readonly isTableCellBreak: any;
  readonly isMidWordPunctuation: any;
  readonly isTab: any;
  readonly isCombining: any;
  readonly isMarkup: any;
  readonly isHiddenFromOpenType: any;
  readonly wantsFastFind: any;
  getDescription(format?: any): any;
  readonly description: any;
  readonly glyphType: any;
  readonly softBreakType: any;
  readonly hardBreakType: any;
  readonly wordPartType: any;
}

export class GlyphIndexGlyph extends Glyph {
  constructor(handle?: any);
  readonly isGlyphIndexGlyph: any;
  clone(): GlyphIndexGlyph;
  readonly index: any;
}

export class HardBreakGlyph extends Glyph {
  constructor(handle?: any);
  readonly isHardBreakGlyph: any;
  clone(): HardBreakGlyph;
}

export class IndentToHereGlyph extends Glyph {
  constructor(handle?: any);
  readonly isIndentToHereGlyph: any;
  clone(): IndentToHereGlyph;
}

export class IndexMarkGlyph extends Glyph {
  constructor(handle?: any);
  readonly isIndexMarkGlyph: any;
  readonly glyphStyle: any;
  clone(): IndexMarkGlyph;
  static fromGlyph(glyph?: any): IndexMarkGlyph;
}

export class ListNumberGlyph extends Glyph {
  constructor(handle?: any);
  readonly isListNumberGlyph: any;
  readonly level: any;
  clone(): ListNumberGlyph;
  static fromGlyph(glyph?: any): ListNumberGlyph;
}

export class NoteNumberGlyph extends Glyph {
  constructor(handle?: any);
  readonly isNoteNumberGlyph: any;
  clone(): NoteNumberGlyph;
  static fromGlyph(glyph?: any): NoteNumberGlyph;
}

export class PageNumberGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isPageNumberGlyph: any;
  readonly pageNumberType: any;
  clone(): PageNumberGlyph;
}

export class PinGlyph extends Glyph {
  constructor(handle?: any);
  readonly isPinGlyph: any;
  clone(): PinGlyph;
  readonly isInline: any;
  readonly isNote: any;
  readonly notePosition: any;
  readonly noteType: any;
}

export class RangenoteBodyGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isRangenoteBodyGlyph: any;
  readonly isLive: any;
  clone(): RangenoteBodyGlyph;
}

export class RangenoteEndGlyph extends Glyph {
  constructor(handle?: any);
  readonly isRangenoteEndGlyph: any;
  readonly isLive: any;
  clone(): RangenoteEndGlyph;
  static fromGlyph(glyph?: any): RangenoteEndGlyph;
}

export class RangenoteReferenceGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isRangenoteReferenceGlyph: any;
  readonly noteType: any;
  readonly notePosition: any;
  clone(): RangenoteReferenceGlyph;
}

export class RightIndentTabGlyph extends Glyph {
  constructor(handle?: any);
  readonly isRightIndentTabGlyph: any;
  clone(): RightIndentTabGlyph;
  static fromGlyph(glyph?: any): RightIndentTabGlyph;
}

export class RunningHeaderGlyph extends FormattableFieldGlyph {
  constructor(handle?: any);
  readonly isRunningHeaderGlyph: any;
  clone(): RunningHeaderGlyph;
}

export class SectionNameGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isSectionNameGlyph: any;
  clone(): SectionNameGlyph;
}

export function createTypedGlyph(glyphHandle?: any): any;
export { CrossReferenceSubGlyphType } from 'affinity:story';
export { CrossReferenceTargetType } from 'affinity:story';
export { FieldDataType } from 'affinity:story';
export { FillerTextType } from 'affinity:story';
export { GlyphType } from 'affinity:story';
export { HardBreakType } from 'affinity:story';
export { NotePosition } from 'affinity:story';
export { NoteType } from 'affinity:story';
export { DataMergeSourceType } from 'affinity:story';
export { DocumentFieldType } from 'affinity:story';
export { PageNumberType } from 'affinity:story';
export { SoftBreakType } from 'affinity:story';
export { StoryIoFormat } from 'affinity:story';
export { WordPartType } from 'affinity:story';
