// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class GlyphAtts extends HandleObject {
  constructor(handle?: any);
  static create(): GlyphAtts;
  clone(): GlyphAtts;
  underlineType: any;
  strikeoutType: any;
  superSubType: any;
  capsType: any;
  leadingOverrideType: any;
  opticalAlignmentType: any;
  tocRoleType: any;
  isNoBreak: any;
  openTypeScriptTag: any;
  openTypeLanguageTag: any;
  height: any;
  characterSpacing: any;
  baselineAdvance: any;
  autoKernMinHeight: any;
  offsetX: any;
  offsetY: any;
  manualKerning: any;
  scaleX: any;
  scaleY: any;
  shearX: any;
  absoluteLeading: any;
  getDoubleValue(att?: any): any;
  setDoubleValue(att?: any, value?: any): any;
  spellingLanguageId: any;
  styleName: any;
  hyphenationLanguageId: any;
  getStringValue(att?: any): any;
  setStringValue(att?: any, value?: any): any;
  brushFill: any;
  penFill: any;
  transparency: any;
  highlightFill: any;
  underlineFill: any;
  strikeoutFill: any;
  lineStyleDescriptor: any;
  font: any;
}

export { TypographicLineType } from 'affinity:story';
export { SuperSubType } from 'affinity:story';
export { CapsType } from 'affinity:story';
export { LeadingOverrideType } from 'affinity:story';
export { OpticalAlignmentType } from 'affinity:story';
export { TocRoleType } from 'affinity:story';
export { GlyphAttDoubleType } from 'affinity:story';
export { GlyphAttStringType } from 'affinity:story';
