// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { DataMergeSourceType } from 'affinity:story';
import { DocumentFieldType } from 'affinity:story';
import { FieldDataType } from 'affinity:story';
import { FillerTextType } from 'affinity:story';
import { GlyphType } from 'affinity:story';
import { HardBreakType } from 'affinity:story';
import { NotePosition } from 'affinity:story';
import { NoteType } from 'affinity:story';
import { PageNumberType } from 'affinity:story';
import { SoftBreakType } from 'affinity:story';
import { StoryIoFormat } from 'affinity:story';
import { WordPartType } from 'affinity:story';

export class AnchorGlyph extends Glyph {
  constructor(handle?: any);
  readonly isAnchorGlyph: boolean;
  clone(): AnchorGlyph;
  static fromGlyph(glyph?: any): AnchorGlyph;
}

export class CapturedDateTimeGlyph extends FormattableFieldGlyph {
  constructor(handle?: any);
  readonly isCapturedDateTimeGlyph: boolean;
  readonly dateTime: Date;
  clone(): CapturedDateTimeGlyph;
}

export class CharGlyph extends Glyph {
  constructor(handle?: any);
  readonly isCharGlyph: boolean;
  static create(char32?: any): CharGlyph;
  clone(): CharGlyph;
  readonly char32: any;
  readonly baseChar32: any;
  readonly string: any;
}

export class CrossReferenceGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isCrossReferenceGlyph: boolean;
  readonly targetType: any;
  readonly isTargetDifferentChapter: boolean;
  readonly usesStyles: any;
  clone(): CrossReferenceGlyph;
  static create(): CrossReferenceGlyph;
  static fromGlyph(glyph?: any): CrossReferenceGlyph;
}

export class CrossReferenceSubGlyph extends Glyph {
  constructor(handle?: any);
  readonly isCrossReferenceSubGlyph: boolean;
  clone(): CrossReferenceSubGlyph;
  static create(crossReferenceSubGlyphType?: any): CrossReferenceSubGlyph;
  static fromGlyph(glyph?: any): CrossReferenceSubGlyph;
}

export class CustomFieldGlyph extends FormattableFieldGlyph {
  constructor(handle?: any);
  readonly isCustomFieldGlyph: boolean;
  static fromGlyph(glyph?: any): CustomFieldGlyph;
  clone(): CustomFieldGlyph;
}

export class DataMergeFieldGlyph extends DataMergeGlyph {
  constructor(handle?: any);
  readonly isDataMergeFieldGlyph: boolean;
  readonly dataMergeFieldId: number;
  clone(): DataMergeFieldGlyph;
}

export class DataMergeGlyph extends FormattableFieldGlyph {
  constructor(handle?: any);
  readonly isDataMergeGlyph: boolean;
  clone(): DataMergeGlyph;
}

export class DataMergeSourceGlyph extends DataMergeGlyph {
  constructor(handle?: any);
  readonly isDataMergeSourceGlyph: boolean;
  readonly dataMergeSourceType: DataMergeSourceType;
  clone(): DataMergeSourceGlyph;
}

export class DocumentFieldGlyph extends FormattableFieldGlyph {
  constructor(handle?: any);
  readonly isDocumentFieldGlyph: boolean;
  readonly documentFieldType: DocumentFieldType;
  clone(): DocumentFieldGlyph;
}

export class FieldGlyph extends Glyph {
  constructor(handle?: any);
  readonly isFieldGlyph: boolean;
  clone(): FieldGlyph;
  readonly fieldName: string;
}

export class FillerTextGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isFillerTextGlyph: boolean;
  readonly fillerTextType: FillerTextType;
  readonly sourceBegin: any;
  clone(): FillerTextGlyph;
  static fromGlyph(glyph?: any): FillerTextGlyph;
  static create(fillerTextType?: any, sourceBegin?: any): FillerTextGlyph;
}

export class FormattableFieldGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isFormattableFieldGlyph: boolean;
  readonly fieldDataType: FieldDataType;
  clone(): FormattableFieldGlyph;
}

export class Glyph extends HandleObject {
  constructor(handle?: any);
  static GlyphType: any;
  static HardBreakType: any;
  static SoftBreakType: any;
  static WordPartType: any;
  readonly isGlyph: boolean;
  clone(): Glyph;
  readonly isConsolidated: boolean;
  readonly isMarking: boolean;
  readonly isZeroWidth: boolean;
  readonly isJustificationSpace: boolean;
  readonly isParagraphBreak: boolean;
  readonly isSoftBreak: boolean;
  readonly canSoftBreakBefore: boolean;
  readonly canSoftBreakAfter: boolean;
  readonly isAlphaNumeric: boolean;
  readonly isAlpha: boolean;
  readonly isNumeric: boolean;
  readonly isUppercase: boolean;
  readonly isLowercase: boolean;
  readonly isStoryTerminator: boolean;
  readonly isDeletable: boolean;
  readonly isTableCellBreak: boolean;
  readonly isMidWordPunctuation: boolean;
  readonly isTab: boolean;
  readonly isCombining: boolean;
  readonly isMarkup: boolean;
  readonly isHiddenFromOpenType: boolean;
  readonly wantsFastFind: any;
  getDescription(format?: StoryIoFormat): string;
  readonly description: string;
  readonly glyphType: GlyphType;
  readonly softBreakType: SoftBreakType;
  readonly hardBreakType: HardBreakType;
  readonly wordPartType: WordPartType;
}

export class GlyphIndexGlyph extends Glyph {
  constructor(handle?: any);
  readonly isGlyphIndexGlyph: boolean;
  clone(): GlyphIndexGlyph;
  readonly index: number;
}

export class HardBreakGlyph extends Glyph {
  constructor(handle?: any);
  readonly isHardBreakGlyph: boolean;
  clone(): HardBreakGlyph;
}

export class IndentToHereGlyph extends Glyph {
  constructor(handle?: any);
  readonly isIndentToHereGlyph: boolean;
  clone(): IndentToHereGlyph;
}

export class IndexMarkGlyph extends Glyph {
  constructor(handle?: any);
  readonly isIndexMarkGlyph: boolean;
  readonly glyphStyle: any;
  clone(): IndexMarkGlyph;
  static fromGlyph(glyph?: any): IndexMarkGlyph;
}

export class ListNumberGlyph extends Glyph {
  constructor(handle?: any);
  readonly isListNumberGlyph: boolean;
  readonly level: any;
  clone(): ListNumberGlyph;
  static fromGlyph(glyph?: any): ListNumberGlyph;
}

export class NoteNumberGlyph extends Glyph {
  constructor(handle?: any);
  readonly isNoteNumberGlyph: boolean;
  clone(): NoteNumberGlyph;
  static fromGlyph(glyph?: any): NoteNumberGlyph;
}

export class PageNumberGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isPageNumberGlyph: boolean;
  readonly pageNumberType: PageNumberType;
  clone(): PageNumberGlyph;
}

export class PinGlyph extends Glyph {
  constructor(handle?: any);
  readonly isPinGlyph: boolean;
  clone(): PinGlyph;
  readonly isInline: boolean;
  readonly isNote: boolean;
  readonly notePosition: NotePosition;
  readonly noteType: NoteType;
}

export class RangenoteBodyGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isRangenoteBodyGlyph: boolean;
  readonly isLive: boolean;
  clone(): RangenoteBodyGlyph;
}

export class RangenoteEndGlyph extends Glyph {
  constructor(handle?: any);
  readonly isRangenoteEndGlyph: boolean;
  readonly isLive: boolean;
  clone(): RangenoteEndGlyph;
  static fromGlyph(glyph?: any): RangenoteEndGlyph;
}

export class RangenoteReferenceGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isRangenoteReferenceGlyph: boolean;
  readonly noteType: NoteType;
  readonly notePosition: NotePosition;
  clone(): RangenoteReferenceGlyph;
}

export class RightIndentTabGlyph extends Glyph {
  constructor(handle?: any);
  readonly isRightIndentTabGlyph: boolean;
  clone(): RightIndentTabGlyph;
  static fromGlyph(glyph?: any): RightIndentTabGlyph;
}

export class RunningHeaderGlyph extends FormattableFieldGlyph {
  constructor(handle?: any);
  readonly isRunningHeaderGlyph: boolean;
  clone(): RunningHeaderGlyph;
}

export class SectionNameGlyph extends FieldGlyph {
  constructor(handle?: any);
  readonly isSectionNameGlyph: boolean;
  clone(): SectionNameGlyph;
}

export function createTypedGlyph(glyphHandle?: any): any;
export { CrossReferenceSubGlyphType } from 'affinity:story';
export { CrossReferenceTargetType } from 'affinity:story';
export { FieldDataType } from 'affinity:story';
export { FillerTextType } from 'affinity:story';
export { GlyphType } from 'affinity:story';
export { HardBreakType } from 'affinity:story';
export { NotePosition } from 'affinity:story';
export { NoteType } from 'affinity:story';
export { DataMergeSourceType } from 'affinity:story';
export { DocumentFieldType } from 'affinity:story';
export { PageNumberType } from 'affinity:story';
export { SoftBreakType } from 'affinity:story';
export { StoryIoFormat } from 'affinity:story';
export { WordPartType } from 'affinity:story';
