// Auto-generated by tools/generate_types.py. Do not edit.

import { FillDescriptor } from '/fills';
import { Font } from '/fonts';
import { HandleObject } from '/handleobject';
import { LineStyleDescriptor } from '/linestyle';
import { CapsType } from 'affinity:story';
import { LeadingOverrideType } from 'affinity:story';
import { OpticalAlignmentType } from 'affinity:story';
import { SuperSubType } from 'affinity:story';
import { TocRoleType } from 'affinity:story';

export class GlyphAtts extends HandleObject {
  constructor(handle?: any);
  static create(): GlyphAtts;
  clone(): GlyphAtts;
  underlineType: any;
  strikeoutType: any;
  superSubType: SuperSubType;
  capsType: CapsType;
  leadingOverrideType: LeadingOverrideType;
  opticalAlignmentType: OpticalAlignmentType;
  tocRoleType: TocRoleType;
  isNoBreak: boolean;
  openTypeScriptTag: any;
  openTypeLanguageTag: any;
  height: any;
  characterSpacing: any;
  baselineAdvance: any;
  autoKernMinHeight: number;
  offsetX: any;
  offsetY: any;
  manualKerning: any;
  scaleX: any;
  scaleY: any;
  shearX: any;
  absoluteLeading: any;
  getDoubleValue(att?: any): any;
  setDoubleValue(att?: any, value?: any): this;
  spellingLanguageId: number;
  styleName: string;
  hyphenationLanguageId: number;
  getStringValue(att?: any): any;
  setStringValue(att?: any, value?: any): this;
  brushFill: FillDescriptor;
  penFill: FillDescriptor;
  transparency: FillDescriptor;
  highlightFill: FillDescriptor;
  underlineFill: FillDescriptor;
  strikeoutFill: FillDescriptor;
  lineStyleDescriptor: LineStyleDescriptor;
  font: Font;
}

export { TypographicLineType } from 'affinity:story';
export { SuperSubType } from 'affinity:story';
export { CapsType } from 'affinity:story';
export { LeadingOverrideType } from 'affinity:story';
export { OpticalAlignmentType } from 'affinity:story';
export { TocRoleType } from 'affinity:story';
export { GlyphAttDoubleType } from 'affinity:story';
export { GlyphAttStringType } from 'affinity:story';
