// Auto-generated by tools/generate_types.py. Do not edit.

export class HandleObject {
  constructor(handle?: any);
  readonly handle: any;
}

export function liveStruct(fields?: any, get?: any, set?: any): any;
export function livePoint(get?: any, set?: any): any;
export function liveStructArray(count?: any, fields?: any, get?: any, set?: any): any;
export function setStructArray(count?: any, values?: any, set?: any, typeName?: any): any;
