// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class HatchLine extends HandleObject {
  constructor(handle?: any);
  clone(): HatchLine;
  static create(origin?: any, rotation?: any, step?: any, pattern?: any): HatchLine;
  origin: any;
  rotation: any;
  step: any;
  readonly patternDashCount: any;
  getPatternDash(index?: any): any;
  pattern: any;
  enumeratePattern(callback?: (...args: any[]) => any): any;
  readonly isSolid: any;
}

export class HatchPattern extends HandleObject {
  constructor(handle?: any);
  clone(): HatchPattern;
  static createEmpty(): HatchPattern;
  static createDefault(): HatchPattern;
  readonly hatchLineCount: any;
  getHatchLine(index?: any): HatchLine;
  enumerateHatchLines(callback?: (...args: any[]) => any): any;
  appendHatchLine(hatchLine?: any): any;
  appendHatchLineData(origin?: any, rotation?: any, step?: any, pattern?: any): any;
  clearHatchLines(): any;
  eraseHatchLine(index?: any): any;
  insertHatchLine(index?: any, hatchLine?: any): any;
  insertHatchLineData(index?: any, origin?: any, rotation?: any, step?: any, pattern?: any): any;
}

