// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class ImageResourceInterface extends HandleObject {
  constructor(handle?: any);
  readonly imageFilePath: any;
  readonly imageFileSize: any;
  readonly modifiedTime: any;
  readonly fileType: any;
  readonly fileTypeName: any;
  readonly page: any;
  readonly artboard: any;
  readonly isOnArtboard: any;
  readonly originalDPI: any;
  readonly iccProfile: any;
  readonly placedSize: any;
  readonly originalSize: any;
  getColourFormat(allowRemote?: any): any;
  readonly imagePlacement: any;
  readonly masterPage: any;
  getSmallThumbnail(format?: any, colourProfileSet?: any): any;
  getLargeThumbnail(format?: any, colourProfileSet?: any): any;
  readonly resourceNode: any;
  readonly canEditOriginalImage: any;
  createFileTypeName(): any;
  saveOriginalFile(filename?: any): any;
  readonly node: any;
}

export { FileType } from 'affinity:dom';
export { ImagePlacement } from 'affinity:dom';
export { RasterFormat } from 'affinity:raster';
