// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { FileType } from 'affinity:dom';
import { ImagePlacement } from 'affinity:dom';

export class ImageResourceInterface extends HandleObject {
  constructor(handle?: any);
  readonly imageFilePath: string;
  readonly imageFileSize: any;
  readonly modifiedTime: any;
  readonly fileType: FileType;
  readonly fileTypeName: string;
  readonly page: any;
  readonly artboard: any;
  readonly isOnArtboard: boolean;
  readonly originalDPI: any;
  readonly iccProfile: any;
  readonly placedSize: any;
  readonly originalSize: any;
  getColourFormat(allowRemote?: any): any;
  readonly imagePlacement: ImagePlacement;
  readonly masterPage: any;
  getSmallThumbnail(format?: any, colourProfileSet?: any): any;
  getLargeThumbnail(format?: any, colourProfileSet?: any): any;
  readonly resourceNode: any;
  readonly canEditOriginalImage: boolean;
  createFileTypeName(): string;
  saveOriginalFile(filename?: any): any;
  readonly node: any;
}

export { FileType } from 'affinity:dom';
export { ImagePlacement } from 'affinity:dom';
export { RasterFormat } from 'affinity:raster';
