// Auto-generated by tools/generate_types.py. Do not edit.

export class inspect {
  constructor(...args: any[]);
  static custom: any;
  static defaultOptions: any;
}

export const format: any;
export const formatWithOptions: any;
export const patchConsole: any;
export const unpatchConsole: any;
