// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { BevelEmbossType } from 'affinity:layereffects';
import { BlendMode } from 'affinity:common';
import { FillType } from 'affinity:fills';
import { LayerEffectType } from 'affinity:layereffects';

export class BevelEmbossLayerEffect extends LayerEffect {
  constructor(handle?: any);
  readonly isBevelEmbossLayerEffect: boolean;
  clone(): BevelEmbossLayerEffect;
  static create(): BevelEmbossLayerEffect;
  radius: any;
  depth: any;
  soften: any;
  bevelProfile: any;
  setStandardBevelProfile(standardProfile?: any): this;
  bevelEmbossType: BevelEmbossType;
  azimuth: any;
  elevation: any;
  invert: any;
  shadowColour: any;
  highlightColour: any;
  shadowBlendMode: any;
  shadowOpacity: any;
}

export class ColourOverlayLayerEffect extends LayerEffect {
  constructor(handle?: any);
  readonly isColourOverlayLayerEffect: boolean;
  clone(): ColourOverlayLayerEffect;
  static create(): ColourOverlayLayerEffect;
  colour: any;
}

export class GaussianBlurLayerEffect extends LayerEffect {
  constructor(handle?: any);
  readonly isGaussianBlurLayerEffect: boolean;
  clone(): GaussianBlurLayerEffect;
  static create(): GaussianBlurLayerEffect;
  radius: any;
  preserveAlpha: any;
}

export class GradientOverlayLayerEffect extends LayerEffect {
  constructor(handle?: any);
  readonly isGradientOverlayLayerEffect: boolean;
  clone(): GradientOverlayLayerEffect;
  static create(): GradientOverlayLayerEffect;
  fillDescriptor: any;
  static calculateTransform(scaleX?: any, scaleY?: any, transformX?: any, transformY?: any): any;
}

export class InnerGlowLayerEffect extends LayerEffect {
  constructor(handle?: any);
  readonly isInnerGlowLayerEffect: boolean;
  clone(): InnerGlowLayerEffect;
  static create(): InnerGlowLayerEffect;
  radius: any;
  colour: any;
  intensity: any;
  centre: any;
}

export class InnerShadowLayerEffect extends LayerEffect {
  constructor(handle?: any);
  readonly isInnerShadowLayerEffect: boolean;
  clone(): InnerShadowLayerEffect;
  static create(): InnerShadowLayerEffect;
  radius: any;
  colour: any;
  offset: any;
  angle: any;
  intensity: any;
}

export class LayerEffect extends HandleObject {
  constructor(handle?: any);
  readonly isLayerEffect: boolean;
  clone(): LayerEffect;
  readonly type: LayerEffectType;
  enabled: any;
  opacity: any;
  blendMode: BlendMode;
  scaleWithObject: any;
}

export class OuterGlowLayerEffect extends LayerEffect {
  constructor(handle?: any);
  readonly isOuterGlowLayerEffect: boolean;
  clone(): OuterGlowLayerEffect;
  static create(): OuterGlowLayerEffect;
  radius: any;
  colour: any;
  intensity: any;
}

export class OuterShadowLayerEffect extends LayerEffect {
  constructor(handle?: any);
  readonly isOuterShadowLayerEffect: boolean;
  clone(): OuterShadowLayerEffect;
  static create(): OuterShadowLayerEffect;
  radius: any;
  colour: any;
  offset: any;
  angle: any;
  intensity: any;
  fillKnocksOut: any;
}

export class OutlineLayerEffect extends LayerEffect {
  constructor(handle?: any);
  readonly isOutlineLayerEffect: boolean;
  clone(): OutlineLayerEffect;
  static create(): OutlineLayerEffect;
  radius: any;
  colour: any;
  alignment: any;
  fillType: FillType;
  fillDescriptor: any;
  static calculateTransform(scaleX?: any, scaleY?: any, transformX?: any, transformY?: any): any;
}

export class PhongBevelLayerEffect extends LayerEffect {
  constructor(handle?: any);
  readonly isPhongBevelLayerEffect: boolean;
  clone(): PhongBevelLayerEffect;
  static create(): PhongBevelLayerEffect;
  radius: any;
  linkDepth: any;
  depth: any;
  soften: any;
  bevelProfile: any;
  setStandardBevelProfile(standardProfile?: any): this;
  ambient: any;
  diffuse: any;
  specular: any;
  shininess: any;
  ambientColour: any;
  specularColour: any;
  readonly lightCount: number;
  getLight(index?: any): PointLight;
  enumerateLights(callback?: (...args: any[]) => any): any;
  insertLight(index?: any, pointLight?: any): any;
  removeLight(index?: any): any;
  appendLight(pointLight?: any): any;
}

export class PointLight extends HandleObject {
  constructor(handle?: any);
  readonly isPointLight: boolean;
  clone(): PointLight;
  azimuth: any;
  elevation: any;
  colour: any;
}

export { BlendMode } from 'affinity:common';
export { SplineProfile } from 'affinity:geometry';
export function createTypedLayerEffect(handle?: any): any;
export { LayerEffectType } from 'affinity:layereffects';
export { StrokeAlignment } from 'affinity:linestyles';
export { StrokeFillType } from 'affinity:layereffects';
export { BevelEmbossType } from 'affinity:layereffects';
