// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { LayerEffect } from '/layereffects';

export class LayerEffectsInterface extends HandleObject {
  constructor(handle?: any);
  readonly effectCount: number;
  getEffect(index?: any): LayerEffect;
  enumerateEffects(callback?: (...args: any[]) => any): any;
  readonly effects: any;
  readonly hasAnyVisibleEffects: boolean;
  readonly hasActiveEffects: boolean;
  readonly isScaleWithObject: boolean;
  readonly node: any;
}

