// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class LayerEffectsInterface extends HandleObject {
  constructor(handle?: any);
  readonly effectCount: any;
  getEffect(index?: any): any;
  enumerateEffects(callback?: (...args: any[]) => any): any;
  readonly effects: any;
  readonly hasAnyVisibleEffects: any;
  readonly hasActiveEffects: any;
  readonly isScaleWithObject: any;
  readonly node: any;
}

