// Auto-generated by tools/generate_types.py. Do not edit.

import { FillDescriptor } from '/fills';
import { HandleObject } from '/handleobject';
import { LineStyleDescriptor } from '/linestyle';
import { ContentType } from 'affinity:dom';
import { LineCap } from 'affinity:linestyles';
import { LineJoin } from 'affinity:linestyles';
import { LineType } from 'affinity:linestyles';
import { StrokeAlignment } from 'affinity:linestyles';

export class LineStyleInterface extends HandleObject {
  constructor(handle?: any);
  readonly isNoFill: boolean;
  readonly isLineStyleVisible: boolean;
  readonly domainTransform: any;
  readonly scalarDomainTransform: any;
  readonly contentType: ContentType;
  readonly descriptorCount: number;
  getCurrentFillDescriptor(obeyScaleWithObject?: boolean): FillDescriptor;
  getCurrentLineStyleDescriptor(): LineStyleDescriptor;
  getCurrentDescriptors(obeyScaleWithObject?: boolean): any;
  readonly currentIndex: number;
  getFillDescriptor(index?: any, obeyScaleWithObject?: boolean): FillDescriptor;
  getLineStyleDescriptor(index?: any): LineStyleDescriptor;
  getDescriptors(index?: any, obeyScaleWithObject?: boolean): any;
  enumerateFillDescriptors(callback?: (...args: any[]) => any, obeyScaleWithObject?: boolean): any;
  enumerateLineStyleDescriptors(callback?: (...args: any[]) => any): any;
  enumerateDescriptors(callback?: (...args: any[]) => any, obeyScaleWithObject?: any): any;
  readonly node: any;
  penFillDescriptor: any;
  lineStyleDescriptor: any;
  lineStyle: any;
  setCurrentLineStyle(lineStyle?: any, options?: any, preview?: any): this;
  setCurrentFillDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): this;
  setCurrentLineStyleDescriptor(descriptor?: any, options?: any, preview?: any): this;
  lineWeight: any;
  lineWeightPts: any;
  lineType: LineType;
  lineCap: LineCap;
  lineJoin: LineJoin;
  dashPhase: any;
  dashPattern: any;
  hasBalancedDashes: boolean;
  strokeAlignment: StrokeAlignment;
  getAllFillDescriptors(obeyScaleWithObject?: boolean): any;
  getAllLineStyleDescriptors(): any;
  readonly penFillDescriptors: any;
  readonly lineStyleDescriptors: any;
  isAnchoredToSpread: boolean;
  setIsAnchoredToSpread(anchored?: any, applyToAllFills?: any, preview?: any): any;
}

export { ContentType } from 'affinity:dom';
