// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class ArrowHead extends HandleObject {
  constructor(handle?: any);
  static create(style?: any, opts?: any): ArrowHead;
  static createDefault(): ArrowHead;
  clone(): ArrowHead;
  getAnchor(internal?: any): any;
  setAnchor(internal?: any, value?: any): any;
  readonly isFilled: any;
  readonly isOutlined: any;
  isSolidLine: any;
  scaleX: any;
  scaleY: any;
}

export class LineStyle extends HandleObject {
  constructor(handle?: any);
  static create(opts?: any): LineStyle;
  static createDefault(): LineStyle;
  static createDefaultWithWeight(weight?: any): LineStyle;
  clone(): LineStyle;
  cap: any;
  join: any;
  type: any;
  weight: any;
  miterLimit: any;
  dashPhase: any;
  dashPattern: any;
  isResolutionIndependent: any;
  hasBalancedDashes: any;
  vectorBrush: any;
}

export class LineStyleDescriptor extends HandleObject {
  constructor(handle?: any);
  static create(lineStyle?: any, options?: any): LineStyleDescriptor;
  static createDefault(weight?: any): LineStyleDescriptor;
  readonly lineStyle: any;
  readonly frontArrowHead: any;
  readonly backArrowHead: any;
  readonly pressure: any;
  readonly isBehind: any;
  readonly isScale: any;
  readonly strokeAlignment: any;
  effectiveWeight(localTransform?: any, worldTransform?: any): any;
  clone(): LineStyleDescriptor;
  cloneWithNewArrowHeads(frontArrow?: any, backArrow?: any): LineStyleDescriptor;
  cloneWithNewLineStyle(lineStyle?: any): LineStyleDescriptor;
  cloneScaled(scale?: any): LineStyleDescriptor;
}

export { ArrowHeadStyle } from 'affinity:linestyles';
export { LineCap } from 'affinity:linestyles';
export { LineJoin } from 'affinity:linestyles';
export { LineStyleMask } from 'affinity:linestyles';
export { LineType } from 'affinity:linestyles';
export { StrokeAlignment } from 'affinity:linestyles';
