// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class LineStyleInterface extends HandleObject {
  constructor(handle?: any);
  readonly isNoFill: any;
  readonly isLineStyleVisible: any;
  readonly domainTransform: any;
  readonly scalarDomainTransform: any;
  readonly contentType: any;
  readonly descriptorCount: any;
  getCurrentFillDescriptor(obeyScaleWithObject?: any): any;
  getCurrentLineStyleDescriptor(): any;
  getCurrentDescriptors(obeyScaleWithObject?: any): any;
  readonly currentIndex: any;
  getFillDescriptor(index?: any, obeyScaleWithObject?: any): any;
  getLineStyleDescriptor(index?: any): any;
  getDescriptors(index?: any, obeyScaleWithObject?: any): any;
  enumerateFillDescriptors(callback?: any, obeyScaleWithObject?: any): any;
  enumerateLineStyleDescriptors(callback?: any): any;
  enumerateDescriptors(callback?: any, obeyScaleWithObject?: any): any;
  readonly node: any;
  penFillDescriptor: any;
  lineStyleDescriptor: any;
  lineStyle: any;
  setCurrentLineStyle(lineStyle?: any, options?: any, preview?: any): any;
  setCurrentFillDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): any;
  setCurrentLineStyleDescriptor(descriptor?: any, options?: any, preview?: any): any;
  lineWeight: any;
  lineWeightPts: any;
  lineType: any;
  lineCap: any;
  lineJoin: any;
  dashPhase: any;
  dashPattern: any;
  hasBalancedDashes: any;
  strokeAlignment: any;
  getAllFillDescriptors(obeyScaleWithObject?: any): any;
  getAllLineStyleDescriptors(): any;
  readonly penFillDescriptors: any;
  readonly lineStyleDescriptors: any;
  isAnchoredToSpread: any;
  setIsAnchoredToSpread(anchored?: any, applyToAllFills?: any, preview?: any): any;
}

export { ContentType } from 'affinity:dom';
