// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { LogLevel } from 'affinity:common';

export class LogFile extends HandleObject {
  constructor(handle?: any);
  static create(path?: string, logLevel?: any, append?: boolean): LogFile;
  logLevel: LogLevel;
  start(): any;
  flush(): any;
  stop(): any;
}

export { LogLevel } from 'affinity:common';
