// Auto-generated by tools/generate_types.py. Do not edit.

import { FillDescriptor } from '/fills';
import { HandleObject } from '/handleobject';

export class MarginsInterface extends HandleObject {
  constructor(handle?: any);
  readonly margins: any;
  readonly marginFill: FillDescriptor;
  readonly useMargins: any;
  readonly hasMargins: boolean;
}

