// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class MarginsInterface extends HandleObject {
  constructor(handle?: any);
  readonly useMargins: any;
  readonly hasMargins: boolean;
}

