// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { ContentType } from 'affinity:dom';

export class HttpRequest extends HandleObject {
  constructor(handle?: any);
  setTimeoutInSec(timeoutSec: number): this;
  setSuppressUserAgentHeader(suppress: boolean): this;
  setEncodeHeaderValuesAsRfc2047(encodeAs2047: boolean): this;
  setUseExpensiveNetwork(useExpensive: boolean): this;
  setUseConstrainedNetwork(useConstrained: boolean): this;
  setAvoidChunkedTransferEncoding(avoid: boolean): this;
  setHeaderValue(headerKey: string, headerVal: string): void;
  getHeaderValue(headerKey: string): string | null;
  do(): HttpRequestResult;
  doAsync(callback?: (state: AffinityEnumValue, response: HttpResponse, reason: string) => void): void;
  static create(url: string, method: AffinityEnumValue | number): HttpRequest;
}

export class HttpResponse extends HandleObject {
  constructor(handle?: any);
  readonly statusCode: AffinityEnumValue;
  getHeaderValue(headerKey: string): string | null;
  readonly content: unknown;
}

export { HttpRequestResult } from 'affinity:network';
export { RequestMethod } from 'affinity:network';
export { HttpStatusCode } from 'affinity:network';
