// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class HttpRequest extends HandleObject {
  constructor(handle?: any);
  setTimeoutInSec(timeoutSec?: any): any;
  setSuppressUserAgentHeader(suppress?: any): any;
  setEncodeHeaderValuesAsRfc2047(encodeAs2047?: any): any;
  setUseExpensiveNetwork(useExpensive?: any): any;
  setUseConstrainedNetwork(useConstrained?: any): any;
  setAvoidChunkedTransferEncoding(avoid?: any): any;
  setHeaderValue(headerKey?: any, headerVal?: any): any;
  getHeaderValue(headerKey?: any): any;
  do(): any;
  doAsync(callback?: any): any;
  static create(url?: any, method?: any): HttpRequest;
}

export class HttpResponse extends HandleObject {
  constructor(handle?: any);
  readonly statusCode: any;
  getHeaderValue(headerKey?: any): any;
  readonly content: any;
}

export { RequestMethod } from 'affinity:network';
export { HttpStatusCode } from 'affinity:network';
