// Auto-generated by tools/generate_types.py. Do not edit.

import { ArtboardInterface } from '/artboardinterface';
import { BaseBoxInterface } from '/baseboxinterface';
import { BlendModeInterface } from '/blendmodeinterface';
import { BrushFillInterface } from '/brushfillinterface';
import { Collection } from '/collection';
import { Colour } from '/colours';
import { CompoundOperationInterface } from '/compoundoperationinterface';
import { CurvesInterface } from '/curvesinterface';
import { DescriptionInterface } from '/descriptioninterface';
import { EditabilityInterface } from '/editabilityinterface';
import { ExportableInterface } from '/exportableinterface';
import { FillDescriptor } from '/fills';
import { HandleObject } from '/handleobject';
import { ImageResourceInterface } from '/imageresourceinterface';
import { LayerEffectsInterface } from '/layereffectsinterface';
import { LineStyleInterface } from '/linestyleinterface';
import { LoadDocumentOptions } from '/document';
import { PhysicalRootInterface } from '/physicalrootinterface';
import { PhysicalRootPropertiesInterface } from '/physicalrootpropertiesinterface';
import { PictureFrameInterface } from '/pictureframeinterface';
import { PolyCurve } from '/geometry';
import { RasterInterface } from '/rasterinterface';
import { RasterObject } from '/rasterobject';
import { Selectable } from '/selectable';
import { Shape } from '/shapes';
import { ShapeInterface } from '/shapeinterface';
import { Spline } from '/geometry';
import { StoryInterface } from '/storyinterface';
import { TagInterface } from '/taginterface';
import { TextFrameInterface } from '/textframeinterface';
import { TransformInterface } from '/transforminterface';
import { TransparencyInterface } from '/transparencyinterface';
import { VisibilityInterface } from '/visibilityinterface';
import { AntialiasingMode } from 'affinity:dom';
import { BlendMode } from 'affinity:common';
import { ColourSpaceType } from 'affinity:colours';
import { CompoundOperation } from 'affinity:dom';
import { LineCap } from 'affinity:linestyles';
import { LineJoin } from 'affinity:linestyles';
import { LineType } from 'affinity:linestyles';
import { PageBoundingBoxType } from 'affinity:dom';
import { RasterFormat } from 'affinity:raster';
import { ShapeType } from 'affinity:geometry';
import { StoryIoFormat } from 'affinity:story';
import { StrokeAlignment } from 'affinity:linestyles';

export class AddNoiseFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isAddNoiseFilterParameters: boolean;
  intensity: any;
  noiseType: any;
  isMonochromatic: boolean;
  static create(): AddNoiseFilterParameters;
}

export class AddNoiseFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isAddNoiseFilterRasterNode: boolean;
  readonly parameters: AddNoiseFilterParameters;
}

export class AddNoiseFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isAddNoiseFilterRasterNodeDefinition: boolean;
  parameters: AddNoiseFilterParameters;
  setParameters(parameters?: AddNoiseFilterParameters): this;
  static create(parameters?: any): AddNoiseFilterRasterNodeDefinition;
  static createDefault(): AddNoiseFilterRasterNodeDefinition;
}

export class AdjustmentRasterNode extends EnclosureRasterNode {
  constructor(handle?: any);
  readonly isAdjustmentRasterNode: boolean;
}

export class AdjustmentRasterNodeDefinition extends EnclosureRasterNodeDefinition {
  constructor(handle?: any);
  readonly isAdjustmentRasterNodeDefinition: boolean;
}

export class ArtTextNode extends TextNode {
  constructor(handle?: any);
  readonly isArtTextNode: boolean;
}

export class ArtTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isArtTextNodeDefinition: boolean;
  static createFromStoryBuilder(position?: any, storyBuilder?: any): ArtTextNodeDefinition;
}

export class BilateralBlurFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isBilateralBlurFilterParameters: boolean;
  radius: any;
  tolerance: any;
  static create(): BilateralBlurFilterParameters;
}

export class BilateralBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isBilateralBlurFilterRasterNode: boolean;
  readonly parameters: BilateralBlurFilterParameters;
}

export class BilateralBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBilateralBlurFilterRasterNodeDefinition: boolean;
  parameters: BilateralBlurFilterParameters;
  setParameters(parameters?: BilateralBlurFilterParameters): this;
  static create(params?: any): BilateralBlurFilterRasterNodeDefinition;
  static createDefault(): BilateralBlurFilterRasterNodeDefinition;
}

export class BlackAndWhiteAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isBlackAndWhiteAdjustmentParameters: boolean;
  red: any;
  green: any;
  blue: any;
  cyan: any;
  magenta: any;
  yellow: any;
  static create(): BlackAndWhiteAdjustmentParameters;
}

export class BlackAndWhiteAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isBlackAndWhiteAdjustmentRasterNode: boolean;
  readonly parameters: BlackAndWhiteAdjustmentParameters;
}

export class BlackAndWhiteAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBlackAndWhiteAdjustmentRasterNodeDefinition: boolean;
  parameters: BlackAndWhiteAdjustmentParameters;
  setParameters(parameters?: BlackAndWhiteAdjustmentParameters): this;
  static create(parameters?: any): BlackAndWhiteAdjustmentRasterNodeDefinition;
  static createDefault(): BlackAndWhiteAdjustmentRasterNodeDefinition;
}

export class BloomFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isBloomFilterParameters: boolean;
  shadowBlend: any;
  midtoneBlend: any;
  highlightBlend: any;
  isStrong: boolean;
  method: any;
  colour: any;
  static create(): BloomFilterParameters;
}

export class BloomFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isBloomFilterRasterNode: boolean;
  readonly parameters: BloomFilterParameters;
}

export class BloomFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBloomFilterRasterNodeDefinition: boolean;
  parameters: BloomFilterParameters;
  setParameters(parameters?: BloomFilterParameters): this;
  static create(params?: any): BloomFilterRasterNodeDefinition;
  static createDefault(): BloomFilterRasterNodeDefinition;
}

export class BoxBlurFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isBoxBlurFilterParameters: boolean;
  radius: any;
  static create(): BoxBlurFilterParameters;
}

export class BoxBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isBoxBlurFilterRasterNode: boolean;
  readonly parameters: BoxBlurFilterParameters;
}

export class BoxBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBoxBlurFilterRasterNodeDefinition: boolean;
  parameters: BoxBlurFilterParameters;
  setParameters(parameters?: BoxBlurFilterParameters): this;
  static create(params?: any): BoxBlurFilterRasterNodeDefinition;
  static createDefault(): BoxBlurFilterRasterNodeDefinition;
}

export class BrightnessContrastAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isBrightnessContrastAdjustmentParameters: boolean;
  brightness: any;
  contrast: any;
  isLinear: boolean;
  static create(): BrightnessContrastAdjustmentParameters;
}

export class BrightnessContrastAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isBrightnessContrastAdjustmentRasterNode: boolean;
  readonly parameters: BrightnessContrastAdjustmentParameters;
}

export class BrightnessContrastAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBrightnessContrastAdjustmentRasterNodeDefinition: boolean;
  parameters: BrightnessContrastAdjustmentParameters;
  setParameters(parameters?: BrightnessContrastAdjustmentParameters): this;
  static create(parameters?: any): BrightnessContrastAdjustmentRasterNodeDefinition;
  static createDefault(): BrightnessContrastAdjustmentRasterNodeDefinition;
}

export class ClarityFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isClarityFilterParameters: boolean;
  strength: any;
  static create(): ClarityFilterParameters;
}

export class ClarityFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isClarityFilterRasterNode: boolean;
  readonly parameters: ClarityFilterParameters;
}

export class ClarityFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isClarityFilterRasterNodeDefinition: boolean;
  parameters: ClarityFilterParameters;
  setParameters(parameters?: ClarityFilterParameters): this;
  static create(parameters?: any): ClarityFilterRasterNodeDefinition;
  static createDefault(): ClarityFilterRasterNodeDefinition;
}

export class ColourBalanceAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isColourBalanceAdjustmentParameters: boolean;
  readonly valuesCount: number;
  setValues(tonalRange?: any, value?: any): this;
  getValues(tonalRange?: any): any;
  enumerateValues(callback?: (...args: any[]) => any): any;
  values: any;
  preserveLuminosity: any;
  static create(): ColourBalanceAdjustmentParameters;
}

export class ColourBalanceAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isColourBalanceAdjustmentRasterNode: boolean;
  readonly parameters: ColourBalanceAdjustmentParameters;
}

export class ColourBalanceAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isColourBalanceAdjustmentRasterNodeDefinition: boolean;
  parameters: ColourBalanceAdjustmentParameters;
  setParameters(parameters?: ColourBalanceAdjustmentParameters): this;
  static create(parameters?: any): ColourBalanceAdjustmentRasterNodeDefinition;
  static createDefault(): ColourBalanceAdjustmentRasterNodeDefinition;
}

export class ColouredLogicalNode extends LogicalNode {
  constructor(handle?: any);
  readonly isColouredLogicalNode: boolean;
  readonly layerColour: Colour;
}

export class ColouredLogicalNodeDefinition extends LogicalNodeDefinition {
  constructor(handle?: any);
  readonly isColouredLogicalNodeDefinition: boolean;
}

export class ContainerNode extends ColouredLogicalNode {
  constructor(handle?: any);
  readonly isContainerNode: boolean;
}

export class ContainerNodeDefinition extends ColouredLogicalNodeDefinition {
  constructor(handle?: any);
  static createDefault(): ContainerNodeDefinition;
  static create(name?: any): ContainerNodeDefinition;
}

export class CurvePathTextNode extends TextNode {
  constructor(handle?: any);
  readonly isCurvePathTextNode: boolean;
}

export class CurvePathTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isCurvePathTextNodeDefinition: boolean;
  static createFromStoryBuilder(polyCurve?: any, storyBuilder?: any): CurvePathTextNodeDefinition;
}

export class CurvesAdjustmentParameters extends HandleObject {
  constructor(handle?: any);
  readonly isCurvesAdjustmentParameters: boolean;
  masterSpline: Spline;
  setChannelSpline(channel?: any, channelSpline?: any): any;
  min: any;
  max: any;
  getChannelSpline(channel?: any): Spline;
  readonly channelSplineCount: number;
  enumerateChannelSplines(callback?: (...args: any[]) => any): any;
  static create(): CurvesAdjustmentParameters;
}

export class CurvesAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isCurvesAdjustmentRasterNode: boolean;
  readonly parameters: CurvesAdjustmentParameters;
  readonly colourSpace: ColourSpaceType;
}

export class CurvesAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isCurvesAdjustmentRasterNodeDefinition: boolean;
  parameters: CurvesAdjustmentParameters;
  setParameters(parameters?: CurvesAdjustmentParameters): this;
  colourSpace: ColourSpaceType;
  setColourSpace(csType?: ColourSpaceType): this;
  static create(params?: any, colourSpace?: any): CurvesAdjustmentRasterNodeDefinition;
  static createDefault(document?: any): CurvesAdjustmentRasterNodeDefinition;
}

export class DefringeFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isDefringeFilterParameters: boolean;
  hue: any;
  removeComplementary: any;
  tolerance: any;
  radius: any;
  edgeBrightnessThreshold: any;
  static create(): DefringeFilterParameters;
}

export class DefringeFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDefringeFilterRasterNode: boolean;
  readonly parameters: DefringeFilterParameters;
}

export class DefringeFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDefringeFilterRasterNodeDefinition: boolean;
  parameters: DefringeFilterParameters;
  setParameters(parameters?: DefringeFilterParameters): this;
  static create(parameters?: any): DefringeFilterRasterNodeDefinition;
  static createDefault(): DefringeFilterRasterNodeDefinition;
}

export class DenoiseFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isDenoiseFilterParameters: boolean;
  luminance: any;
  luminanceDetail: any;
  luminanceContribution: any;
  colours: any;
  coloursContribution: any;
  static create(): DenoiseFilterParameters;
}

export class DenoiseFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDenoiseFilterRasterNode: boolean;
  readonly parameters: DenoiseFilterParameters;
}

export class DenoiseFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDenoiseFilterRasterNodeDefinition: boolean;
  parameters: DenoiseFilterParameters;
  setParameters(parameters?: DenoiseFilterParameters): this;
  static create(parameters?: any): DenoiseFilterRasterNodeDefinition;
  static createDefault(): DenoiseFilterRasterNodeDefinition;
}

export class DepthOfFieldFilterParameters extends HandleObject {
  constructor(handle?: any);
  readonly isDepthOfFieldFilterParameters: boolean;
  readonly mode: any;
  radius: any;
  vibrance: any;
  clarity: any;
  ellipticalParams: any;
  tiltShiftParams: any;
  static create(): DepthOfFieldFilterParameters;
}

export class DepthOfFieldFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDepthOfFieldFilterRasterNode: boolean;
  readonly parameters: DepthOfFieldFilterParameters;
}

export class DepthOfFieldFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDepthOfFieldFilterRasterNodeDefinition: boolean;
  parameters: DepthOfFieldFilterParameters;
  setParameters(parameters?: DepthOfFieldFilterParameters): this;
  static create(params?: any): DepthOfFieldFilterRasterNodeDefinition;
  static createDefault(doc?: any): DepthOfFieldFilterRasterNodeDefinition;
}

export class DevelopNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isDevelopNode: boolean;
  readonly parameters: DevelopParameters;
  readonly sourceIsRaw: any;
  readonly imageSize: any;
  readonly imageResourceInterface: ImageResourceInterface;
  readonly rasterInterface: RasterInterface;
}

export class DevelopParameters extends HandleObject {
  constructor(handle?: any);
  readonly isDevelopParameters: boolean;
  exposure: any;
  exposureEnabled: any;
  blackpoint: any;
  whitepoint: any;
  contrast: any;
  enhanceEnabled: any;
  saturation: any;
  vibrance: any;
  clarity: any;
  texture: any;
  shadowsIntensity: any;
  highlightsIntensity: any;
  shadowsHighlightsEnabled: any;
  whiteBalance: any;
  tint: any;
  whiteBalanceEnabled: any;
  readonly rawWhiteBalance: any;
  applyToneCurve: any;
  toneCurveEnabled: any;
  toneCurveMethod: any;
  curves: CurvesAdjustmentParameters;
  curvesEnabled: any;
  noiseReductionLuminanceSigma: any;
  noiseReductionChromaSigma: any;
  noiseReductionDetail: any;
  luminanceContribution: any;
  colourContribution: any;
  noiseReductionEnabled: any;
  waveletLumaSigma: any;
  waveletChromaSigma: any;
  waveletLevels: any;
  waveletChromaLevels: any;
  waveletDetail: any;
  waveletNoiseReductionEnabled: any;
  noiseAdditionIntensity: any;
  noiseAdditionGaussian: any;
  noiseAdditionColour: any;
  noiseAdditionEnabled: any;
  profileEnabled: any;
  detailRefinementRadius: any;
  detailRefinementAmount: any;
  detailRefinementMethod: any;
  detailRefinementEnabled: any;
  defringeHue: any;
  defringeComplementary: any;
  defringeTolerance: any;
  defringeThreshold: any;
  defringeRadius: any;
  defringeEnabled: any;
  chromaticAberrationEnabled: any;
  chromaticAberrationUseProfile: any;
  lensVignetteEnabled: any;
  lensVignetteUseProfile: any;
  lensVignetteIntensity: any;
  postVignetteEnabled: any;
  postVignetteIntensity: any;
  postVignetteScale: any;
  postVignetteHardness: any;
  lensCorrectionEnabled: any;
  lensProfileDistortion: any;
  lensDistortion: any;
  lensRotation: any;
  lensScale: any;
  lensHorizontal: any;
  lensVertical: any;
  readonly lensProfileName: string;
  invertEnabled: any;
  invertMethod: any;
  invertStrength: any;
  hslEnabled: any;
  blackAndWhiteEnabled: any;
  splitToningEnabled: any;
  selectiveColourEnabled: any;
  colourBalanceEnabled: any;
  hsl: HSLShiftAdjustmentParameters;
  blackAndWhite: BlackAndWhiteAdjustmentParameters;
  splitToning: SplitToningAdjustmentParameters;
  selectiveColour: SelectiveColourAdjustmentParameters;
  colourBalance: ColourBalanceAdjustmentParameters;
  showClippedHighlights: any;
  showClippedShadows: any;
  showClippedTones: any;
  showFocusPeaking: any;
  focusPeakingHue: any;
}

export class DiffuseFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isDiffuseFilterParameters: boolean;
  intensity: any;
  static create(): DiffuseFilterParameters;
}

export class DiffuseFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDiffuseFilterRasterNode: boolean;
  readonly parameters: DiffuseFilterParameters;
}

export class DiffuseFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDiffuseFilterRasterNodeDefinition: boolean;
  parameters: DiffuseFilterParameters;
  setParameters(parameters?: DiffuseFilterParameters): this;
  static create(parameters?: any): DiffuseFilterRasterNodeDefinition;
  static createDefault(): DiffuseFilterRasterNodeDefinition;
}

export class DiffuseGlowFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isDiffuseGlowFilterParameters: boolean;
  radius: any;
  intensity: any;
  threshold: any;
  opacity: any;
  static create(): DiffuseGlowFilterParameters;
}

export class DiffuseGlowFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDiffuseGlowFilterRasterNode: boolean;
  readonly parameters: DiffuseGlowFilterParameters;
}

export class DiffuseGlowFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDiffuseGlowFilterRasterNodeDefinition: boolean;
  parameters: DiffuseGlowFilterParameters;
  setParameters(parameters?: DiffuseGlowFilterParameters): this;
  static create(params?: any): DiffuseGlowFilterRasterNodeDefinition;
  static createDefault(): DiffuseGlowFilterRasterNodeDefinition;
}

export class DocumentNode extends LogicalNode {
  constructor(handle?: any);
  readonly isDocumentNode: boolean;
  readonly pageCount: number;
  readonly spreadCount: number;
}

export class DustAndScratchFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isDustAndScratchFilterParameters: boolean;
  radius: any;
  tolerance: any;
  isChannelTolerance: boolean;
  static create(): DustAndScratchFilterParameters;
}

export class DustAndScratchFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDustAndScratchFilterRasterNode: boolean;
  readonly parameters: DustAndScratchFilterParameters;
}

export class DustAndScratchFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDustAndScratchFilterRasterNodeDefinition: boolean;
  parameters: DustAndScratchFilterParameters;
  setParameters(parameters?: DustAndScratchFilterParameters): this;
  static create(parameters?: any): DustAndScratchFilterRasterNodeDefinition;
  static createDefault(): DustAndScratchFilterRasterNodeDefinition;
}

export class EmbeddedDocumentNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isEmbeddedDocumentNode: boolean;
  readonly selectedSpreadId: number;
  readonly selectedArtboardId: number;
  readonly embeddedDocumentHasSpreads: any;
  readonly embeddedDocumentHasArtboards: any;
  readonly embeddedDocumentHasPageBoundingBoxes: any;
  readonly embeddedDocumentHasLayers: any;
  readonly selectedArtboardOffset: any;
  readonly pageBoundingBoxType: PageBoundingBoxType;
  readonly PDFPassthrough: any;
  readonly canSetPDFPassthrough: boolean;
  readonly rasterDPI: any;
  readonly originalHostDPI: any;
  readonly isAffinityFile: boolean;
  readonly canMakeLinked: boolean;
  readonly canEditEmbeddedImage: boolean;
  readonly loadDocumentOptions: LoadDocumentOptions;
  readonly shouldAllowSelectDocument: boolean;
  readonly isArtboardSelected: boolean;
  readonly isArtboardDoc: boolean;
  readonly needsPassword: any;
  enumerateSpreads(includeMasters?: any, func?: any): any;
  enumerateArtboards(func?: any): any;
  enumeratePageBoundingBoxes(func?: any): any;
  enumerateLayerVisibilities(func?: any): any;
  getSpreads(includeMasters?: any): any;
  readonly artboards: any;
  readonly pageBoundingBoxes: any;
  readonly layerVisibilities: any;
  readonly imageResourceInterface: ImageResourceInterface;
  readonly imageFilePath: string;
  getImageFileSize(asBigInt?: any): any;
  readonly imageFileSize: any;
  readonly imageFileType: any;
  readonly imageFileTypeName: string;
  readonly transparencyInterface: TransparencyInterface;
  readonly transparencyFillDescriptor: any;
  readonly transparencyFill: any;
}

export class EnclosureRasterNode extends RasterNode {
  constructor(handle?: any);
  readonly isEnclosureRasterNode: boolean;
}

export class EnclosureRasterNodeDefinition extends RasterNodeDefinition {
  constructor(handle?: any);
  readonly isEnclosureRasterNodeDefinition: boolean;
}

export class ExposureAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isExposureAdjustmentParameters: boolean;
  exposure: any;
  static create(): ExposureAdjustmentParameters;
}

export class ExposureAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isExposureAdjustmentRasterNode: boolean;
  readonly parameters: ExposureAdjustmentParameters;
}

export class ExposureAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isExposureAdjustmentRasterNodeDefinition: boolean;
  parameters: ExposureAdjustmentParameters;
  static create(params?: any): ExposureAdjustmentRasterNodeDefinition;
  static createDefault(): ExposureAdjustmentRasterNodeDefinition;
}

export class FieldBlurFilterParameters extends HandleObject {
  constructor(handle?: any);
  readonly isFieldBlurFilterParameters: boolean;
  readonly blurItemCount: number;
  getBlurItem(index?: any): any;
  enumerateBlurItems(callback?: (...args: any[]) => any): any;
  addBlurItem(itemParams?: any): any;
  deleteBlurItem(index?: any): any;
  globalRadius: any;
  static create(): FieldBlurFilterParameters;
}

export class FieldBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isFieldBlurFilterRasterNode: boolean;
  readonly parameters: FieldBlurFilterParameters;
}

export class FieldBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isFieldBlurFilterRasterNodeDefinition: boolean;
  parameters: FieldBlurFilterParameters;
  setParameters(parameters?: FieldBlurFilterParameters): this;
  static create(params?: any): FieldBlurFilterRasterNodeDefinition;
  static createDefault(doc?: any): FieldBlurFilterRasterNodeDefinition;
}

export class FilterRasterNode extends EnclosureRasterNode {
  constructor(handle?: any);
  readonly isFilterRasterNode: boolean;
  readonly preserveAlpha: any;
}

export class FilterRasterNodeDefinition extends EnclosureRasterNodeDefinition {
  constructor(handle?: any);
  readonly isFilterRasterNodeDefinition: boolean;
  preserveAlpha: any;
  setPreserveAlpha(value?: any): this;
}

export class FrameTextNode extends TextNode {
  constructor(handle?: any);
  readonly isFrameTextNode: boolean;
}

export class FrameTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isFrameTextNodeDefinition: boolean;
  static createFromStoryBuilder(frameBox?: any, storyBuilder?: any): FrameTextNodeDefinition;
}

export class GaussianBlurFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isGaussianBlurFilterParameters: boolean;
  radius: any;
  static create(): GaussianBlurFilterParameters;
}

export class GaussianBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isGaussianBlurFilterRasterNode: boolean;
  readonly parameters: GaussianBlurFilterParameters;
}

export class GaussianBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isGaussianBlurFilterRasterNodeDefinition: boolean;
  parameters: GaussianBlurFilterParameters;
  setParameters(parameters?: GaussianBlurFilterParameters): this;
  static create(parameters?: any): GaussianBlurFilterRasterNodeDefinition;
  static createDefault(): GaussianBlurFilterRasterNodeDefinition;
}

export class GroupNode extends LogicalNode {
  constructor(handle?: any);
  readonly isGroupNode: boolean;
}

export class GroupNodeDefinition extends LogicalNodeDefinition {
  constructor(handle?: any);
  readonly isGroupNodeDefinition: boolean;
}

export class HSLShiftAdjustmentParameters extends HandleObject {
  constructor(handle?: any);
  readonly isHSLShiftAdjustmentParameters: boolean;
  masterParameters: any;
  setChannelParameters(channel?: any, channelParameter?: any): any;
  setChannelColourRange(channel?: any, colourRange?: any): any;
  useHSV: any;
  getChannelParameters(channel?: any): any;
  getChannelColourRange(channel?: any): any;
  readonly channelCount: number;
  enumerateChannelParameters(callback?: (...args: any[]) => any): any;
  enumerateChannelColourRanges(callback?: (...args: any[]) => any): any;
  static create(): HSLShiftAdjustmentParameters;
}

export class HSLShiftAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isHSLShiftAdjustmentRasterNode: boolean;
  readonly parameters: HSLShiftAdjustmentParameters;
}

export class HSLShiftAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isHSLShiftAdjustmentRasterNodeDefinition: boolean;
  parameters: HSLShiftAdjustmentParameters;
  static create(parameters?: any): HSLShiftAdjustmentRasterNodeDefinition;
  static createDefault(): HSLShiftAdjustmentRasterNodeDefinition;
}

export class HalftoneFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isHalftoneFilterParameters: boolean;
  cellSize: any;
  screenAngle: any;
  contrast: any;
  screenType: any;
  dotType: any;
  greyComponentReplacement: any;
  underColourRemoval: any;
  static create(): HalftoneFilterParameters;
}

export class HalftoneFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isHalftoneFilterRasterNode: boolean;
  readonly parameters: HalftoneFilterParameters;
}

export class HalftoneFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isHalftoneFilterRasterNodeDefinition: boolean;
  parameters: HalftoneFilterParameters;
  static create(params?: any): HalftoneFilterRasterNodeDefinition;
  static createDefault(): HalftoneFilterRasterNodeDefinition;
}

export class HighPassFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isHighPassFilterParameters: boolean;
  radius: any;
  isMonochrome: boolean;
  static create(): HighPassFilterParameters;
}

export class HighPassFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isHighPassFilterRasterNode: boolean;
  readonly parameters: HighPassFilterParameters;
}

export class HighPassFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isHighPassFilterRasterNodeDefinition: boolean;
  parameters: HighPassFilterParameters;
  setParameters(parameters?: HighPassFilterParameters): this;
  static create(parameters?: any): HighPassFilterRasterNodeDefinition;
  static createDefault(): HighPassFilterRasterNodeDefinition;
}

export class ImageNode extends VectorNode {
  constructor(handle?: any);
  readonly isImageNode: boolean;
  readonly extendType: any;
  readonly upsamplerType: any;
  readonly stockURL: any;
  readonly stockUserProfileURL: any;
  readonly stockAuthor: any;
  readonly lastRendered: any;
  readonly bitmapBrushFillDescriptor: any;
  readonly isKOnly: boolean;
  readonly imageResourceInterface: ImageResourceInterface;
  readonly imageFilePath: string;
  getImageFileSize(asBigInt?: any): any;
  readonly imageFileSize: any;
  readonly imageFileType: any;
  readonly imageFileTypeName: string;
  readonly rasterInterface: RasterInterface;
  readonly rasterWidth: number;
  readonly rasterHeight: number;
  readonly rasterFormat: RasterFormat;
  readonly pixelSize: any;
  createCompatibleBitmap(copyContents?: any): any;
  createCompatibleBuffer(copyContents?: any): any;
  copyTo(dest?: any, destRect?: any, srcX?: any, srcY?: any): any;
}

export class ImageNodeDefinition extends VectorNodeDefinition {
  constructor(handle?: any);
  static create(format?: any): ImageNodeDefinition;
  readonly isImageNodeDefinition: boolean;
  bitmap: RasterObject;
  setBitmap(bm?: RasterObject): this;
}

export class InvertAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isInvertAdjustmentRasterNode: boolean;
}

export class InvertAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isInvertAdjustmentRasterNodeDefinition: boolean;
  static create(): InvertAdjustmentRasterNodeDefinition;
}

export class LensBlurFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isLensBlurFilterParameters: boolean;
  radius: any;
  numberOfBlades: any;
  bladeCurvature: any;
  bloomThreshold: any;
  bloomFactor: number;
  bloomColour: any;
  static create(): LensBlurFilterParameters;
}

export class LensBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isLensBlurFilterRasterNode: boolean;
  readonly parameters: LensBlurFilterParameters;
}

export class LensBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isLensBlurFilterRasterNodeDefinition: boolean;
  parameters: LensBlurFilterParameters;
  setParameters(parameters?: LensBlurFilterParameters): this;
  static create(params?: any): LensBlurFilterRasterNodeDefinition;
  static createDefault(): LensBlurFilterRasterNodeDefinition;
}

export class LevelsAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isLevelsAdjustmentParameters: boolean;
  masterParameters: any;
  readonly channelParametersCount: number;
  setChannelParameters(channel?: any, value?: any): this;
  getChannelParameters(channel?: any): any;
  enumerateChannelParameters(callback?: (...args: any[]) => any): any;
  channelParameters: any;
  static create(): LevelsAdjustmentParameters;
}

export class LevelsAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isLevelsAdjustmentRasterNode: boolean;
  readonly parameters: LevelsAdjustmentParameters;
  readonly colourSpace: ColourSpaceType;
}

export class LevelsAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isLevelsAdjustmentRasterNodeDefinition: boolean;
  parameters: LevelsAdjustmentParameters;
  setParameters(parameters?: LevelsAdjustmentParameters): this;
  colourSpace: ColourSpaceType;
  setColourSpace(csType?: ColourSpaceType): this;
  static create(params?: any, colourSpace?: any): LevelsAdjustmentRasterNodeDefinition;
  static createDefault(document?: any): LevelsAdjustmentRasterNodeDefinition;
}

export class LogicalNode extends Node {
  constructor(handle?: any);
  readonly isLogicalNode: boolean;
  readonly hasNonMaskChildren: boolean;
  readonly hasNonMaskOrAdjustmentChildren: boolean;
  readonly brushFillInterface: BrushFillInterface;
  getBrushFillDescriptor(index?: any, obeyScaleWithObject?: boolean): any;
  setBrushFillDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): any;
  brushFillDescriptor: any;
  readonly hasBrushFill: boolean;
  readonly lineStyleInterface: LineStyleInterface;
  lineStyleDescriptor: any;
  readonly lineStyleDescriptors: any;
  lineStyle: any;
  penFillDescriptor: any;
  readonly penFillDescriptors: any;
  readonly penFill: any;
  readonly hasPenFill: boolean;
  readonly isLineStyleVisible: boolean;
  lineWeight: any;
  lineWeightPts: any;
  lineType: LineType;
  lineCap: LineCap;
  lineJoin: LineJoin;
  dashPhase: any;
  dashPattern: any;
  hasBalancedDashes: boolean;
  strokeAlignment: StrokeAlignment;
  readonly transparencyInterface: TransparencyInterface;
  readonly transparencyFillDescriptor: any;
  readonly transparencyFill: any;
}

export class LogicalNodeDefinition extends NodeDefinition {
  constructor(handle?: any);
  readonly isLogicalNodeDefinition: boolean;
}

export class MaximumBlurFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isMaximumBlurFilterParameters: boolean;
  radius: any;
  isCircular: boolean;
  static create(): MaximumBlurFilterParameters;
}

export class MaximumBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isMaximumBlurFilterRasterNode: boolean;
  readonly parameters: MaximumBlurFilterParameters;
}

export class MaximumBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isMaximumBlurFilterRasterNodeDefinition: boolean;
  parameters: MaximumBlurFilterParameters;
  setParameters(parameters?: MaximumBlurFilterParameters): this;
  static create(params?: any): MaximumBlurFilterRasterNodeDefinition;
  static createDefault(): MaximumBlurFilterRasterNodeDefinition;
}

export class MeasurementNode extends VectorNode {
  constructor(handle?: any);
  readonly isMeasurementNode: boolean;
  readonly factor: number;
  readonly scaledUnitType: any;
  readonly displayUnitType: any;
  readonly annotationOffset: any;
  readonly showEndpointMarkers: any;
  readonly useDocumentPrecision: number;
  readonly decimalPlaces: any;
  readonly spreadDistance: any;
  readonly spreadEndpoints: any;
}

export class MeasurementNodeDefinition extends VectorNodeDefinition {
  constructor(handle?: any);
  readonly isMeasurementNodeDefinition: boolean;
  annotationOffset: any;
  setAnnotationOffset(offset?: any): this;
  showEndpointMarkers: any;
  setShowEndpointMarkers(show?: any): this;
  endpoints: any;
  setEndpoints(start?: any, end?: any): this;
  factor: number;
  setFactor(factor?: number): this;
  scaledUnitType: any;
  setScaledUnitType(unitType?: any): this;
  useDocumentPrecision: number;
  decimalPlaces: any;
  setDisplayPrecision(useDocumentPrecision?: any, decimalPlaces?: any): this;
  labelGlyphAtts: any;
  setLabelGlyphAtts(glyphAtts?: any): this;
  static create(start?: any, end?: any, factor?: any, unitType?: any): MeasurementNodeDefinition;
}

export class MedianBlurFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isMedianBlurFilterParameters: boolean;
  radius: any;
  static create(): MedianBlurFilterParameters;
}

export class MedianBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isMedianBlurFilterRasterNode: boolean;
  readonly parameters: MedianBlurFilterParameters;
}

export class MedianBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isMedianBlurFilterRasterNodeDefinition: boolean;
  parameters: MedianBlurFilterParameters;
  setParameters(parameters?: MedianBlurFilterParameters): this;
  static create(params?: any): MedianBlurFilterRasterNodeDefinition;
  static createDefault(): MedianBlurFilterRasterNodeDefinition;
}

export class MinimumBlurFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isMinimumBlurFilterParameters: boolean;
  radius: any;
  isCircular: boolean;
  static create(): MinimumBlurFilterParameters;
}

export class MinimumBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isMinimumBlurFilterRasterNode: boolean;
  readonly parameters: MinimumBlurFilterParameters;
}

export class MinimumBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isMinimumBlurFilterRasterNodeDefinition: boolean;
  parameters: MinimumBlurFilterParameters;
  setParameters(parameters?: MinimumBlurFilterParameters): this;
  static create(params?: any): MinimumBlurFilterRasterNodeDefinition;
  static createDefault(): MinimumBlurFilterRasterNodeDefinition;
}

export class MotionBlurFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isMotionBlurFilterParameters: boolean;
  radius: any;
  angle: any;
  static create(): MotionBlurFilterParameters;
}

export class MotionBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isMotionBlurFilterRasterNode: boolean;
  readonly parameters: MotionBlurFilterParameters;
}

export class MotionBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isMotionBlurFilterRasterNodeDefinition: boolean;
  parameters: MotionBlurFilterParameters;
  setParameters(parameters?: MotionBlurFilterParameters): this;
  static create(params?: any): MotionBlurFilterRasterNodeDefinition;
  static createDefault(): MotionBlurFilterRasterNodeDefinition;
}

export class Node extends Selectable {
  constructor(handle?: any);
  readonly isNode: boolean;
  isSameNode(otherNode?: any): boolean;
  readonly document: any;
  readonly selfSelection: any;
  readonly nextSibling: Node;
  readonly previousSibling: Node;
  readonly parent: Node;
  readonly firstChild: any;
  readonly lastChild: any;
  getFirstChild(nodeChildType?: any): Node;
  getLastChild(nodeChildType?: any): Node;
  readonly children: NodeChildren;
  readonly enclosures: NodeChildren;
  getSpreadBaseBox(includeClips?: boolean): any;
  readonly spreadBaseBox: any;
  readonly baseToSpreadTransform: any;
  readonly localToSpreadTransform: any;
  readonly spreadToBaseTransform: any;
  getLineBox(includeClips?: boolean): any;
  getTransformedLineBox(transform?: any, scalarTransform?: any, includeClips?: boolean): any;
  getSpreadVisibleBox(includeParentEffects?: boolean): any;
  getLocalVisibleBox(): any;
  getExactSpreadBaseBox(): any;
  getExactSpreadVisibleBox(includeParentEffects?: any, considerParentClips?: any): any;
  getContentExtentsBox(includeInvisible?: any, includeOffCurvePoints?: any): any;
  getContentExtentsBoxOfChildren(includeInvisible?: any, includeOffCurvePoints?: any): any;
  readonly lineBox: any;
  readonly spreadVisibleBox: any;
  readonly localVisibleBox: any;
  readonly exactSpreadBaseBox: any;
  readonly baseBoxInterface: BaseBoxInterface;
  readonly baseBox: any;
  readonly constrainingBaseBox: any;
  readonly bmIFace: any;
  readonly blendModeInterface: BlendModeInterface;
  readonly blendMode: BlendMode;
  readonly blendOptions: any;
  readonly antialiasingMode: AntialiasingMode;
  readonly descriptionInterface: DescriptionInterface;
  readonly description: string;
  userDescription: string;
  readonly defaultDescription: string;
  readonly defaultDescriptionForDisplay: any;
  tagColour: any;
  readonly editabilityInterface: EditabilityInterface;
  readonly isEditable: boolean;
  readonly isLocalEditable: boolean;
  readonly isMasterEditable: boolean;
  readonly isLocked: boolean;
  lock(preview?: any): any;
  unlock(preview?: any): any;
  readonly exportableInterface: ExportableInterface;
  readonly exportConfig: any;
  readonly layerEffectsInterface: LayerEffectsInterface;
  readonly quickFX: any;
  readonly transformInterface: TransformInterface;
  readonly transform: any;
  readonly visibilityInterface: VisibilityInterface;
  readonly globalOpacity: any;
  readonly fillOpacity: any;
  readonly isVisible: boolean;
  readonly isVisibleInExport: boolean;
  readonly isVisibleInDomain: boolean;
  testVisibility(options?: any): any;
  readonly tagInterface: TagInterface;
  hasKey(key?: any): boolean;
  getValueForKey(key?: any): any;
  readonly isMarkAsDecoration: boolean;
  hasPredefinedKey(key?: any): boolean;
  getValueForPredefinedKey(key?: any): any;
  readonly spread: any;
  moveToFirstChild(childType?: any): any;
  moveToLastChild(childType?: any): any;
  moveToNextSibling(): any;
  moveToParent(): any;
  moveToPreviousSibling(): any;
  delete(): any;
  duplicate(transform?: any): any;
}

export class NodeCast extends HandleObject {
  constructor(handle?: any);
  setNodeHandler(callback?: (...args: any[]) => any): any;
  setArtTextNodeHandler(callback?: (...args: any[]) => any): any;
  setAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setColouredLogicalNodeHandler(callback?: (...args: any[]) => any): any;
  setCurvePathTextNodeHandler(callback?: (...args: any[]) => any): any;
  setCurvesAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDocumentNodeHandler(callback?: (...args: any[]) => any): any;
  setDevelopNodeHandler(callback?: (...args: any[]) => any): any;
  setEmbeddedDocumentNodeHandler(callback?: (...args: any[]) => any): any;
  setEnclosureRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setExposureAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setGaussianBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setBoxBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setBilateralBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setBloomFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setMedianBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDiffuseGlowFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setFieldBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDepthOfFieldFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setLensBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setMaximumBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setMinimumBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setMotionBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setRadialBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setShadowsHighlightsFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setBrightnessContrastAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setShadowsHighlightsAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setBlackAndWhiteAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setRecolourAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setPosteriseAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setSplitToningAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setInvertAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setThresholdAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setClarityFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setUnsharpMaskFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setHighPassFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDenoiseFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDiffuseFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDustAndScratchFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setAddNoiseFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setRippleFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setTwirlFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setSphericalFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setPinchPunchFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setPixelateFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setHalftoneFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setWhiteBalanceAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setColourBalanceAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setVibranceAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setNormalsAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setVignetteFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDefringeFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setVoronoiFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setSelectiveColourAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setHSLShiftAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setToneCompressionAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setToneStretchAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setFrameTextNodeHandler(callback?: (...args: any[]) => any): any;
  setGroupNodeHandler(callback?: (...args: any[]) => any): any;
  setImageNodeHandler(callback?: (...args: any[]) => any): any;
  setLevelsAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setLogicalNodeHandler(callback?: (...args: any[]) => any): any;
  setPatternRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setPhysicalNodeHandler(callback?: (...args: any[]) => any): any;
  setPolyCurveNodeHandler(callback?: (...args: any[]) => any): any;
  setPolyCurveTextNodeHandler(callback?: (...args: any[]) => any): any;
  setRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setContainerNodeHandler(callback?: (...args: any[]) => any): any;
  setShapeNodeHandler(callback?: (...args: any[]) => any): any;
  setShapePathTextNodeHandler(callback?: (...args: any[]) => any): any;
  setShapeTextNodeHandler(callback?: (...args: any[]) => any): any;
  setSpreadNodeHandler(callback?: (...args: any[]) => any): any;
  setMeasurementNodeHandler(callback?: (...args: any[]) => any): any;
  setTableTextNodeHandler(callback?: (...args: any[]) => any): any;
  setTextNodeHandler(callback?: (...args: any[]) => any): any;
  setVectorNodeHandler(callback?: (...args: any[]) => any): any;
  exec(nodeHandle?: any): any;
}

export class NodeChildren extends NodeChildrenOnly {
  constructor(parentNodeHandle?: any, childType?: any, reversed?: any);
}

export class NodeChildrenOnly extends Collection {
  constructor(parentNodeHandle?: any, childType?: any, reversed?: any);
}

export class NodeDefinition extends HandleObject {
  constructor(handle?: any);
  readonly isNodeDefinition: boolean;
  transform: any;
  setTransform(xf?: any): this;
  userDescription: string;
  setUserDescription(desc?: string): this;
}

export class NodeDescendents extends Collection {
  constructor(rootNodeHandle?: any, childType?: any, reversed?: any);
}

export class NodeFactory {
  constructor();
  create(handle?: any): any;
}

export class NormalsAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isNormalsAdjustmentParameters: boolean;
  rotation: any;
  scale: any;
  flipX: any;
  flipY: any;
  static create(): NormalsAdjustmentParameters;
}

export class NormalsAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isNormalsAdjustmentRasterNode: boolean;
  readonly parameters: NormalsAdjustmentParameters;
}

export class NormalsAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isNormalsAdjustmentRasterNodeDefinition: boolean;
  parameters: NormalsAdjustmentParameters;
  setParameters(parameters?: NormalsAdjustmentParameters): this;
  static create(parameters?: any): NormalsAdjustmentRasterNodeDefinition;
  static createDefault(): NormalsAdjustmentRasterNodeDefinition;
}

export class PatternRasterNode extends RasterNode {
  constructor(handle?: any);
  readonly isPatternRasterNode: boolean;
  readonly mirror: any;
}

export class PatternRasterNodeDefinition extends RasterNodeDefinition {
  constructor(handle?: any);
  readonly isPatternRasterNodeDefinition: boolean;
  mirror: any;
  setMirror(value?: any): this;
  static createDefault(document?: any): PatternRasterNodeDefinition;
  static create(bitmap?: any, transform?: any, mirror?: any): PatternRasterNodeDefinition;
}

export class PhysicalNode extends Node {
  constructor(handle?: any);
  readonly isPhysicalNode: boolean;
  readonly canTransformWhileProtectingChildList: boolean;
}

export class PhysicalNodeDefinition extends NodeDefinition {
  constructor(handle?: any);
  readonly isPhysicalNodeDefinition: boolean;
}

export class PinchPunchFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isPinchPunchFilterParameters: boolean;
  intensity: any;
  radius: any;
  position: any;
  static create(): PinchPunchFilterParameters;
}

export class PinchPunchFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isPinchPunchFilterRasterNode: boolean;
  readonly parameters: PinchPunchFilterParameters;
}

export class PinchPunchFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isPinchPunchFilterRasterNodeDefinition: boolean;
  parameters: PinchPunchFilterParameters;
  setParameters(parameters?: PinchPunchFilterParameters): this;
  static create(parameters?: any): PinchPunchFilterRasterNodeDefinition;
  static createDefault(document?: any): PinchPunchFilterRasterNodeDefinition;
}

export class PixelateFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isPixelateFilterParameters: boolean;
  quantisation: any;
  static create(): PixelateFilterParameters;
}

export class PixelateFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isPixelateFilterRasterNode: boolean;
  readonly parameters: PixelateFilterParameters;
}

export class PixelateFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isPixelateFilterRasterNodeDefinition: boolean;
  parameters: PixelateFilterParameters;
  setParameters(parameters?: PixelateFilterParameters): this;
  static create(params?: any): PixelateFilterRasterNodeDefinition;
  static createDefault(): PixelateFilterRasterNodeDefinition;
}

export class PolyCurveNode extends VectorNode {
  constructor(handle?: any);
  readonly isPolyCurveNode: boolean;
  readonly artboardInterface: ArtboardInterface;
  artboardEnabled: any;
  isArtboardEnabled: boolean;
  readonly artboardDescription: string;
  readonly artboardBaseBox: any;
  readonly artboardSpreadBaseBox: any;
  readonly artboardOrigin: any;
}

export class PolyCurveNodeDefinition extends VectorNodeDefinition {
  constructor(handle?: any);
  readonly isPolyCurveNodeDefinition: boolean;
  setCurves(curve?: PolyCurve): this;
  curves: PolyCurve;
  static create(curve?: any, brushFill?: any, lineFill?: any, lineStyle?: any, transparencyFill?: any): PolyCurveNodeDefinition;
  static createDefault(): PolyCurveNodeDefinition;
}

export class PolyCurveTextNode extends TextNode {
  constructor(handle?: any);
  readonly isPolyCurveTextNode: boolean;
}

export class PolyCurveTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isPolyCurveTextNodeDefinition: boolean;
  static createFromStoryBuilder(polyCurve?: any, storyBuilder?: any): PolyCurveTextNodeDefinition;
}

export class PosteriseAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isPosteriseAdjustmentParameters: boolean;
  levels: any;
  static create(): PosteriseAdjustmentParameters;
}

export class PosteriseAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isPosteriseAdjustmentRasterNode: boolean;
  readonly parameters: PosteriseAdjustmentParameters;
}

export class PosteriseAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isPosteriseAdjustmentRasterNodeDefinition: boolean;
  parameters: PosteriseAdjustmentParameters;
  setParameters(parameters?: PosteriseAdjustmentParameters): this;
  static create(parameters?: any): PosteriseAdjustmentRasterNodeDefinition;
  static createDefault(): PosteriseAdjustmentRasterNodeDefinition;
}

export class RadialBlurFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isRadialBlurFilterParameters: boolean;
  angle: any;
  position: any;
  static create(): RadialBlurFilterParameters;
}

export class RadialBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isRadialBlurFilterRasterNode: boolean;
  readonly parameters: RadialBlurFilterParameters;
}

export class RadialBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isRadialBlurFilterRasterNodeDefinition: boolean;
  parameters: RadialBlurFilterParameters;
  setParameters(parameters?: RadialBlurFilterParameters): this;
  static create(parameters?: any): RadialBlurFilterRasterNodeDefinition;
  static createDefault(document?: any): RadialBlurFilterRasterNodeDefinition;
}

export class RasterNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isRasterNode: boolean;
  readonly extendEmpty: boolean;
  readonly rasterInterface: RasterInterface;
  readonly rasterWidth: number;
  readonly rasterHeight: number;
  readonly rasterFormat: RasterFormat;
  readonly pixelSize: any;
  createCompatibleBitmap(copyContents?: any): any;
  createCompatibleBuffer(copyContents?: any): any;
  copyTo(dest?: any, destRect?: any, srcX?: any, srcY?: any): any;
}

export class RasterNodeDefinition extends PhysicalNodeDefinition {
  constructor(handle?: any);
  static create(format?: any): RasterNodeDefinition;
  readonly isRasterNodeDefinition: boolean;
  bitmap: RasterObject;
  setBitmap(bm?: RasterObject): this;
}

export class RecolourAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isRecolourAdjustmentParameters: boolean;
  hue: any;
  saturation: any;
  lightness: any;
  static create(): RecolourAdjustmentParameters;
}

export class RecolourAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isRecolourAdjustmentRasterNode: boolean;
  readonly parameters: RecolourAdjustmentParameters;
}

export class RecolourAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isRecolourAdjustmentRasterNodeDefinition: boolean;
  parameters: RecolourAdjustmentParameters;
  setParameters(parameters?: RecolourAdjustmentParameters): this;
  static create(parameters?: any): RecolourAdjustmentRasterNodeDefinition;
  static createDefault(): RecolourAdjustmentRasterNodeDefinition;
}

export class RippleFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isRippleFilterParameters: boolean;
  intensity: any;
  position: any;
  static create(): RippleFilterParameters;
}

export class RippleFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isRippleFilterRasterNode: boolean;
  readonly parameters: RippleFilterParameters;
}

export class RippleFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isRippleFilterRasterNodeDefinition: boolean;
  parameters: RippleFilterParameters;
  setParameters(parameters?: RippleFilterParameters): this;
  static create(parameters?: any): RippleFilterRasterNodeDefinition;
  static createDefault(document?: any): RippleFilterRasterNodeDefinition;
}

export class SelectiveColourAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isSelectiveColourAdjustmentParameters: boolean;
  readonly weightsCount: number;
  setWeights(colour?: any, value?: any): this;
  getWeights(colour?: any): any;
  enumerateWeights(callback?: (...args: any[]) => any): any;
  weights: any;
  isRelative: boolean;
  static create(): SelectiveColourAdjustmentParameters;
}

export class SelectiveColourAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isSelectiveColourAdjustmentRasterNode: boolean;
  readonly parameters: SelectiveColourAdjustmentParameters;
}

export class SelectiveColourAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isSelectiveColourAdjustmentRasterNodeDefinition: boolean;
  parameters: SelectiveColourAdjustmentParameters;
  setParameters(parameters?: SelectiveColourAdjustmentParameters): this;
  static create(parameters?: any): SelectiveColourAdjustmentRasterNodeDefinition;
  static createDefault(): SelectiveColourAdjustmentRasterNodeDefinition;
}

export class ShadowsHighlightsAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isShadowsHighlightsAdjustmentParameters: boolean;
  shadows: any;
  highlights: any;
  static create(): ShadowsHighlightsAdjustmentParameters;
}

export class ShadowsHighlightsAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isShadowsHighlightsAdjustmentRasterNode: boolean;
  readonly parameters: ShadowsHighlightsAdjustmentParameters;
}

export class ShadowsHighlightsAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isShadowsHighlightsAdjustmentRasterNodeDefinition: boolean;
  parameters: ShadowsHighlightsAdjustmentParameters;
  setParameters(parameters?: ShadowsHighlightsAdjustmentParameters): this;
  static create(parameters?: any): ShadowsHighlightsAdjustmentRasterNodeDefinition;
  static createDefault(): ShadowsHighlightsAdjustmentRasterNodeDefinition;
}

export class ShadowsHighlightsFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isShadowsHighlightsFilterParameters: boolean;
  version: string;
  shadowsStrength: any;
  shadowsRange: any;
  shadowsRadius: any;
  highlightsStrength: any;
  highlightsRange: any;
  highlightsRadius: any;
  static create(): ShadowsHighlightsFilterParameters;
}

export class ShadowsHighlightsFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isShadowsHighlightsFilterRasterNode: boolean;
  readonly parameters: ShadowsHighlightsFilterParameters;
}

export class ShadowsHighlightsFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isShadowsHighlightsFilterRasterNodeDefinition: boolean;
  parameters: ShadowsHighlightsFilterParameters;
  setParameters(parameters?: ShadowsHighlightsFilterParameters): this;
  static create(parameters?: any): ShadowsHighlightsFilterRasterNodeDefinition;
  static createDefault(): ShadowsHighlightsFilterRasterNodeDefinition;
}

export class ShapeNode extends VectorNode {
  constructor(handle?: any);
  readonly isShapeNode: boolean;
  readonly artboardInterface: ArtboardInterface;
  artboardEnabled: any;
  isArtboardEnabled: boolean;
  readonly artboardDescription: string;
  readonly artboardBaseBox: any;
  readonly artboardSpreadBaseBox: any;
  readonly artboardOrigin: any;
  readonly shapeInterface: ShapeInterface;
  readonly shape: ShapeType;
  readonly shapeType: ShapeType;
  readonly shapeBoundingBox: any;
}

export class ShapeNodeDefinition extends VectorNodeDefinition {
  constructor(handle?: any);
  readonly isShapeNodeDefinition: boolean;
  setShape(shape?: Shape): this;
  shape: Shape;
  setBoundingRectangle(rectangle?: any): this;
  boundingRectangle: any;
  static create(shape?: any, rectangle?: any, brushFill?: any, lineFill?: any, lineStyle?: any, transparencyFill?: any): ShapeNodeDefinition;
  static createDefault(): ShapeNodeDefinition;
}

export class ShapePathTextNode extends TextNode {
  constructor(handle?: any);
  readonly isShapePathTextNode: boolean;
  readonly shapeInterface: ShapeInterface;
  readonly shape: ShapeType;
  readonly shapeType: ShapeType;
  readonly shapeBoundingBox: any;
}

export class ShapePathTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isShapePathTextNodeDefinition: boolean;
  static createFromStoryBuilder(shape?: any, rectangle?: any, storyBuilder?: any): ShapePathTextNodeDefinition;
}

export class ShapeTextNode extends TextNode {
  constructor(handle?: any);
  readonly isShapeTextNode: boolean;
  readonly shapeInterface: ShapeInterface;
  readonly shape: ShapeType;
  readonly shapeType: ShapeType;
  readonly shapeBoundingBox: any;
}

export class ShapeTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isShapeTextNodeDefinition: boolean;
  static createFromStoryBuilder(shape?: any, rectangle?: any, storyBuilder?: any): ShapeTextNodeDefinition;
}

export class SphericalFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isSphericalFilterParameters: boolean;
  intensity: any;
  radius: any;
  position: any;
  static create(): SphericalFilterParameters;
}

export class SphericalFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isSphericalFilterRasterNode: boolean;
  readonly parameters: SphericalFilterParameters;
}

export class SphericalFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isSphericalFilterRasterNodeDefinition: boolean;
  parameters: SphericalFilterParameters;
  setParameters(parameters?: SphericalFilterParameters): this;
  static create(parameters?: any): SphericalFilterRasterNodeDefinition;
  static createDefault(document?: any): SphericalFilterRasterNodeDefinition;
}

export class SplitToningAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isSplitToningAdjustmentParameters: boolean;
  highlightsHue: any;
  highlightsSaturation: any;
  shadowsHue: any;
  shadowsSaturation: any;
  balance: any;
  static create(): SplitToningAdjustmentParameters;
}

export class SplitToningAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isSplitToningAdjustmentRasterNode: boolean;
  readonly parameters: SplitToningAdjustmentParameters;
}

export class SplitToningAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isSplitToningAdjustmentRasterNodeDefinition: boolean;
  parameters: SplitToningAdjustmentParameters;
  setParameters(parameters?: SplitToningAdjustmentParameters): this;
  static create(parameters?: any): SplitToningAdjustmentRasterNodeDefinition;
  static createDefault(): SplitToningAdjustmentRasterNodeDefinition;
}

export class SpreadNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isSpreadNode: boolean;
  readonly layers: NodeChildren;
  getSpreadExtents(options?: any): any;
  readonly physicalRootInterface: PhysicalRootInterface;
  readonly physicalRootPropertiesInterface: PhysicalRootPropertiesInterface;
  readonly physicalRootProperties: any;
  readonly pageCount: number;
  readonly artboardCount: number;
  getArtboard(index?: any): ArtboardInterface;
  enumerateArtboards(callback?: (...args: any[]) => any): any;
  readonly artboards: any;
  readonly firstPageIndex: number;
  readonly lastPageIndex: number;
  readonly isFirstPage: boolean;
  getPageIndexOfPoint(pt?: any, relativeToSpread?: any): any;
  getPageIndexOfBox(box?: any, relativeToSpread?: any): any;
}

export class TableTextNode extends TextNode {
  constructor(handle?: any);
  readonly isTableTextNode: boolean;
}

export class TableTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isTableTextNodeDefinition: boolean;
  static create(box?: any, size?: any): TableTextNodeDefinition;
}

export class TextNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isTextNode: boolean;
  readonly artboardInterface: ArtboardInterface;
  artboardEnabled: any;
  isArtboardEnabled: boolean;
  readonly artboardDescription: string;
  readonly artboardBaseBox: any;
  readonly artboardSpreadBaseBox: any;
  readonly artboardOrigin: any;
  readonly brushFillInterface: BrushFillInterface;
  getBrushFillDescriptor(index?: any, obeyScaleWithObject?: boolean): any;
  setBrushFillDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): any;
  brushFillDescriptor: any;
  readonly hasBrushFill: boolean;
  readonly compoundOperationInterface: CompoundOperationInterface;
  readonly compoundOperation: CompoundOperation;
  readonly curvesInterface: CurvesInterface;
  readonly polyCurve: any;
  readonly lineStyleInterface: LineStyleInterface;
  lineStyleDescriptor: any;
  readonly lineStyleDescriptors: any;
  lineStyle: any;
  penFillDescriptor: any;
  readonly penFillDescriptors: any;
  readonly penFill: any;
  readonly hasPenFill: boolean;
  readonly isLineStyleVisible: boolean;
  lineWeight: any;
  lineWeightPts: any;
  lineType: LineType;
  lineCap: LineCap;
  lineJoin: LineJoin;
  dashPhase: any;
  dashPattern: any;
  hasBalancedDashes: boolean;
  strokeAlignment: StrokeAlignment;
  readonly storyInterface: StoryInterface;
  getText(startPos?: number, maxLength?: any, format?: StoryIoFormat): any;
  readonly text: string;
  readonly story: any;
  readonly storyRange: any;
  setText(str?: string): this;
  readonly textFrameInterface: TextFrameInterface;
  readonly transparencyInterface: TransparencyInterface;
  readonly transparencyFillDescriptor: any;
  readonly transparencyFill: any;
}

export class TextNodeDefinition extends PhysicalNodeDefinition {
  constructor(handle?: any);
  readonly isTextNodeDefinition: boolean;
}

export class ThresholdAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isThresholdAdjustmentParameters: boolean;
  threshold: any;
  static create(): ThresholdAdjustmentParameters;
}

export class ThresholdAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isThresholdAdjustmentRasterNode: boolean;
  readonly parameters: ThresholdAdjustmentParameters;
}

export class ThresholdAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isThresholdAdjustmentRasterNodeDefinition: boolean;
  parameters: ThresholdAdjustmentParameters;
  setParameters(parameters?: ThresholdAdjustmentParameters): this;
  static create(parameters?: any): ThresholdAdjustmentRasterNodeDefinition;
  static createDefault(): ThresholdAdjustmentRasterNodeDefinition;
}

export class ToneCompressionAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isToneCompressionAdjustmentParameters: boolean;
  method: any;
  exposure: any;
  gamma: any;
  colour: any;
  static create(): ToneCompressionAdjustmentParameters;
}

export class ToneCompressionAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isToneCompressionAdjustmentRasterNode: boolean;
  readonly parameters: ToneCompressionAdjustmentParameters;
}

export class ToneCompressionAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isToneCompressionAdjustmentRasterNodeDefinition: boolean;
  parameters: ToneCompressionAdjustmentParameters;
  setParameters(parameters?: ToneCompressionAdjustmentParameters): this;
  static create(parameters?: any): ToneCompressionAdjustmentRasterNodeDefinition;
  static createDefault(): ToneCompressionAdjustmentRasterNodeDefinition;
}

export class ToneStretchAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isToneStretchAdjustmentParameters: boolean;
  method: any;
  gamma: any;
  stretchFactor: number;
  compression: any;
  static create(): ToneStretchAdjustmentParameters;
}

export class ToneStretchAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isToneStretchAdjustmentRasterNode: boolean;
  readonly parameters: ToneStretchAdjustmentParameters;
}

export class ToneStretchAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isToneStretchAdjustmentRasterNodeDefinition: boolean;
  parameters: ToneStretchAdjustmentParameters;
  setParameters(parameters?: ToneStretchAdjustmentParameters): this;
  static create(parameters?: any): ToneStretchAdjustmentRasterNodeDefinition;
  static createDefault(): ToneStretchAdjustmentRasterNodeDefinition;
}

export class TwirlFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isTwirlFilterParameters: boolean;
  angle: any;
  radius: any;
  position: any;
  static create(): TwirlFilterParameters;
}

export class TwirlFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isTwirlFilterRasterNode: boolean;
  readonly parameters: TwirlFilterParameters;
}

export class TwirlFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isTwirlFilterRasterNodeDefinition: boolean;
  parameters: TwirlFilterParameters;
  setParameters(parameters?: TwirlFilterParameters): this;
  static create(parameters?: any): TwirlFilterRasterNodeDefinition;
  static createDefault(document?: any): TwirlFilterRasterNodeDefinition;
}

export class UnsharpMaskFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isUnsharpMaskFilterParameters: boolean;
  radius: any;
  threshold: any;
  factor: number;
  static create(): UnsharpMaskFilterParameters;
}

export class UnsharpMaskFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isUnsharpMaskFilterRasterNode: boolean;
  readonly parameters: UnsharpMaskFilterParameters;
}

export class UnsharpMaskFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isUnsharpMaskFilterRasterNodeDefinition: boolean;
  parameters: UnsharpMaskFilterParameters;
  setParameters(parameters?: UnsharpMaskFilterParameters): this;
  static create(parameters?: any): UnsharpMaskFilterRasterNodeDefinition;
  static createDefault(): UnsharpMaskFilterRasterNodeDefinition;
}

export class VectorNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isVectorNode: boolean;
  readonly canBeExpressedAsVectorClip: boolean;
  readonly brushFillInterface: BrushFillInterface;
  getBrushFillDescriptor(index?: any, obeyScaleWithObject?: boolean): any;
  setBrushFillDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): any;
  brushFillDescriptor: any;
  readonly hasBrushFill: boolean;
  readonly compoundOperationInterface: CompoundOperationInterface;
  readonly compoundOperation: CompoundOperation;
  readonly curvesInterface: CurvesInterface;
  readonly polyCurve: any;
  readonly lineStyleInterface: LineStyleInterface;
  lineStyleDescriptor: any;
  readonly lineStyleDescriptors: any;
  lineStyle: any;
  penFillDescriptor: any;
  readonly penFillDescriptors: any;
  readonly penFill: any;
  readonly hasPenFill: boolean;
  readonly isLineStyleVisible: boolean;
  lineWeight: any;
  lineWeightPts: any;
  lineType: LineType;
  lineCap: LineCap;
  lineJoin: LineJoin;
  dashPhase: any;
  dashPattern: any;
  hasBalancedDashes: boolean;
  strokeAlignment: StrokeAlignment;
  readonly pictureFrameInterface: PictureFrameInterface;
  readonly pictureFrameEnabled: any;
  readonly pictureFrameDescription: string;
  readonly transparencyInterface: TransparencyInterface;
  readonly transparencyFillDescriptor: any;
  readonly transparencyFill: any;
}

export class VectorNodeDefinition extends PhysicalNodeDefinition {
  constructor(handle?: any);
  readonly isVectorNodeDefinition: boolean;
  addBrushFillDescriptor(brushFillDescriptor?: any): this;
  addLineDescriptors(lineFillDescriptor?: any, lineStyleDescriptor?: any): this;
  setTransparencyDescriptor(transparencyDescriptor?: FillDescriptor): this;
  transparencyDescriptor: FillDescriptor;
  readonly brushFillDescriptorCount: number;
  getBrushFillDescriptor(index?: any): FillDescriptor;
  insertBrushFillDescriptor(brushFillDescriptor?: any, index?: any): this;
  setBrushFillDescriptor(brushFillDescriptor?: any, index?: any): this;
  removeBrushFillDescriptor(index?: any): this;
  currentBrushFillIndex: number;
  readonly lineDescriptorsCount: number;
  getLineDescriptors(index?: any): any;
  insertLineDescriptors(lineFillDescriptor?: any, lineStyleDescriptor?: any, index?: any): this;
  setLineDescriptors(lineFillDescriptor?: any, lineStyleDescriptor?: any, index?: any): this;
  removeLineDescriptors(index?: any): this;
  currentLineDescriptorsIndex: number;
  setPictureFrameEnabled(pictureFrameEnabled?: any): this;
  pictureFrameEnabled: any;
}

export class VibranceAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isVibranceAdjustmentParameters: boolean;
  vibrance: any;
  saturation: any;
  static create(): VibranceAdjustmentParameters;
}

export class VibranceAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isVibranceAdjustmentRasterNode: boolean;
  readonly parameters: VibranceAdjustmentParameters;
}

export class VibranceAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isVibranceAdjustmentRasterNodeDefinition: boolean;
  parameters: VibranceAdjustmentParameters;
  setParameters(parameters?: VibranceAdjustmentParameters): this;
  static create(parameters?: any): VibranceAdjustmentRasterNodeDefinition;
  static createDefault(): VibranceAdjustmentRasterNodeDefinition;
}

export class VignetteFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isVignetteFilterParameters: boolean;
  exposure: any;
  hardness: any;
  scale: any;
  shape: ShapeType;
  static create(): VignetteFilterParameters;
}

export class VignetteFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isVignetteFilterRasterNode: boolean;
  readonly parameters: VignetteFilterParameters;
}

export class VignetteFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isVignetteFilterRasterNodeDefinition: boolean;
  parameters: VignetteFilterParameters;
  setParameters(parameters?: VignetteFilterParameters): this;
  static create(parameters?: any): VignetteFilterRasterNodeDefinition;
  static createDefault(): VignetteFilterRasterNodeDefinition;
}

export class VoronoiFilterParameters extends HandleObject {
  constructor(...args: any);
  readonly isVoronoiFilterParameters: boolean;
  cellSize: any;
  lineWidth: number;
  static create(): VoronoiFilterParameters;
}

export class VoronoiFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isVoronoiFilterRasterNode: boolean;
  readonly parameters: VoronoiFilterParameters;
}

export class VoronoiFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isVoronoiFilterRasterNodeDefinition: boolean;
  parameters: VoronoiFilterParameters;
  setParameters(parameters?: VoronoiFilterParameters): this;
  static create(parameters?: any): VoronoiFilterRasterNodeDefinition;
  static createDefault(): VoronoiFilterRasterNodeDefinition;
}

export class WhiteBalanceAdjustmentParameters extends HandleObject {
  constructor(...args: any);
  readonly isWhiteBalanceAdjustmentParameters: boolean;
  whiteBalance: any;
  tint: any;
  static create(): WhiteBalanceAdjustmentParameters;
}

export class WhiteBalanceAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isWhiteBalanceAdjustmentRasterNode: boolean;
  readonly parameters: WhiteBalanceAdjustmentParameters;
}

export class WhiteBalanceAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isWhiteBalanceAdjustmentRasterNodeDefinition: boolean;
  parameters: WhiteBalanceAdjustmentParameters;
  setParameters(parameters?: WhiteBalanceAdjustmentParameters): this;
  static create(parameters?: any): WhiteBalanceAdjustmentRasterNodeDefinition;
  static createDefault(): WhiteBalanceAdjustmentRasterNodeDefinition;
}

export { ColourBalanceValues } from 'affinity:dom';
export { HSLShiftAdjustmentChannelParameters } from 'affinity:dom';
export { HSLShiftAdjustmentColourRange } from 'affinity:dom';
export { LevelsAdjustmentChannelParameters } from 'affinity:dom';
export { EllipticalDepthOfFieldParameters } from 'affinity:dom';
export { FieldBlurItemParameters } from 'affinity:dom';
export { TiltShiftDepthOfFieldParameters } from 'affinity:dom';
export { AddNoiseType } from 'affinity:dom';
export { BloomMethod } from 'affinity:dom';
export { ColourSpaceType } from 'affinity:colours';
export { DepthOfFieldMode } from 'affinity:dom';
export { DevelopDetailRefinementMethod } from 'affinity:dom';
export { DevelopInvertMethod } from 'affinity:dom';
export { DevelopToneCurveMethod } from 'affinity:dom';
export { HalftoneDotType } from 'affinity:dom';
export { HalftoneScreenType } from 'affinity:dom';
export { LineDescriptors } from 'affinity:dom';
export { NodeChildType } from 'affinity:dom';
export { PageBoundingBoxType } from 'affinity:dom';
export { RasterExtendType } from 'affinity:raster';
export { RasterFormat } from 'affinity:raster';
export { RasterResamplerType } from 'affinity:raster';
export { ShadowsHighlightsVersion } from 'affinity:dom';
export { SelectiveColour } from 'affinity:dom';
export { SelectiveColourWeights } from 'affinity:dom';
export { TonalRangeType } from 'affinity:dom';
export { ToneCompressionMethod } from 'affinity:dom';
export { ToneStretchMethod } from 'affinity:dom';
export { UnitType } from 'affinity:common';
export function createTypedNode(handle?: any): any;
export const getNodeSiblings: any;
export const getNodeChildren: any;
export const getNodesRecursive: any;
export const getNodeChildrenRecursive: any;
