// Auto-generated by tools/generate_types.py. Do not edit.

import { Collection } from '/collection';
import { HandleObject } from '/handleobject';
import { Selectable } from '/selectable';

export class AddNoiseFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isAddNoiseFilterRasterNode: any;
  readonly parameters: any;
}

export class AddNoiseFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isAddNoiseFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): AddNoiseFilterRasterNodeDefinition;
  static createDefault(): AddNoiseFilterRasterNodeDefinition;
}

export class AdjustmentRasterNode extends EnclosureRasterNode {
  constructor(handle?: any);
  readonly isAdjustmentRasterNode: any;
}

export class AdjustmentRasterNodeDefinition extends EnclosureRasterNodeDefinition {
  constructor(handle?: any);
  readonly isAdjustmentRasterNodeDefinition: any;
}

export class ArtTextNode extends TextNode {
  constructor(handle?: any);
  readonly isArtTextNode: any;
}

export class ArtTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isArtTextNodeDefinition: any;
  static createFromStoryBuilder(position?: any, storyBuilder?: any): ArtTextNodeDefinition;
}

export class BilateralBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isBilateralBlurFilterRasterNode: any;
  readonly parameters: any;
}

export class BilateralBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBilateralBlurFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): BilateralBlurFilterRasterNodeDefinition;
  static createDefault(): BilateralBlurFilterRasterNodeDefinition;
}

export class BlackAndWhiteAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isBlackAndWhiteAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class BlackAndWhiteAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBlackAndWhiteAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): BlackAndWhiteAdjustmentRasterNodeDefinition;
  static createDefault(): BlackAndWhiteAdjustmentRasterNodeDefinition;
}

export class BloomFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isBloomFilterRasterNode: any;
  readonly parameters: any;
}

export class BloomFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBloomFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): BloomFilterRasterNodeDefinition;
  static createDefault(): BloomFilterRasterNodeDefinition;
}

export class BoxBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isBoxBlurFilterRasterNode: any;
  readonly parameters: any;
}

export class BoxBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBoxBlurFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): BoxBlurFilterRasterNodeDefinition;
  static createDefault(): BoxBlurFilterRasterNodeDefinition;
}

export class BrightnessContrastAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isBrightnessContrastAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class BrightnessContrastAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBrightnessContrastAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): BrightnessContrastAdjustmentRasterNodeDefinition;
  static createDefault(): BrightnessContrastAdjustmentRasterNodeDefinition;
}

export class ClarityFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isClarityFilterRasterNode: any;
  readonly parameters: any;
}

export class ClarityFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isClarityFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ClarityFilterRasterNodeDefinition;
  static createDefault(): ClarityFilterRasterNodeDefinition;
}

export class ColourBalanceAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isColourBalanceAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class ColourBalanceAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isColourBalanceAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ColourBalanceAdjustmentRasterNodeDefinition;
  static createDefault(): ColourBalanceAdjustmentRasterNodeDefinition;
}

export class ColouredLogicalNode extends LogicalNode {
  constructor(handle?: any);
  readonly isColouredLogicalNode: any;
  readonly layerColour: any;
}

export class ColouredLogicalNodeDefinition extends LogicalNodeDefinition {
  constructor(handle?: any);
  readonly isColouredLogicalNodeDefinition: any;
}

export class ContainerNode extends ColouredLogicalNode {
  constructor(handle?: any);
  readonly isContainerNode: any;
}

export class ContainerNodeDefinition extends ColouredLogicalNodeDefinition {
  constructor(handle?: any);
  static createDefault(): ContainerNodeDefinition;
  static create(name?: any): ContainerNodeDefinition;
}

export class CurvePathTextNode extends TextNode {
  constructor(handle?: any);
  readonly isCurvePathTextNode: any;
}

export class CurvesAdjustmentParameters extends HandleObject {
  constructor(handle?: any);
  readonly isCurvesAdjustmentParameters: any;
  masterSpline: any;
  setChannelSpline(channel?: any, channelSpline?: any): any;
  min: any;
  max: any;
  getChannelSpline(channel?: any): any;
  static create(): CurvesAdjustmentParameters;
}

export class CurvesAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isCurvesAdjustmentRasterNode: any;
  readonly parameters: CurvesAdjustmentParameters;
  readonly colourSpace: any;
}

export class CurvesAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isCurvesAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  colourSpace: any;
  setColourSpace(csType?: any): this;
  static create(params?: any, colourSpace?: any): CurvesAdjustmentRasterNodeDefinition;
  static createDefault(document?: any): CurvesAdjustmentRasterNodeDefinition;
}

export class DefringeFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDefringeFilterRasterNode: any;
  readonly parameters: any;
}

export class DefringeFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDefringeFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): DefringeFilterRasterNodeDefinition;
  static createDefault(): DefringeFilterRasterNodeDefinition;
}

export class DenoiseFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDenoiseFilterRasterNode: any;
  readonly parameters: any;
}

export class DenoiseFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDenoiseFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): DenoiseFilterRasterNodeDefinition;
  static createDefault(): DenoiseFilterRasterNodeDefinition;
}

export class DepthOfFieldFilterParameters extends HandleObject {
  constructor(handle?: any);
  readonly isDepthOfFieldFilterParameters: any;
  readonly mode: any;
  radius: any;
  vibrance: any;
  clarity: any;
  ellipticalParams: any;
  tiltShiftParams: any;
  static create(): DepthOfFieldFilterParameters;
}

export class DepthOfFieldFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDepthOfFieldFilterRasterNode: any;
  readonly parameters: DepthOfFieldFilterParameters;
}

export class DepthOfFieldFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDepthOfFieldFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): DepthOfFieldFilterRasterNodeDefinition;
  static createDefault(doc?: any): DepthOfFieldFilterRasterNodeDefinition;
}

export class DiffuseFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDiffuseFilterRasterNode: any;
  readonly parameters: any;
}

export class DiffuseFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDiffuseFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): DiffuseFilterRasterNodeDefinition;
  static createDefault(): DiffuseFilterRasterNodeDefinition;
}

export class DiffuseGlowFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDiffuseGlowFilterRasterNode: any;
  readonly parameters: any;
}

export class DiffuseGlowFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDiffuseGlowFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): DiffuseGlowFilterRasterNodeDefinition;
  static createDefault(): DiffuseGlowFilterRasterNodeDefinition;
}

export class DocumentNode extends LogicalNode {
  constructor(handle?: any);
  readonly isDocumentNode: any;
  readonly pageCount: any;
  readonly spreadCount: any;
}

export class DustAndScratchFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDustAndScratchFilterRasterNode: any;
  readonly parameters: any;
}

export class DustAndScratchFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDustAndScratchFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): DustAndScratchFilterRasterNodeDefinition;
  static createDefault(): DustAndScratchFilterRasterNodeDefinition;
}

export class EmbeddedDocumentNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isEmbeddedDocumentNode: any;
  readonly selectedSpreadId: any;
  readonly selectedArtboardId: any;
  readonly embeddedDocumentHasSpreads: any;
  readonly embeddedDocumentHasArtboards: any;
  readonly embeddedDocumentHasPageBoundingBoxes: any;
  readonly embeddedDocumentHasLayers: any;
  readonly selectedArtboardOffset: any;
  readonly pageBoundingBoxType: any;
  readonly PDFPassthrough: any;
  readonly canSetPDFPassthrough: any;
  readonly rasterDPI: any;
  readonly originalHostDPI: any;
  readonly isAffinityFile: any;
  readonly canMakeLinked: any;
  readonly canEditEmbeddedImage: any;
  readonly loadDocumentOptions: any;
  readonly shouldAllowSelectDocument: any;
  readonly isArtboardSelected: any;
  readonly isArtboardDoc: any;
  readonly needsPassword: any;
  enumerateSpreads(includeMasters?: any, func?: any): any;
  enumerateArtboards(func?: any): any;
  enumeratePageBoundingBoxes(func?: any): any;
  enumerateLayerVisibilities(func?: any): any;
  getSpreads(includeMasters?: any): any;
  readonly artboards: any;
  readonly pageBoundingBoxes: any;
  readonly layerVisibilities: any;
  readonly imageResourceInterface: any;
  readonly imageFilePath: any;
  readonly imageFileSize: any;
  readonly imageFileType: any;
  readonly imageFileTypeName: any;
  readonly transparencyInterface: any;
  readonly transparencyFillDescriptor: any;
  readonly transparencyFill: any;
}

export class EnclosureRasterNode extends RasterNode {
  constructor(handle?: any);
  readonly isEnclosureRasterNode: any;
}

export class EnclosureRasterNodeDefinition extends RasterNodeDefinition {
  constructor(handle?: any);
  readonly isEnclosureRasterNodeDefinition: any;
}

export class ExposureAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isExposureAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class ExposureAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isExposureAdjustmentRasterNodeDefinition: any;
  parameters: any;
  static create(params?: any): ExposureAdjustmentRasterNodeDefinition;
  static createDefault(): ExposureAdjustmentRasterNodeDefinition;
}

export class FieldBlurFilterParameters extends HandleObject {
  constructor(handle?: any);
  readonly isFieldBlurFilterParameters: any;
  readonly blurItemCount: any;
  getBlurItem(index?: any): any;
  addBlurItem(itemParams?: any): any;
  deleteBlurItem(index?: any): any;
  globalRadius: any;
  static create(): FieldBlurFilterParameters;
}

export class FieldBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isFieldBlurFilterRasterNode: any;
  readonly parameters: FieldBlurFilterParameters;
}

export class FieldBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isFieldBlurFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): FieldBlurFilterRasterNodeDefinition;
  static createDefault(doc?: any): FieldBlurFilterRasterNodeDefinition;
}

export class FilterRasterNode extends EnclosureRasterNode {
  constructor(handle?: any);
  readonly isFilterRasterNode: any;
  readonly preserveAlpha: any;
}

export class FilterRasterNodeDefinition extends EnclosureRasterNodeDefinition {
  constructor(handle?: any);
  readonly isFilterRasterNodeDefinition: any;
  preserveAlpha: any;
  setPreserveAlpha(value?: any): this;
}

export class FrameTextNode extends TextNode {
  constructor(handle?: any);
  readonly isFrameTextNode: any;
}

export class FrameTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isFrameTextNodeDefinition: any;
  static createFromStoryBuilder(frameBox?: any, storyBuilder?: any): FrameTextNodeDefinition;
}

export class GaussianBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isGaussianBlurFilterRasterNode: any;
  readonly parameters: any;
}

export class GaussianBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isGaussianBlurFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): GaussianBlurFilterRasterNodeDefinition;
  static createDefault(): GaussianBlurFilterRasterNodeDefinition;
}

export class GroupNode extends LogicalNode {
  constructor(handle?: any);
  readonly isGroupNode: any;
}

export class GroupNodeDefinition extends LogicalNodeDefinition {
  constructor(handle?: any);
  readonly isGroupNodeDefinition: any;
}

export class HSLShiftAdjustmentParameters extends HandleObject {
  constructor(handle?: any);
  readonly isHSLShiftAdjustmentParameters: any;
  masterParameters: any;
  setChannelParameters(channel?: any, channelParameter?: any): any;
  setChannelColourRange(channel?: any, colourRange?: any): any;
  useHSV: any;
  getChannelParameters(channel?: any): any;
  getChannelColourRange(channel?: any): any;
  static create(): HSLShiftAdjustmentParameters;
}

export class HSLShiftAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isHSLShiftAdjustmentRasterNode: any;
  readonly parameters: HSLShiftAdjustmentParameters;
}

export class HSLShiftAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isHSLShiftAdjustmentRasterNodeDefinition: any;
  parameters: any;
  static create(parameters?: any): HSLShiftAdjustmentRasterNodeDefinition;
  static createDefault(): HSLShiftAdjustmentRasterNodeDefinition;
}

export class HalftoneFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isHalftoneFilterRasterNode: any;
  readonly parameters: any;
}

export class HalftoneFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isHalftoneFilterRasterNodeDefinition: any;
  parameters: any;
  static create(params?: any): HalftoneFilterRasterNodeDefinition;
  static createDefault(): HalftoneFilterRasterNodeDefinition;
}

export class HighPassFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isHighPassFilterRasterNode: any;
  readonly parameters: any;
}

export class HighPassFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isHighPassFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): HighPassFilterRasterNodeDefinition;
  static createDefault(): HighPassFilterRasterNodeDefinition;
}

export class ImageNode extends VectorNode {
  constructor(handle?: any);
  readonly isImageNode: any;
  readonly extendType: any;
  readonly upsamplerType: any;
  readonly stockURL: any;
  readonly stockUserProfileURL: any;
  readonly stockAuthor: any;
  readonly lastRendered: any;
  readonly bitmapBrushFillDescriptor: any;
  readonly isKOnly: any;
  readonly imageResourceInterface: any;
  readonly imageFilePath: any;
  readonly imageFileSize: any;
  readonly imageFileType: any;
  readonly imageFileTypeName: any;
  readonly rasterInterface: any;
  readonly rasterWidth: any;
  readonly rasterHeight: any;
  readonly rasterFormat: any;
  readonly pixelSize: any;
  createCompatibleBitmap(copyContents?: any): any;
  createCompatibleBuffer(copyContents?: any): any;
  copyTo(dest?: any, destRect?: any, srcX?: any, srcY?: any): any;
}

export class ImageNodeDefinition extends VectorNodeDefinition {
  constructor(handle?: any);
  static create(format?: any): ImageNodeDefinition;
  readonly isImageNodeDefinition: any;
  bitmap: any;
  setBitmap(bm?: any): this;
}

export class InvertAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isInvertAdjustmentRasterNode: any;
}

export class InvertAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isInvertAdjustmentRasterNodeDefinition: any;
  static create(): InvertAdjustmentRasterNodeDefinition;
}

export class LensBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isLensBlurFilterRasterNode: any;
  readonly parameters: any;
}

export class LensBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isLensBlurFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): LensBlurFilterRasterNodeDefinition;
  static createDefault(): LensBlurFilterRasterNodeDefinition;
}

export class LevelsAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isLevelsAdjustmentRasterNode: any;
  readonly parameters: any;
  readonly colourSpace: any;
}

export class LevelsAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isLevelsAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  colourSpace: any;
  setColourSpace(csType?: any): this;
  static create(params?: any, colourSpace?: any): LevelsAdjustmentRasterNodeDefinition;
  static createDefault(document?: any): LevelsAdjustmentRasterNodeDefinition;
}

export class LogicalNode extends Node {
  constructor(handle?: any);
  readonly isLogicalNode: any;
  readonly hasNonMaskChildren: any;
  readonly hasNonMaskOrAdjustmentChildren: any;
  readonly brushFillInterface: any;
  getBrushFillDescriptor(index?: any, obeyScaleWithObject?: any): any;
  setBrushFillDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): any;
  brushFillDescriptor: any;
  readonly hasBrushFill: any;
  readonly lineStyleInterface: any;
  lineStyleDescriptor: any;
  readonly lineStyleDescriptors: any;
  lineStyle: any;
  penFillDescriptor: any;
  readonly penFillDescriptors: any;
  readonly penFill: any;
  readonly hasPenFill: any;
  readonly isLineStyleVisible: any;
  lineWeight: any;
  lineWeightPts: any;
  lineType: any;
  lineCap: any;
  lineJoin: any;
  dashPhase: any;
  dashPattern: any;
  hasBalancedDashes: any;
  strokeAlignment: any;
  readonly transparencyInterface: any;
  readonly transparencyFillDescriptor: any;
  readonly transparencyFill: any;
}

export class LogicalNodeDefinition extends NodeDefinition {
  constructor(handle?: any);
  readonly isLogicalNodeDefinition: any;
}

export class MaximumBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isMaximumBlurFilterRasterNode: any;
  readonly parameters: any;
}

export class MaximumBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isMaximumBlurFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): MaximumBlurFilterRasterNodeDefinition;
  static createDefault(): MaximumBlurFilterRasterNodeDefinition;
}

export class MedianBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isMedianBlurFilterRasterNode: any;
  readonly parameters: any;
}

export class MedianBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isMedianBlurFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): MedianBlurFilterRasterNodeDefinition;
  static createDefault(): MedianBlurFilterRasterNodeDefinition;
}

export class MinimumBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isMinimumBlurFilterRasterNode: any;
  readonly parameters: any;
}

export class MinimumBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isMinimumBlurFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): MinimumBlurFilterRasterNodeDefinition;
  static createDefault(): MinimumBlurFilterRasterNodeDefinition;
}

export class MotionBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isMotionBlurFilterRasterNode: any;
  readonly parameters: any;
}

export class MotionBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isMotionBlurFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): MotionBlurFilterRasterNodeDefinition;
  static createDefault(): MotionBlurFilterRasterNodeDefinition;
}

export class Node extends Selectable {
  constructor(handle?: any);
  readonly isNode: any;
  isSameNode(otherNode?: any): any;
  readonly document: any;
  readonly selfSelection: any;
  readonly nextSibling: any;
  readonly previousSibling: any;
  readonly parent: any;
  readonly firstChild: any;
  readonly lastChild: any;
  getFirstChild(nodeChildType?: any): any;
  getLastChild(nodeChildType?: any): any;
  readonly children: NodeChildren;
  readonly enclosures: NodeChildren;
  getSpreadBaseBox(includeClips?: any): any;
  readonly spreadBaseBox: any;
  readonly baseToSpreadTransform: any;
  readonly localToSpreadTransform: any;
  readonly spreadToBaseTransform: any;
  getLineBox(includeClips?: any): any;
  getTransformedLineBox(transform?: any, scalarTransform?: any, includeClips?: any): any;
  getSpreadVisibleBox(includeParentEffects?: any): any;
  getLocalVisibleBox(): any;
  getExactSpreadBaseBox(): any;
  getExactSpreadVisibleBox(includeParentEffects?: any, considerParentClips?: any): any;
  getContentExtentsBox(includeInvisible?: any, includeOffCurvePoints?: any): any;
  getContentExtentsBoxOfChildren(includeInvisible?: any, includeOffCurvePoints?: any): any;
  readonly lineBox: any;
  readonly spreadVisibleBox: any;
  readonly localVisibleBox: any;
  readonly exactSpreadBaseBox: any;
  readonly baseBoxInterface: any;
  readonly baseBox: any;
  readonly constrainingBaseBox: any;
  readonly bmIFace: any;
  readonly blendModeInterface: any;
  readonly blendMode: any;
  readonly blendOptions: any;
  readonly antialiasingMode: any;
  readonly descriptionInterface: any;
  readonly description: any;
  userDescription: any;
  readonly defaultDescription: any;
  readonly defaultDescriptionForDisplay: any;
  tagColour: any;
  readonly editabilityInterface: any;
  readonly isEditable: any;
  readonly isLocalEditable: any;
  readonly isMasterEditable: any;
  readonly isLocked: any;
  lock(preview?: any): any;
  unlock(preview?: any): any;
  readonly exportableInterface: any;
  readonly exportConfig: any;
  readonly layerEffectsInterface: any;
  readonly quickFX: any;
  readonly transformInterface: any;
  readonly transform: any;
  readonly visibilityInterface: any;
  readonly globalOpacity: any;
  readonly fillOpacity: any;
  readonly isVisible: any;
  readonly isVisibleInExport: any;
  readonly isVisibleInDomain: any;
  testVisibility(options?: any): any;
  readonly tagInterface: any;
  hasKey(key?: any): any;
  getValueForKey(key?: any): any;
  readonly isMarkAsDecoration: any;
  hasPredefinedKey(key?: any): any;
  getValueForPredefinedKey(key?: any): any;
  readonly spread: any;
  moveToFirstChild(childType?: any): any;
  moveToLastChild(childType?: any): any;
  moveToNextSibling(): any;
  moveToParent(): any;
  moveToPreviousSibling(): any;
  delete(): any;
  duplicate(transform?: any): any;
}

export class NodeCast extends HandleObject {
  constructor(handle?: any);
  setNodeHandler(callback?: any): any;
  setArtTextNodeHandler(callback?: any): any;
  setAdjustmentRasterNodeHandler(callback?: any): any;
  setColouredLogicalNodeHandler(callback?: any): any;
  setCurvePathTextNodeHandler(callback?: any): any;
  setCurvesAdjustmentRasterNodeHandler(callback?: any): any;
  setDocumentNodeHandler(callback?: any): any;
  setEmbeddedDocumentNodeHandler(callback?: any): any;
  setEnclosureRasterNodeHandler(callback?: any): any;
  setExposureAdjustmentRasterNodeHandler(callback?: any): any;
  setFilterRasterNodeHandler(callback?: any): any;
  setGaussianBlurFilterRasterNodeHandler(callback?: any): any;
  setBoxBlurFilterRasterNodeHandler(callback?: any): any;
  setBilateralBlurFilterRasterNodeHandler(callback?: any): any;
  setBloomFilterRasterNodeHandler(callback?: any): any;
  setMedianBlurFilterRasterNodeHandler(callback?: any): any;
  setDiffuseGlowFilterRasterNodeHandler(callback?: any): any;
  setFieldBlurFilterRasterNodeHandler(callback?: any): any;
  setDepthOfFieldFilterRasterNodeHandler(callback?: any): any;
  setLensBlurFilterRasterNodeHandler(callback?: any): any;
  setMaximumBlurFilterRasterNodeHandler(callback?: any): any;
  setMinimumBlurFilterRasterNodeHandler(callback?: any): any;
  setMotionBlurFilterRasterNodeHandler(callback?: any): any;
  setRadialBlurFilterRasterNodeHandler(callback?: any): any;
  setShadowsHighlightsFilterRasterNodeHandler(callback?: any): any;
  setBrightnessContrastAdjustmentRasterNodeHandler(callback?: any): any;
  setShadowsHighlightsAdjustmentRasterNodeHandler(callback?: any): any;
  setBlackAndWhiteAdjustmentRasterNodeHandler(callback?: any): any;
  setRecolourAdjustmentRasterNodeHandler(callback?: any): any;
  setPosteriseAdjustmentRasterNodeHandler(callback?: any): any;
  setSplitToningAdjustmentRasterNodeHandler(callback?: any): any;
  setInvertAdjustmentRasterNodeHandler(callback?: any): any;
  setThresholdAdjustmentRasterNodeHandler(callback?: any): any;
  setClarityFilterRasterNodeHandler(callback?: any): any;
  setUnsharpMaskFilterRasterNodeHandler(callback?: any): any;
  setHighPassFilterRasterNodeHandler(callback?: any): any;
  setDenoiseFilterRasterNodeHandler(callback?: any): any;
  setDiffuseFilterRasterNodeHandler(callback?: any): any;
  setDustAndScratchFilterRasterNodeHandler(callback?: any): any;
  setAddNoiseFilterRasterNodeHandler(callback?: any): any;
  setRippleFilterRasterNodeHandler(callback?: any): any;
  setTwirlFilterRasterNodeHandler(callback?: any): any;
  setSphericalFilterRasterNodeHandler(callback?: any): any;
  setPinchPunchFilterRasterNodeHandler(callback?: any): any;
  setPixelateFilterRasterNodeHandler(callback?: any): any;
  setHalftoneFilterRasterNodeHandler(callback?: any): any;
  setWhiteBalanceAdjustmentRasterNodeHandler(callback?: any): any;
  setColourBalanceAdjustmentRasterNodeHandler(callback?: any): any;
  setVibranceAdjustmentRasterNodeHandler(callback?: any): any;
  setNormalsAdjustmentRasterNodeHandler(callback?: any): any;
  setVignetteFilterRasterNodeHandler(callback?: any): any;
  setDefringeFilterRasterNodeHandler(callback?: any): any;
  setVoronoiFilterRasterNodeHandler(callback?: any): any;
  setSelectiveColourAdjustmentRasterNodeHandler(callback?: any): any;
  setHSLShiftAdjustmentRasterNodeHandler(callback?: any): any;
  setToneCompressionAdjustmentRasterNodeHandler(callback?: any): any;
  setToneStretchAdjustmentRasterNodeHandler(callback?: any): any;
  setFrameTextNodeHandler(callback?: any): any;
  setGroupNodeHandler(callback?: any): any;
  setImageNodeHandler(callback?: any): any;
  setLevelsAdjustmentRasterNodeHandler(callback?: any): any;
  setLogicalNodeHandler(callback?: any): any;
  setPatternRasterNodeHandler(callback?: any): any;
  setPhysicalNodeHandler(callback?: any): any;
  setPolyCurveNodeHandler(callback?: any): any;
  setPolyCurveTextNodeHandler(callback?: any): any;
  setRasterNodeHandler(callback?: any): any;
  setContainerNodeHandler(callback?: any): any;
  setShapeNodeHandler(callback?: any): any;
  setShapePathTextNodeHandler(callback?: any): any;
  setShapeTextNodeHandler(callback?: any): any;
  setSpreadNodeHandler(callback?: any): any;
  setTableTextNodeHandler(callback?: any): any;
  setTextNodeHandler(callback?: any): any;
  setVectorNodeHandler(callback?: any): any;
  exec(nodeHandle?: any): any;
}

export class NodeChildren extends NodeChildrenOnly {
  constructor(parentNodeHandle?: any, childType?: any, reversed?: any);
}

export class NodeChildrenOnly extends Collection {
  constructor(parentNodeHandle?: any, childType?: any, reversed?: any);
}

export class NodeDefinition extends HandleObject {
  constructor(handle?: any);
  readonly isNodeDefinition: any;
  transform: any;
  setTransform(xf?: any): this;
  userDescription: any;
  setUserDescription(desc?: any): this;
}

export class NodeDescendents extends Collection {
  constructor(rootNodeHandle?: any, childType?: any, reversed?: any);
}

export class NodeFactory {
  constructor();
  create(handle?: any): any;
}

export class NormalsAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isNormalsAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class NormalsAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isNormalsAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): NormalsAdjustmentRasterNodeDefinition;
  static createDefault(): NormalsAdjustmentRasterNodeDefinition;
}

export class PatternRasterNode extends RasterNode {
  constructor(handle?: any);
  readonly isPatternRasterNode: any;
  readonly mirror: any;
}

export class PatternRasterNodeDefinition extends RasterNodeDefinition {
  constructor(handle?: any);
  readonly isPatternRasterNodeDefinition: any;
  mirror: any;
  setMirror(value?: any): this;
  static createDefault(document?: any): PatternRasterNodeDefinition;
  static create(bitmap?: any, transform?: any, mirror?: any): PatternRasterNodeDefinition;
}

export class PhysicalNode extends Node {
  constructor(handle?: any);
  readonly isPhysicalNode: any;
  readonly canTransformWhileProtectingChildList: any;
}

export class PhysicalNodeDefinition extends NodeDefinition {
  constructor(handle?: any);
  readonly isPhysicalNodeDefinition: any;
}

export class PinchPunchFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isPinchPunchFilterRasterNode: any;
  readonly parameters: any;
}

export class PinchPunchFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isPinchPunchFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): PinchPunchFilterRasterNodeDefinition;
  static createDefault(document?: any): PinchPunchFilterRasterNodeDefinition;
}

export class PixelateFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isPixelateFilterRasterNode: any;
  readonly parameters: any;
}

export class PixelateFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isPixelateFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): PixelateFilterRasterNodeDefinition;
  static createDefault(): PixelateFilterRasterNodeDefinition;
}

export class PolyCurveNode extends VectorNode {
  constructor(handle?: any);
  readonly isPolyCurveNode: any;
  readonly artboardInterface: any;
  artboardEnabled: any;
  readonly artboardDescription: any;
  readonly artboardBaseBox: any;
  readonly artboardSpreadBaseBox: any;
  readonly artboardOrigin: any;
}

export class PolyCurveNodeDefinition extends VectorNodeDefinition {
  constructor(handle?: any);
  readonly isPolyCurveNodeDefinition: any;
  setCurves(curve?: any): this;
  curves: any;
  static create(curve?: any, brushFill?: any, lineStyle?: any, lineFill?: any, transparencyFill?: any): PolyCurveNodeDefinition;
  static createDefault(): PolyCurveNodeDefinition;
}

export class PolyCurveTextNode extends TextNode {
  constructor(handle?: any);
  readonly isPolyCurveTextNode: any;
}

export class PosteriseAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isPosteriseAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class PosteriseAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isPosteriseAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): PosteriseAdjustmentRasterNodeDefinition;
  static createDefault(): PosteriseAdjustmentRasterNodeDefinition;
}

export class RadialBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isRadialBlurFilterRasterNode: any;
  readonly parameters: any;
}

export class RadialBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isRadialBlurFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): RadialBlurFilterRasterNodeDefinition;
  static createDefault(document?: any): RadialBlurFilterRasterNodeDefinition;
}

export class RasterNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isRasterNode: any;
  readonly extendEmpty: any;
  readonly rasterInterface: any;
  readonly rasterWidth: any;
  readonly rasterHeight: any;
  readonly rasterFormat: any;
  readonly pixelSize: any;
  createCompatibleBitmap(copyContents?: any): any;
  createCompatibleBuffer(copyContents?: any): any;
  copyTo(dest?: any, destRect?: any, srcX?: any, srcY?: any): any;
}

export class RasterNodeDefinition extends PhysicalNodeDefinition {
  constructor(handle?: any);
  static create(format?: any): RasterNodeDefinition;
  readonly isRasterNodeDefinition: any;
  bitmap: any;
  setBitmap(bm?: any): this;
}

export class RecolourAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isRecolourAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class RecolourAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isRecolourAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): RecolourAdjustmentRasterNodeDefinition;
  static createDefault(): RecolourAdjustmentRasterNodeDefinition;
}

export class RippleFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isRippleFilterRasterNode: any;
  readonly parameters: any;
}

export class RippleFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isRippleFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): RippleFilterRasterNodeDefinition;
  static createDefault(document?: any): RippleFilterRasterNodeDefinition;
}

export class SelectiveColourAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isSelectiveColourAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class SelectiveColourAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isSelectiveColourAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): SelectiveColourAdjustmentRasterNodeDefinition;
  static createDefault(): SelectiveColourAdjustmentRasterNodeDefinition;
}

export class ShadowsHighlightsAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isShadowsHighlightsAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class ShadowsHighlightsAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isShadowsHighlightsAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ShadowsHighlightsAdjustmentRasterNodeDefinition;
  static createDefault(): ShadowsHighlightsAdjustmentRasterNodeDefinition;
}

export class ShadowsHighlightsFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isShadowsHighlightsFilterRasterNode: any;
  readonly parameters: any;
}

export class ShadowsHighlightsFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isShadowsHighlightsFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ShadowsHighlightsFilterRasterNodeDefinition;
  static createDefault(): ShadowsHighlightsFilterRasterNodeDefinition;
}

export class ShapeNode extends VectorNode {
  constructor(handle?: any);
  readonly isShapeNode: any;
  readonly artboardInterface: any;
  artboardEnabled: any;
  readonly artboardDescription: any;
  readonly artboardBaseBox: any;
  readonly artboardSpreadBaseBox: any;
  readonly artboardOrigin: any;
  readonly shapeInterface: any;
  readonly shape: any;
  readonly shapeType: any;
  readonly shapeBoundingBox: any;
}

export class ShapeNodeDefinition extends VectorNodeDefinition {
  constructor(handle?: any);
  readonly isShapeNodeDefinition: any;
  setShape(shape?: any): this;
  shape: any;
  setBoundingRectangle(rectangle?: any): this;
  boundingRectangle: any;
  static create(shape?: any, rectangle?: any, brushFill?: any, lineFill?: any, lineStyle?: any, transparencyFill?: any): ShapeNodeDefinition;
  static createDefault(): ShapeNodeDefinition;
}

export class ShapePathTextNode extends TextNode {
  constructor(handle?: any);
  readonly isShapePathTextNode: any;
  readonly shapeInterface: any;
  readonly shape: any;
  readonly shapeType: any;
  readonly shapeBoundingBox: any;
}

export class ShapeTextNode extends TextNode {
  constructor(handle?: any);
  readonly isShapeTextNode: any;
  readonly shapeInterface: any;
  readonly shape: any;
  readonly shapeType: any;
  readonly shapeBoundingBox: any;
}

export class SphericalFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isSphericalFilterRasterNode: any;
  readonly parameters: any;
}

export class SphericalFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isSphericalFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): SphericalFilterRasterNodeDefinition;
  static createDefault(document?: any): SphericalFilterRasterNodeDefinition;
}

export class SplitToningAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isSplitToningAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class SplitToningAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isSplitToningAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): SplitToningAdjustmentRasterNodeDefinition;
  static createDefault(): SplitToningAdjustmentRasterNodeDefinition;
}

export class SpreadNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isSpreadNode: any;
  readonly layers: NodeChildren;
  getSpreadExtents(options?: any): any;
  readonly physicalRootInterface: any;
  readonly physicalRootPropertiesInterface: any;
  readonly physicalRootProperties: any;
  readonly pageCount: any;
  readonly artboardCount: any;
  getArtboard(index?: any): any;
  enumerateArtboards(callback?: any): any;
  readonly artboards: any;
  readonly firstPageIndex: any;
  readonly lastPageIndex: any;
  readonly isFirstPage: any;
  getPageIndexOfPoint(pt?: any, relativeToSpread?: any): any;
  getPageIndexOfBox(box?: any, relativeToSpread?: any): any;
}

export class TableTextNode extends TextNode {
  constructor(handle?: any);
  readonly isTableTextNode: any;
}

export class TableTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isTableTextNodeDefinition: any;
  static create(box?: any, size?: any): TableTextNodeDefinition;
}

export class TextNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isTextNode: any;
  readonly artboardInterface: any;
  artboardEnabled: any;
  readonly artboardDescription: any;
  readonly artboardBaseBox: any;
  readonly artboardSpreadBaseBox: any;
  readonly artboardOrigin: any;
  readonly brushFillInterface: any;
  getBrushFillDescriptor(index?: any, obeyScaleWithObject?: any): any;
  setBrushFillDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): any;
  brushFillDescriptor: any;
  readonly hasBrushFill: any;
  readonly compoundOperationInterface: any;
  readonly compoundOperation: any;
  readonly curvesInterface: any;
  readonly polyCurve: any;
  readonly lineStyleInterface: any;
  lineStyleDescriptor: any;
  readonly lineStyleDescriptors: any;
  lineStyle: any;
  penFillDescriptor: any;
  readonly penFillDescriptors: any;
  readonly penFill: any;
  readonly hasPenFill: any;
  readonly isLineStyleVisible: any;
  lineWeight: any;
  lineWeightPts: any;
  lineType: any;
  lineCap: any;
  lineJoin: any;
  dashPhase: any;
  dashPattern: any;
  hasBalancedDashes: any;
  strokeAlignment: any;
  readonly storyInterface: any;
  getText(startPos?: any, maxLength?: any, format?: any): any;
  readonly text: any;
  readonly story: any;
  readonly storyRange: any;
  setText(str?: any): any;
  readonly textFrameInterface: any;
  readonly transparencyInterface: any;
  readonly transparencyFillDescriptor: any;
  readonly transparencyFill: any;
}

export class TextNodeDefinition extends PhysicalNodeDefinition {
  constructor(handle?: any);
  readonly isTextNodeDefinition: any;
}

export class ThresholdAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isThresholdAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class ThresholdAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isThresholdAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ThresholdAdjustmentRasterNodeDefinition;
  static createDefault(): ThresholdAdjustmentRasterNodeDefinition;
}

export class ToneCompressionAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isToneCompressionAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class ToneCompressionAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isToneCompressionAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ToneCompressionAdjustmentRasterNodeDefinition;
  static createDefault(): ToneCompressionAdjustmentRasterNodeDefinition;
}

export class ToneStretchAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isToneStretchAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class ToneStretchAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isToneStretchAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ToneStretchAdjustmentRasterNodeDefinition;
  static createDefault(): ToneStretchAdjustmentRasterNodeDefinition;
}

export class TwirlFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isTwirlFilterRasterNode: any;
  readonly parameters: any;
}

export class TwirlFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isTwirlFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): TwirlFilterRasterNodeDefinition;
  static createDefault(document?: any): TwirlFilterRasterNodeDefinition;
}

export class UnsharpMaskFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isUnsharpMaskFilterRasterNode: any;
  readonly parameters: any;
}

export class UnsharpMaskFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isUnsharpMaskFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): UnsharpMaskFilterRasterNodeDefinition;
  static createDefault(): UnsharpMaskFilterRasterNodeDefinition;
}

export class VectorNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isVectorNode: any;
  readonly canBeExpressedAsVectorClip: any;
  readonly brushFillInterface: any;
  getBrushFillDescriptor(index?: any, obeyScaleWithObject?: any): any;
  setBrushFillDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): any;
  brushFillDescriptor: any;
  readonly hasBrushFill: any;
  readonly compoundOperationInterface: any;
  readonly compoundOperation: any;
  readonly curvesInterface: any;
  readonly polyCurve: any;
  readonly lineStyleInterface: any;
  lineStyleDescriptor: any;
  readonly lineStyleDescriptors: any;
  lineStyle: any;
  penFillDescriptor: any;
  readonly penFillDescriptors: any;
  readonly penFill: any;
  readonly hasPenFill: any;
  readonly isLineStyleVisible: any;
  lineWeight: any;
  lineWeightPts: any;
  lineType: any;
  lineCap: any;
  lineJoin: any;
  dashPhase: any;
  dashPattern: any;
  hasBalancedDashes: any;
  strokeAlignment: any;
  readonly pictureFrameInterface: any;
  readonly pictureFrameEnabled: any;
  readonly pictureFrameDescription: any;
  readonly transparencyInterface: any;
  readonly transparencyFillDescriptor: any;
  readonly transparencyFill: any;
}

export class VectorNodeDefinition extends PhysicalNodeDefinition {
  constructor(handle?: any);
  readonly isVectorNodeDefinition: any;
  addBrushFillDescriptor(brushFillDescriptor?: any): this;
  addLineDescriptors(lineFillDescriptor?: any, lineStyleDescriptor?: any): this;
  setTransparencyDescriptor(transparencyDescriptor?: any): this;
  transparencyDescriptor: any;
  readonly brushFillDescriptorCount: any;
  getBrushFillDescriptor(index?: any): any;
  insertBrushFillDescriptor(brushFillDescriptor?: any, index?: any): this;
  setBrushFillDescriptor(brushFillDescriptor?: any, index?: any): this;
  removeBrushFillDescriptor(index?: any): this;
  currentBrushFillIndex: any;
  readonly lineDescriptorsCount: any;
  getLineDescriptors(index?: any): any;
  insertLineDescriptors(lineFillDescriptor?: any, lineStyleDescriptor?: any, index?: any): this;
  setLineDescriptors(lineFillDescriptor?: any, lineStyleDescriptor?: any, index?: any): this;
  removeLineDescriptors(index?: any): this;
  currentLineDescriptorsIndex: any;
}

export class VibranceAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isVibranceAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class VibranceAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isVibranceAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): VibranceAdjustmentRasterNodeDefinition;
  static createDefault(): VibranceAdjustmentRasterNodeDefinition;
}

export class VignetteFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isVignetteFilterRasterNode: any;
  readonly parameters: any;
}

export class VignetteFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isVignetteFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): VignetteFilterRasterNodeDefinition;
  static createDefault(): VignetteFilterRasterNodeDefinition;
}

export class VoronoiFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isVoronoiFilterRasterNode: any;
  readonly parameters: any;
}

export class VoronoiFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isVoronoiFilterRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): VoronoiFilterRasterNodeDefinition;
  static createDefault(): VoronoiFilterRasterNodeDefinition;
}

export class WhiteBalanceAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isWhiteBalanceAdjustmentRasterNode: any;
  readonly parameters: any;
}

export class WhiteBalanceAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isWhiteBalanceAdjustmentRasterNodeDefinition: any;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): WhiteBalanceAdjustmentRasterNodeDefinition;
  static createDefault(): WhiteBalanceAdjustmentRasterNodeDefinition;
}

export { BlackAndWhiteAdjustmentParameters } from 'affinity:dom';
export { BrightnessContrastAdjustmentParameters } from 'affinity:dom';
export { ColourBalanceAdjustmentParameters } from 'affinity:dom';
export { ColourBalanceValues } from 'affinity:dom';
export { ExposureAdjustmentParameters } from 'affinity:dom';
export { HSLShiftAdjustmentChannelParameters } from 'affinity:dom';
export { HSLShiftAdjustmentColourRange } from 'affinity:dom';
export { LevelsAdjustmentChannelParameters } from 'affinity:dom';
export { LevelsAdjustmentParameters } from 'affinity:dom';
export { NormalsAdjustmentParameters } from 'affinity:dom';
export { PosteriseAdjustmentParameters } from 'affinity:dom';
export { RecolourAdjustmentParameters } from 'affinity:dom';
export { ShadowsHighlightsAdjustmentParameters } from 'affinity:dom';
export { SelectiveColourAdjustmentParameters } from 'affinity:dom';
export { SplitToningAdjustmentParameters } from 'affinity:dom';
export { ThresholdAdjustmentParameters } from 'affinity:dom';
export { ToneCompressionAdjustmentParameters } from 'affinity:dom';
export { ToneStretchAdjustmentParameters } from 'affinity:dom';
export { VibranceAdjustmentParameters } from 'affinity:dom';
export { WhiteBalanceAdjustmentParameters } from 'affinity:dom';
export { AddNoiseFilterParameters } from 'affinity:dom';
export { BilateralBlurFilterParameters } from 'affinity:dom';
export { BloomFilterParameters } from 'affinity:dom';
export { BoxBlurFilterParameters } from 'affinity:dom';
export { ClarityFilterParameters } from 'affinity:dom';
export { DefringeFilterParameters } from 'affinity:dom';
export { DenoiseFilterParameters } from 'affinity:dom';
export { DiffuseFilterParameters } from 'affinity:dom';
export { DiffuseGlowFilterParameters } from 'affinity:dom';
export { DustAndScratchFilterParameters } from 'affinity:dom';
export { EllipticalDepthOfFieldParameters } from 'affinity:dom';
export { FieldBlurItemParameters } from 'affinity:dom';
export { GaussianBlurFilterParameters } from 'affinity:dom';
export { HalftoneFilterParameters } from 'affinity:dom';
export { ShadowsHighlightsFilterParameters } from 'affinity:dom';
export { HighPassFilterParameters } from 'affinity:dom';
export { LensBlurFilterParameters } from 'affinity:dom';
export { MedianBlurFilterParameters } from 'affinity:dom';
export { MaximumBlurFilterParameters } from 'affinity:dom';
export { MinimumBlurFilterParameters } from 'affinity:dom';
export { MotionBlurFilterParameters } from 'affinity:dom';
export { PinchPunchFilterParameters } from 'affinity:dom';
export { PixelateFilterParameters } from 'affinity:dom';
export { RadialBlurFilterParameters } from 'affinity:dom';
export { RippleFilterParameters } from 'affinity:dom';
export { SphericalFilterParameters } from 'affinity:dom';
export { TiltShiftDepthOfFieldParameters } from 'affinity:dom';
export { TwirlFilterParameters } from 'affinity:dom';
export { UnsharpMaskFilterParameters } from 'affinity:dom';
export { VignetteFilterParameters } from 'affinity:dom';
export { VoronoiFilterParameters } from 'affinity:dom';
export function createTypedNode(handle?: any): any;
export { AddNoiseType } from 'affinity:dom';
export { ColourSpaceType } from 'affinity:colours';
export { DepthOfFieldMode } from 'affinity:dom';
export { PageBoundingBoxType } from 'affinity:dom';
export { RasterExtendType } from 'affinity:raster';
export { RasterFormat } from 'affinity:raster';
export { RasterResamplerType } from 'affinity:raster';
export { ShadowsHighlightsVersion } from 'affinity:dom';
export { SelectiveColour } from 'affinity:dom';
export { TonalRangeType } from 'affinity:dom';
export { ToneCompressionMethod } from 'affinity:dom';
export { ToneStretchMethod } from 'affinity:dom';
export { BloomMethod } from 'affinity:dom';
export { HalftoneScreenType } from 'affinity:dom';
export { HalftoneDotType } from 'affinity:dom';
export { NodeChildType } from 'affinity:dom';
export const getNodeSiblings: any;
export const getNodeChildren: any;
export const getNodesRecursive: any;
export const getNodeChildrenRecursive: any;
