// Auto-generated by tools/generate_types.py. Do not edit.

import { ArtboardInterface } from '/artboardinterface';
import { BaseBoxInterface } from '/baseboxinterface';
import { BlendModeInterface } from '/blendmodeinterface';
import { BrushFillInterface } from '/brushfillinterface';
import { Collection } from '/collection';
import { Colour } from '/colours';
import { CompoundOperationInterface } from '/compoundoperationinterface';
import { CurvesInterface } from '/curvesinterface';
import { DescriptionInterface } from '/descriptioninterface';
import { EditabilityInterface } from '/editabilityinterface';
import { ExportableInterface } from '/exportableinterface';
import { FillDescriptor } from '/fills';
import { HandleObject } from '/handleobject';
import { ImageResourceInterface } from '/imageresourceinterface';
import { LayerEffectsInterface } from '/layereffectsinterface';
import { LineStyleInterface } from '/linestyleinterface';
import { LoadDocumentOptions } from '/document';
import { PhysicalRootInterface } from '/physicalrootinterface';
import { PhysicalRootPropertiesInterface } from '/physicalrootpropertiesinterface';
import { PictureFrameInterface } from '/pictureframeinterface';
import { PolyCurve } from '/geometry';
import { RasterInterface } from '/rasterinterface';
import { RasterObject } from '/rasterobject';
import { Selectable } from '/selectable';
import { Shape } from '/shapes';
import { ShapeInterface } from '/shapeinterface';
import { Spline } from '/geometry';
import { StoryInterface } from '/storyinterface';
import { TagInterface } from '/taginterface';
import { TextFrameInterface } from '/textframeinterface';
import { TransformInterface } from '/transforminterface';
import { TransparencyInterface } from '/transparencyinterface';
import { VisibilityInterface } from '/visibilityinterface';
import { AntialiasingMode } from 'affinity:dom';
import { BlendMode } from 'affinity:common';
import { ColourSpaceType } from 'affinity:colours';
import { CompoundOperation } from 'affinity:dom';
import { LineCap } from 'affinity:linestyles';
import { LineJoin } from 'affinity:linestyles';
import { LineType } from 'affinity:linestyles';
import { PageBoundingBoxType } from 'affinity:dom';
import { RasterFormat } from 'affinity:raster';
import { ShapeType } from 'affinity:geometry';
import { StoryIoFormat } from 'affinity:story';
import { StrokeAlignment } from 'affinity:linestyles';

export class AddNoiseFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isAddNoiseFilterRasterNode: boolean;
  readonly parameters: any;
}

export class AddNoiseFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isAddNoiseFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): AddNoiseFilterRasterNodeDefinition;
  static createDefault(): AddNoiseFilterRasterNodeDefinition;
}

export class AdjustmentRasterNode extends EnclosureRasterNode {
  constructor(handle?: any);
  readonly isAdjustmentRasterNode: boolean;
}

export class AdjustmentRasterNodeDefinition extends EnclosureRasterNodeDefinition {
  constructor(handle?: any);
  readonly isAdjustmentRasterNodeDefinition: boolean;
}

export class ArtTextNode extends TextNode {
  constructor(handle?: any);
  readonly isArtTextNode: boolean;
}

export class ArtTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isArtTextNodeDefinition: boolean;
  static createFromStoryBuilder(position?: any, storyBuilder?: any): ArtTextNodeDefinition;
}

export class BilateralBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isBilateralBlurFilterRasterNode: boolean;
  readonly parameters: any;
}

export class BilateralBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBilateralBlurFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): BilateralBlurFilterRasterNodeDefinition;
  static createDefault(): BilateralBlurFilterRasterNodeDefinition;
}

export class BlackAndWhiteAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isBlackAndWhiteAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class BlackAndWhiteAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBlackAndWhiteAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): BlackAndWhiteAdjustmentRasterNodeDefinition;
  static createDefault(): BlackAndWhiteAdjustmentRasterNodeDefinition;
}

export class BloomFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isBloomFilterRasterNode: boolean;
  readonly parameters: any;
}

export class BloomFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBloomFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): BloomFilterRasterNodeDefinition;
  static createDefault(): BloomFilterRasterNodeDefinition;
}

export class BoxBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isBoxBlurFilterRasterNode: boolean;
  readonly parameters: any;
}

export class BoxBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBoxBlurFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): BoxBlurFilterRasterNodeDefinition;
  static createDefault(): BoxBlurFilterRasterNodeDefinition;
}

export class BrightnessContrastAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isBrightnessContrastAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class BrightnessContrastAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isBrightnessContrastAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): BrightnessContrastAdjustmentRasterNodeDefinition;
  static createDefault(): BrightnessContrastAdjustmentRasterNodeDefinition;
}

export class ClarityFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isClarityFilterRasterNode: boolean;
  readonly parameters: any;
}

export class ClarityFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isClarityFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ClarityFilterRasterNodeDefinition;
  static createDefault(): ClarityFilterRasterNodeDefinition;
}

export class ColourBalanceAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isColourBalanceAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class ColourBalanceAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isColourBalanceAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ColourBalanceAdjustmentRasterNodeDefinition;
  static createDefault(): ColourBalanceAdjustmentRasterNodeDefinition;
}

export class ColouredLogicalNode extends LogicalNode {
  constructor(handle?: any);
  readonly isColouredLogicalNode: boolean;
  readonly layerColour: Colour;
}

export class ColouredLogicalNodeDefinition extends LogicalNodeDefinition {
  constructor(handle?: any);
  readonly isColouredLogicalNodeDefinition: boolean;
}

export class ContainerNode extends ColouredLogicalNode {
  constructor(handle?: any);
  readonly isContainerNode: boolean;
}

export class ContainerNodeDefinition extends ColouredLogicalNodeDefinition {
  constructor(handle?: any);
  static createDefault(): ContainerNodeDefinition;
  static create(name?: any): ContainerNodeDefinition;
}

export class CurvePathTextNode extends TextNode {
  constructor(handle?: any);
  readonly isCurvePathTextNode: boolean;
}

export class CurvesAdjustmentParameters extends HandleObject {
  constructor(handle?: any);
  readonly isCurvesAdjustmentParameters: boolean;
  masterSpline: Spline;
  setChannelSpline(channel?: any, channelSpline?: any): any;
  min: any;
  max: any;
  getChannelSpline(channel?: any): Spline;
  static create(): CurvesAdjustmentParameters;
}

export class CurvesAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isCurvesAdjustmentRasterNode: boolean;
  readonly parameters: CurvesAdjustmentParameters;
  readonly colourSpace: ColourSpaceType;
}

export class CurvesAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isCurvesAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  colourSpace: ColourSpaceType;
  setColourSpace(csType?: ColourSpaceType): this;
  static create(params?: any, colourSpace?: any): CurvesAdjustmentRasterNodeDefinition;
  static createDefault(document?: any): CurvesAdjustmentRasterNodeDefinition;
}

export class DefringeFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDefringeFilterRasterNode: boolean;
  readonly parameters: any;
}

export class DefringeFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDefringeFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): DefringeFilterRasterNodeDefinition;
  static createDefault(): DefringeFilterRasterNodeDefinition;
}

export class DenoiseFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDenoiseFilterRasterNode: boolean;
  readonly parameters: any;
}

export class DenoiseFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDenoiseFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): DenoiseFilterRasterNodeDefinition;
  static createDefault(): DenoiseFilterRasterNodeDefinition;
}

export class DepthOfFieldFilterParameters extends HandleObject {
  constructor(handle?: any);
  readonly isDepthOfFieldFilterParameters: boolean;
  readonly mode: any;
  radius: any;
  vibrance: any;
  clarity: any;
  ellipticalParams: any;
  tiltShiftParams: any;
  static create(): DepthOfFieldFilterParameters;
}

export class DepthOfFieldFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDepthOfFieldFilterRasterNode: boolean;
  readonly parameters: DepthOfFieldFilterParameters;
}

export class DepthOfFieldFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDepthOfFieldFilterRasterNodeDefinition: boolean;
  parameters: DepthOfFieldFilterParameters;
  setParameters(parameters?: DepthOfFieldFilterParameters): this;
  static create(params?: any): DepthOfFieldFilterRasterNodeDefinition;
  static createDefault(doc?: any): DepthOfFieldFilterRasterNodeDefinition;
}

export class DiffuseFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDiffuseFilterRasterNode: boolean;
  readonly parameters: any;
}

export class DiffuseFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDiffuseFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): DiffuseFilterRasterNodeDefinition;
  static createDefault(): DiffuseFilterRasterNodeDefinition;
}

export class DiffuseGlowFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDiffuseGlowFilterRasterNode: boolean;
  readonly parameters: any;
}

export class DiffuseGlowFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDiffuseGlowFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): DiffuseGlowFilterRasterNodeDefinition;
  static createDefault(): DiffuseGlowFilterRasterNodeDefinition;
}

export class DocumentNode extends LogicalNode {
  constructor(handle?: any);
  readonly isDocumentNode: boolean;
  readonly pageCount: number;
  readonly spreadCount: number;
}

export class DustAndScratchFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isDustAndScratchFilterRasterNode: boolean;
  readonly parameters: any;
}

export class DustAndScratchFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isDustAndScratchFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): DustAndScratchFilterRasterNodeDefinition;
  static createDefault(): DustAndScratchFilterRasterNodeDefinition;
}

export class EmbeddedDocumentNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isEmbeddedDocumentNode: boolean;
  readonly selectedSpreadId: number;
  readonly selectedArtboardId: number;
  readonly embeddedDocumentHasSpreads: any;
  readonly embeddedDocumentHasArtboards: any;
  readonly embeddedDocumentHasPageBoundingBoxes: any;
  readonly embeddedDocumentHasLayers: any;
  readonly selectedArtboardOffset: any;
  readonly pageBoundingBoxType: PageBoundingBoxType;
  readonly PDFPassthrough: any;
  readonly canSetPDFPassthrough: boolean;
  readonly rasterDPI: any;
  readonly originalHostDPI: any;
  readonly isAffinityFile: boolean;
  readonly canMakeLinked: boolean;
  readonly canEditEmbeddedImage: boolean;
  readonly loadDocumentOptions: LoadDocumentOptions;
  readonly shouldAllowSelectDocument: boolean;
  readonly isArtboardSelected: boolean;
  readonly isArtboardDoc: boolean;
  readonly needsPassword: any;
  enumerateSpreads(includeMasters?: any, func?: any): any;
  enumerateArtboards(func?: any): any;
  enumeratePageBoundingBoxes(func?: any): any;
  enumerateLayerVisibilities(func?: any): any;
  getSpreads(includeMasters?: any): any;
  readonly artboards: any;
  readonly pageBoundingBoxes: any;
  readonly layerVisibilities: any;
  readonly imageResourceInterface: ImageResourceInterface;
  readonly imageFilePath: string;
  readonly imageFileSize: any;
  readonly imageFileType: any;
  readonly imageFileTypeName: string;
  readonly transparencyInterface: TransparencyInterface;
  readonly transparencyFillDescriptor: any;
  readonly transparencyFill: any;
}

export class EnclosureRasterNode extends RasterNode {
  constructor(handle?: any);
  readonly isEnclosureRasterNode: boolean;
}

export class EnclosureRasterNodeDefinition extends RasterNodeDefinition {
  constructor(handle?: any);
  readonly isEnclosureRasterNodeDefinition: boolean;
}

export class ExposureAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isExposureAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class ExposureAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isExposureAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  static create(params?: any): ExposureAdjustmentRasterNodeDefinition;
  static createDefault(): ExposureAdjustmentRasterNodeDefinition;
}

export class FieldBlurFilterParameters extends HandleObject {
  constructor(handle?: any);
  readonly isFieldBlurFilterParameters: boolean;
  readonly blurItemCount: number;
  getBlurItem(index?: any): any;
  addBlurItem(itemParams?: any): any;
  deleteBlurItem(index?: any): any;
  globalRadius: any;
  static create(): FieldBlurFilterParameters;
}

export class FieldBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isFieldBlurFilterRasterNode: boolean;
  readonly parameters: FieldBlurFilterParameters;
}

export class FieldBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isFieldBlurFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): FieldBlurFilterRasterNodeDefinition;
  static createDefault(doc?: any): FieldBlurFilterRasterNodeDefinition;
}

export class FilterRasterNode extends EnclosureRasterNode {
  constructor(handle?: any);
  readonly isFilterRasterNode: boolean;
  readonly preserveAlpha: any;
}

export class FilterRasterNodeDefinition extends EnclosureRasterNodeDefinition {
  constructor(handle?: any);
  readonly isFilterRasterNodeDefinition: boolean;
  preserveAlpha: any;
  setPreserveAlpha(value?: any): this;
}

export class FrameTextNode extends TextNode {
  constructor(handle?: any);
  readonly isFrameTextNode: boolean;
}

export class FrameTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isFrameTextNodeDefinition: boolean;
  static createFromStoryBuilder(frameBox?: any, storyBuilder?: any): FrameTextNodeDefinition;
}

export class GaussianBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isGaussianBlurFilterRasterNode: boolean;
  readonly parameters: any;
}

export class GaussianBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isGaussianBlurFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): GaussianBlurFilterRasterNodeDefinition;
  static createDefault(): GaussianBlurFilterRasterNodeDefinition;
}

export class GroupNode extends LogicalNode {
  constructor(handle?: any);
  readonly isGroupNode: boolean;
}

export class GroupNodeDefinition extends LogicalNodeDefinition {
  constructor(handle?: any);
  readonly isGroupNodeDefinition: boolean;
}

export class HSLShiftAdjustmentParameters extends HandleObject {
  constructor(handle?: any);
  readonly isHSLShiftAdjustmentParameters: boolean;
  masterParameters: any;
  setChannelParameters(channel?: any, channelParameter?: any): any;
  setChannelColourRange(channel?: any, colourRange?: any): any;
  useHSV: any;
  getChannelParameters(channel?: any): any;
  getChannelColourRange(channel?: any): any;
  static create(): HSLShiftAdjustmentParameters;
}

export class HSLShiftAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isHSLShiftAdjustmentRasterNode: boolean;
  readonly parameters: HSLShiftAdjustmentParameters;
}

export class HSLShiftAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isHSLShiftAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  static create(parameters?: any): HSLShiftAdjustmentRasterNodeDefinition;
  static createDefault(): HSLShiftAdjustmentRasterNodeDefinition;
}

export class HalftoneFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isHalftoneFilterRasterNode: boolean;
  readonly parameters: any;
}

export class HalftoneFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isHalftoneFilterRasterNodeDefinition: boolean;
  parameters: any;
  static create(params?: any): HalftoneFilterRasterNodeDefinition;
  static createDefault(): HalftoneFilterRasterNodeDefinition;
}

export class HighPassFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isHighPassFilterRasterNode: boolean;
  readonly parameters: any;
}

export class HighPassFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isHighPassFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): HighPassFilterRasterNodeDefinition;
  static createDefault(): HighPassFilterRasterNodeDefinition;
}

export class ImageNode extends VectorNode {
  constructor(handle?: any);
  readonly isImageNode: boolean;
  readonly extendType: any;
  readonly upsamplerType: any;
  readonly stockURL: any;
  readonly stockUserProfileURL: any;
  readonly stockAuthor: any;
  readonly lastRendered: any;
  readonly bitmapBrushFillDescriptor: any;
  readonly isKOnly: boolean;
  readonly imageResourceInterface: ImageResourceInterface;
  readonly imageFilePath: string;
  readonly imageFileSize: any;
  readonly imageFileType: any;
  readonly imageFileTypeName: string;
  readonly rasterInterface: RasterInterface;
  readonly rasterWidth: number;
  readonly rasterHeight: number;
  readonly rasterFormat: RasterFormat;
  readonly pixelSize: any;
  createCompatibleBitmap(copyContents?: any): any;
  createCompatibleBuffer(copyContents?: any): any;
  copyTo(dest?: any, destRect?: any, srcX?: any, srcY?: any): any;
}

export class ImageNodeDefinition extends VectorNodeDefinition {
  constructor(handle?: any);
  static create(format?: any): ImageNodeDefinition;
  readonly isImageNodeDefinition: boolean;
  bitmap: RasterObject;
  setBitmap(bm?: RasterObject): this;
}

export class InvertAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isInvertAdjustmentRasterNode: boolean;
}

export class InvertAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isInvertAdjustmentRasterNodeDefinition: boolean;
  static create(): InvertAdjustmentRasterNodeDefinition;
}

export class LensBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isLensBlurFilterRasterNode: boolean;
  readonly parameters: any;
}

export class LensBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isLensBlurFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): LensBlurFilterRasterNodeDefinition;
  static createDefault(): LensBlurFilterRasterNodeDefinition;
}

export class LevelsAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isLevelsAdjustmentRasterNode: boolean;
  readonly parameters: any;
  readonly colourSpace: ColourSpaceType;
}

export class LevelsAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isLevelsAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  colourSpace: ColourSpaceType;
  setColourSpace(csType?: ColourSpaceType): this;
  static create(params?: any, colourSpace?: any): LevelsAdjustmentRasterNodeDefinition;
  static createDefault(document?: any): LevelsAdjustmentRasterNodeDefinition;
}

export class LogicalNode extends Node {
  constructor(handle?: any);
  readonly isLogicalNode: boolean;
  readonly hasNonMaskChildren: boolean;
  readonly hasNonMaskOrAdjustmentChildren: boolean;
  readonly brushFillInterface: BrushFillInterface;
  getBrushFillDescriptor(index?: any, obeyScaleWithObject?: boolean): any;
  setBrushFillDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): any;
  brushFillDescriptor: any;
  readonly hasBrushFill: boolean;
  readonly lineStyleInterface: LineStyleInterface;
  lineStyleDescriptor: any;
  readonly lineStyleDescriptors: any;
  lineStyle: any;
  penFillDescriptor: any;
  readonly penFillDescriptors: any;
  readonly penFill: any;
  readonly hasPenFill: boolean;
  readonly isLineStyleVisible: boolean;
  lineWeight: any;
  lineWeightPts: any;
  lineType: LineType;
  lineCap: LineCap;
  lineJoin: LineJoin;
  dashPhase: any;
  dashPattern: any;
  hasBalancedDashes: boolean;
  strokeAlignment: StrokeAlignment;
  readonly transparencyInterface: TransparencyInterface;
  readonly transparencyFillDescriptor: any;
  readonly transparencyFill: any;
}

export class LogicalNodeDefinition extends NodeDefinition {
  constructor(handle?: any);
  readonly isLogicalNodeDefinition: boolean;
}

export class MaximumBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isMaximumBlurFilterRasterNode: boolean;
  readonly parameters: any;
}

export class MaximumBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isMaximumBlurFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): MaximumBlurFilterRasterNodeDefinition;
  static createDefault(): MaximumBlurFilterRasterNodeDefinition;
}

export class MedianBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isMedianBlurFilterRasterNode: boolean;
  readonly parameters: any;
}

export class MedianBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isMedianBlurFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): MedianBlurFilterRasterNodeDefinition;
  static createDefault(): MedianBlurFilterRasterNodeDefinition;
}

export class MinimumBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isMinimumBlurFilterRasterNode: boolean;
  readonly parameters: any;
}

export class MinimumBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isMinimumBlurFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): MinimumBlurFilterRasterNodeDefinition;
  static createDefault(): MinimumBlurFilterRasterNodeDefinition;
}

export class MotionBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isMotionBlurFilterRasterNode: boolean;
  readonly parameters: any;
}

export class MotionBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isMotionBlurFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): MotionBlurFilterRasterNodeDefinition;
  static createDefault(): MotionBlurFilterRasterNodeDefinition;
}

export class Node extends Selectable {
  constructor(handle?: any);
  readonly isNode: boolean;
  isSameNode(otherNode?: any): boolean;
  readonly document: any;
  readonly selfSelection: any;
  readonly nextSibling: Node;
  readonly previousSibling: Node;
  readonly parent: Node;
  readonly firstChild: any;
  readonly lastChild: any;
  getFirstChild(nodeChildType?: any): Node;
  getLastChild(nodeChildType?: any): Node;
  readonly children: NodeChildren;
  readonly enclosures: NodeChildren;
  getSpreadBaseBox(includeClips?: boolean): any;
  readonly spreadBaseBox: any;
  readonly baseToSpreadTransform: any;
  readonly localToSpreadTransform: any;
  readonly spreadToBaseTransform: any;
  getLineBox(includeClips?: boolean): any;
  getTransformedLineBox(transform?: any, scalarTransform?: any, includeClips?: boolean): any;
  getSpreadVisibleBox(includeParentEffects?: boolean): any;
  getLocalVisibleBox(): any;
  getExactSpreadBaseBox(): any;
  getExactSpreadVisibleBox(includeParentEffects?: any, considerParentClips?: any): any;
  getContentExtentsBox(includeInvisible?: any, includeOffCurvePoints?: any): any;
  getContentExtentsBoxOfChildren(includeInvisible?: any, includeOffCurvePoints?: any): any;
  readonly lineBox: any;
  readonly spreadVisibleBox: any;
  readonly localVisibleBox: any;
  readonly exactSpreadBaseBox: any;
  readonly baseBoxInterface: BaseBoxInterface;
  readonly baseBox: any;
  readonly constrainingBaseBox: any;
  readonly bmIFace: any;
  readonly blendModeInterface: BlendModeInterface;
  readonly blendMode: BlendMode;
  readonly blendOptions: any;
  readonly antialiasingMode: AntialiasingMode;
  readonly descriptionInterface: DescriptionInterface;
  readonly description: string;
  userDescription: string;
  readonly defaultDescription: string;
  readonly defaultDescriptionForDisplay: any;
  tagColour: any;
  readonly editabilityInterface: EditabilityInterface;
  readonly isEditable: boolean;
  readonly isLocalEditable: boolean;
  readonly isMasterEditable: boolean;
  readonly isLocked: boolean;
  lock(preview?: any): any;
  unlock(preview?: any): any;
  readonly exportableInterface: ExportableInterface;
  readonly exportConfig: any;
  readonly layerEffectsInterface: LayerEffectsInterface;
  readonly quickFX: any;
  readonly transformInterface: TransformInterface;
  readonly transform: any;
  readonly visibilityInterface: VisibilityInterface;
  readonly globalOpacity: any;
  readonly fillOpacity: any;
  readonly isVisible: boolean;
  readonly isVisibleInExport: boolean;
  readonly isVisibleInDomain: boolean;
  testVisibility(options?: any): any;
  readonly tagInterface: TagInterface;
  hasKey(key?: any): boolean;
  getValueForKey(key?: any): any;
  readonly isMarkAsDecoration: boolean;
  hasPredefinedKey(key?: any): boolean;
  getValueForPredefinedKey(key?: any): any;
  readonly spread: any;
  moveToFirstChild(childType?: any): any;
  moveToLastChild(childType?: any): any;
  moveToNextSibling(): any;
  moveToParent(): any;
  moveToPreviousSibling(): any;
  delete(): any;
  duplicate(transform?: any): any;
}

export class NodeCast extends HandleObject {
  constructor(handle?: any);
  setNodeHandler(callback?: (...args: any[]) => any): any;
  setArtTextNodeHandler(callback?: (...args: any[]) => any): any;
  setAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setColouredLogicalNodeHandler(callback?: (...args: any[]) => any): any;
  setCurvePathTextNodeHandler(callback?: (...args: any[]) => any): any;
  setCurvesAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDocumentNodeHandler(callback?: (...args: any[]) => any): any;
  setEmbeddedDocumentNodeHandler(callback?: (...args: any[]) => any): any;
  setEnclosureRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setExposureAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setGaussianBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setBoxBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setBilateralBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setBloomFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setMedianBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDiffuseGlowFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setFieldBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDepthOfFieldFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setLensBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setMaximumBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setMinimumBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setMotionBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setRadialBlurFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setShadowsHighlightsFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setBrightnessContrastAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setShadowsHighlightsAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setBlackAndWhiteAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setRecolourAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setPosteriseAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setSplitToningAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setInvertAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setThresholdAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setClarityFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setUnsharpMaskFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setHighPassFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDenoiseFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDiffuseFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDustAndScratchFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setAddNoiseFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setRippleFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setTwirlFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setSphericalFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setPinchPunchFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setPixelateFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setHalftoneFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setWhiteBalanceAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setColourBalanceAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setVibranceAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setNormalsAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setVignetteFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setDefringeFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setVoronoiFilterRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setSelectiveColourAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setHSLShiftAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setToneCompressionAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setToneStretchAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setFrameTextNodeHandler(callback?: (...args: any[]) => any): any;
  setGroupNodeHandler(callback?: (...args: any[]) => any): any;
  setImageNodeHandler(callback?: (...args: any[]) => any): any;
  setLevelsAdjustmentRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setLogicalNodeHandler(callback?: (...args: any[]) => any): any;
  setPatternRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setPhysicalNodeHandler(callback?: (...args: any[]) => any): any;
  setPolyCurveNodeHandler(callback?: (...args: any[]) => any): any;
  setPolyCurveTextNodeHandler(callback?: (...args: any[]) => any): any;
  setRasterNodeHandler(callback?: (...args: any[]) => any): any;
  setContainerNodeHandler(callback?: (...args: any[]) => any): any;
  setShapeNodeHandler(callback?: (...args: any[]) => any): any;
  setShapePathTextNodeHandler(callback?: (...args: any[]) => any): any;
  setShapeTextNodeHandler(callback?: (...args: any[]) => any): any;
  setSpreadNodeHandler(callback?: (...args: any[]) => any): any;
  setTableTextNodeHandler(callback?: (...args: any[]) => any): any;
  setTextNodeHandler(callback?: (...args: any[]) => any): any;
  setVectorNodeHandler(callback?: (...args: any[]) => any): any;
  exec(nodeHandle?: any): any;
}

export class NodeChildren extends NodeChildrenOnly {
  constructor(parentNodeHandle?: any, childType?: any, reversed?: any);
}

export class NodeChildrenOnly extends Collection {
  constructor(parentNodeHandle?: any, childType?: any, reversed?: any);
}

export class NodeDefinition extends HandleObject {
  constructor(handle?: any);
  readonly isNodeDefinition: boolean;
  transform: any;
  setTransform(xf?: any): this;
  userDescription: string;
  setUserDescription(desc?: string): this;
}

export class NodeDescendents extends Collection {
  constructor(rootNodeHandle?: any, childType?: any, reversed?: any);
}

export class NodeFactory {
  constructor();
  create(handle?: any): any;
}

export class NormalsAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isNormalsAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class NormalsAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isNormalsAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): NormalsAdjustmentRasterNodeDefinition;
  static createDefault(): NormalsAdjustmentRasterNodeDefinition;
}

export class PatternRasterNode extends RasterNode {
  constructor(handle?: any);
  readonly isPatternRasterNode: boolean;
  readonly mirror: any;
}

export class PatternRasterNodeDefinition extends RasterNodeDefinition {
  constructor(handle?: any);
  readonly isPatternRasterNodeDefinition: boolean;
  mirror: any;
  setMirror(value?: any): this;
  static createDefault(document?: any): PatternRasterNodeDefinition;
  static create(bitmap?: any, transform?: any, mirror?: any): PatternRasterNodeDefinition;
}

export class PhysicalNode extends Node {
  constructor(handle?: any);
  readonly isPhysicalNode: boolean;
  readonly canTransformWhileProtectingChildList: boolean;
}

export class PhysicalNodeDefinition extends NodeDefinition {
  constructor(handle?: any);
  readonly isPhysicalNodeDefinition: boolean;
}

export class PinchPunchFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isPinchPunchFilterRasterNode: boolean;
  readonly parameters: any;
}

export class PinchPunchFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isPinchPunchFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): PinchPunchFilterRasterNodeDefinition;
  static createDefault(document?: any): PinchPunchFilterRasterNodeDefinition;
}

export class PixelateFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isPixelateFilterRasterNode: boolean;
  readonly parameters: any;
}

export class PixelateFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isPixelateFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(params?: any): PixelateFilterRasterNodeDefinition;
  static createDefault(): PixelateFilterRasterNodeDefinition;
}

export class PolyCurveNode extends VectorNode {
  constructor(handle?: any);
  readonly isPolyCurveNode: boolean;
  readonly artboardInterface: ArtboardInterface;
  artboardEnabled: any;
  readonly artboardDescription: string;
  readonly artboardBaseBox: any;
  readonly artboardSpreadBaseBox: any;
  readonly artboardOrigin: any;
}

export class PolyCurveNodeDefinition extends VectorNodeDefinition {
  constructor(handle?: any);
  readonly isPolyCurveNodeDefinition: boolean;
  setCurves(curve?: PolyCurve): this;
  curves: PolyCurve;
  static create(curve?: any, brushFill?: any, lineStyle?: any, lineFill?: any, transparencyFill?: any): PolyCurveNodeDefinition;
  static createDefault(): PolyCurveNodeDefinition;
}

export class PolyCurveTextNode extends TextNode {
  constructor(handle?: any);
  readonly isPolyCurveTextNode: boolean;
}

export class PosteriseAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isPosteriseAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class PosteriseAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isPosteriseAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): PosteriseAdjustmentRasterNodeDefinition;
  static createDefault(): PosteriseAdjustmentRasterNodeDefinition;
}

export class RadialBlurFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isRadialBlurFilterRasterNode: boolean;
  readonly parameters: any;
}

export class RadialBlurFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isRadialBlurFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): RadialBlurFilterRasterNodeDefinition;
  static createDefault(document?: any): RadialBlurFilterRasterNodeDefinition;
}

export class RasterNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isRasterNode: boolean;
  readonly extendEmpty: boolean;
  readonly rasterInterface: RasterInterface;
  readonly rasterWidth: number;
  readonly rasterHeight: number;
  readonly rasterFormat: RasterFormat;
  readonly pixelSize: any;
  createCompatibleBitmap(copyContents?: any): any;
  createCompatibleBuffer(copyContents?: any): any;
  copyTo(dest?: any, destRect?: any, srcX?: any, srcY?: any): any;
}

export class RasterNodeDefinition extends PhysicalNodeDefinition {
  constructor(handle?: any);
  static create(format?: any): RasterNodeDefinition;
  readonly isRasterNodeDefinition: boolean;
  bitmap: RasterObject;
  setBitmap(bm?: RasterObject): this;
}

export class RecolourAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isRecolourAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class RecolourAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isRecolourAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): RecolourAdjustmentRasterNodeDefinition;
  static createDefault(): RecolourAdjustmentRasterNodeDefinition;
}

export class RippleFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isRippleFilterRasterNode: boolean;
  readonly parameters: any;
}

export class RippleFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isRippleFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): RippleFilterRasterNodeDefinition;
  static createDefault(document?: any): RippleFilterRasterNodeDefinition;
}

export class SelectiveColourAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isSelectiveColourAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class SelectiveColourAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isSelectiveColourAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): SelectiveColourAdjustmentRasterNodeDefinition;
  static createDefault(): SelectiveColourAdjustmentRasterNodeDefinition;
}

export class ShadowsHighlightsAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isShadowsHighlightsAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class ShadowsHighlightsAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isShadowsHighlightsAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ShadowsHighlightsAdjustmentRasterNodeDefinition;
  static createDefault(): ShadowsHighlightsAdjustmentRasterNodeDefinition;
}

export class ShadowsHighlightsFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isShadowsHighlightsFilterRasterNode: boolean;
  readonly parameters: any;
}

export class ShadowsHighlightsFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isShadowsHighlightsFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ShadowsHighlightsFilterRasterNodeDefinition;
  static createDefault(): ShadowsHighlightsFilterRasterNodeDefinition;
}

export class ShapeNode extends VectorNode {
  constructor(handle?: any);
  readonly isShapeNode: boolean;
  readonly artboardInterface: ArtboardInterface;
  artboardEnabled: any;
  readonly artboardDescription: string;
  readonly artboardBaseBox: any;
  readonly artboardSpreadBaseBox: any;
  readonly artboardOrigin: any;
  readonly shapeInterface: ShapeInterface;
  readonly shape: ShapeType;
  readonly shapeType: ShapeType;
  readonly shapeBoundingBox: any;
}

export class ShapeNodeDefinition extends VectorNodeDefinition {
  constructor(handle?: any);
  readonly isShapeNodeDefinition: boolean;
  setShape(shape?: Shape): this;
  shape: Shape;
  setBoundingRectangle(rectangle?: any): this;
  boundingRectangle: any;
  static create(shape?: any, rectangle?: any, brushFill?: any, lineFill?: any, lineStyle?: any, transparencyFill?: any): ShapeNodeDefinition;
  static createDefault(): ShapeNodeDefinition;
}

export class ShapePathTextNode extends TextNode {
  constructor(handle?: any);
  readonly isShapePathTextNode: boolean;
  readonly shapeInterface: ShapeInterface;
  readonly shape: ShapeType;
  readonly shapeType: ShapeType;
  readonly shapeBoundingBox: any;
}

export class ShapeTextNode extends TextNode {
  constructor(handle?: any);
  readonly isShapeTextNode: boolean;
  readonly shapeInterface: ShapeInterface;
  readonly shape: ShapeType;
  readonly shapeType: ShapeType;
  readonly shapeBoundingBox: any;
}

export class SphericalFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isSphericalFilterRasterNode: boolean;
  readonly parameters: any;
}

export class SphericalFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isSphericalFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): SphericalFilterRasterNodeDefinition;
  static createDefault(document?: any): SphericalFilterRasterNodeDefinition;
}

export class SplitToningAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isSplitToningAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class SplitToningAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isSplitToningAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): SplitToningAdjustmentRasterNodeDefinition;
  static createDefault(): SplitToningAdjustmentRasterNodeDefinition;
}

export class SpreadNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isSpreadNode: boolean;
  readonly layers: NodeChildren;
  getSpreadExtents(options?: any): any;
  readonly physicalRootInterface: PhysicalRootInterface;
  readonly physicalRootPropertiesInterface: PhysicalRootPropertiesInterface;
  readonly physicalRootProperties: any;
  readonly pageCount: number;
  readonly artboardCount: number;
  getArtboard(index?: any): ArtboardInterface;
  enumerateArtboards(callback?: (...args: any[]) => any): any;
  readonly artboards: any;
  readonly firstPageIndex: number;
  readonly lastPageIndex: number;
  readonly isFirstPage: boolean;
  getPageIndexOfPoint(pt?: any, relativeToSpread?: any): any;
  getPageIndexOfBox(box?: any, relativeToSpread?: any): any;
}

export class TableTextNode extends TextNode {
  constructor(handle?: any);
  readonly isTableTextNode: boolean;
}

export class TableTextNodeDefinition extends TextNodeDefinition {
  constructor(handle?: any);
  readonly isTableTextNodeDefinition: boolean;
  static create(box?: any, size?: any): TableTextNodeDefinition;
}

export class TextNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isTextNode: boolean;
  readonly artboardInterface: ArtboardInterface;
  artboardEnabled: any;
  readonly artboardDescription: string;
  readonly artboardBaseBox: any;
  readonly artboardSpreadBaseBox: any;
  readonly artboardOrigin: any;
  readonly brushFillInterface: BrushFillInterface;
  getBrushFillDescriptor(index?: any, obeyScaleWithObject?: boolean): any;
  setBrushFillDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): any;
  brushFillDescriptor: any;
  readonly hasBrushFill: boolean;
  readonly compoundOperationInterface: CompoundOperationInterface;
  readonly compoundOperation: CompoundOperation;
  readonly curvesInterface: CurvesInterface;
  readonly polyCurve: any;
  readonly lineStyleInterface: LineStyleInterface;
  lineStyleDescriptor: any;
  readonly lineStyleDescriptors: any;
  lineStyle: any;
  penFillDescriptor: any;
  readonly penFillDescriptors: any;
  readonly penFill: any;
  readonly hasPenFill: boolean;
  readonly isLineStyleVisible: boolean;
  lineWeight: any;
  lineWeightPts: any;
  lineType: LineType;
  lineCap: LineCap;
  lineJoin: LineJoin;
  dashPhase: any;
  dashPattern: any;
  hasBalancedDashes: boolean;
  strokeAlignment: StrokeAlignment;
  readonly storyInterface: StoryInterface;
  getText(startPos?: number, maxLength?: any, format?: StoryIoFormat): any;
  readonly text: string;
  readonly story: any;
  readonly storyRange: any;
  setText(str?: string): this;
  readonly textFrameInterface: TextFrameInterface;
  readonly transparencyInterface: TransparencyInterface;
  readonly transparencyFillDescriptor: any;
  readonly transparencyFill: any;
}

export class TextNodeDefinition extends PhysicalNodeDefinition {
  constructor(handle?: any);
  readonly isTextNodeDefinition: boolean;
}

export class ThresholdAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isThresholdAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class ThresholdAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isThresholdAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ThresholdAdjustmentRasterNodeDefinition;
  static createDefault(): ThresholdAdjustmentRasterNodeDefinition;
}

export class ToneCompressionAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isToneCompressionAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class ToneCompressionAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isToneCompressionAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ToneCompressionAdjustmentRasterNodeDefinition;
  static createDefault(): ToneCompressionAdjustmentRasterNodeDefinition;
}

export class ToneStretchAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isToneStretchAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class ToneStretchAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isToneStretchAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): ToneStretchAdjustmentRasterNodeDefinition;
  static createDefault(): ToneStretchAdjustmentRasterNodeDefinition;
}

export class TwirlFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isTwirlFilterRasterNode: boolean;
  readonly parameters: any;
}

export class TwirlFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isTwirlFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): TwirlFilterRasterNodeDefinition;
  static createDefault(document?: any): TwirlFilterRasterNodeDefinition;
}

export class UnsharpMaskFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isUnsharpMaskFilterRasterNode: boolean;
  readonly parameters: any;
}

export class UnsharpMaskFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isUnsharpMaskFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): UnsharpMaskFilterRasterNodeDefinition;
  static createDefault(): UnsharpMaskFilterRasterNodeDefinition;
}

export class VectorNode extends PhysicalNode {
  constructor(handle?: any);
  readonly isVectorNode: boolean;
  readonly canBeExpressedAsVectorClip: boolean;
  readonly brushFillInterface: BrushFillInterface;
  getBrushFillDescriptor(index?: any, obeyScaleWithObject?: boolean): any;
  setBrushFillDescriptor(fillDescriptorOrColour?: any, options?: any, preview?: any): any;
  brushFillDescriptor: any;
  readonly hasBrushFill: boolean;
  readonly compoundOperationInterface: CompoundOperationInterface;
  readonly compoundOperation: CompoundOperation;
  readonly curvesInterface: CurvesInterface;
  readonly polyCurve: any;
  readonly lineStyleInterface: LineStyleInterface;
  lineStyleDescriptor: any;
  readonly lineStyleDescriptors: any;
  lineStyle: any;
  penFillDescriptor: any;
  readonly penFillDescriptors: any;
  readonly penFill: any;
  readonly hasPenFill: boolean;
  readonly isLineStyleVisible: boolean;
  lineWeight: any;
  lineWeightPts: any;
  lineType: LineType;
  lineCap: LineCap;
  lineJoin: LineJoin;
  dashPhase: any;
  dashPattern: any;
  hasBalancedDashes: boolean;
  strokeAlignment: StrokeAlignment;
  readonly pictureFrameInterface: PictureFrameInterface;
  readonly pictureFrameEnabled: any;
  readonly pictureFrameDescription: string;
  readonly transparencyInterface: TransparencyInterface;
  readonly transparencyFillDescriptor: any;
  readonly transparencyFill: any;
}

export class VectorNodeDefinition extends PhysicalNodeDefinition {
  constructor(handle?: any);
  readonly isVectorNodeDefinition: boolean;
  addBrushFillDescriptor(brushFillDescriptor?: any): this;
  addLineDescriptors(lineFillDescriptor?: any, lineStyleDescriptor?: any): this;
  setTransparencyDescriptor(transparencyDescriptor?: FillDescriptor): this;
  transparencyDescriptor: FillDescriptor;
  readonly brushFillDescriptorCount: number;
  getBrushFillDescriptor(index?: any): FillDescriptor;
  insertBrushFillDescriptor(brushFillDescriptor?: any, index?: any): this;
  setBrushFillDescriptor(brushFillDescriptor?: any, index?: any): this;
  removeBrushFillDescriptor(index?: any): this;
  currentBrushFillIndex: number;
  readonly lineDescriptorsCount: number;
  getLineDescriptors(index?: any): any;
  insertLineDescriptors(lineFillDescriptor?: any, lineStyleDescriptor?: any, index?: any): this;
  setLineDescriptors(lineFillDescriptor?: any, lineStyleDescriptor?: any, index?: any): this;
  removeLineDescriptors(index?: any): this;
  currentLineDescriptorsIndex: number;
}

export class VibranceAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isVibranceAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class VibranceAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isVibranceAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): VibranceAdjustmentRasterNodeDefinition;
  static createDefault(): VibranceAdjustmentRasterNodeDefinition;
}

export class VignetteFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isVignetteFilterRasterNode: boolean;
  readonly parameters: any;
}

export class VignetteFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isVignetteFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): VignetteFilterRasterNodeDefinition;
  static createDefault(): VignetteFilterRasterNodeDefinition;
}

export class VoronoiFilterRasterNode extends FilterRasterNode {
  constructor(handle?: any);
  readonly isVoronoiFilterRasterNode: boolean;
  readonly parameters: any;
}

export class VoronoiFilterRasterNodeDefinition extends FilterRasterNodeDefinition {
  constructor(handle?: any);
  readonly isVoronoiFilterRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): VoronoiFilterRasterNodeDefinition;
  static createDefault(): VoronoiFilterRasterNodeDefinition;
}

export class WhiteBalanceAdjustmentRasterNode extends AdjustmentRasterNode {
  constructor(handle?: any);
  readonly isWhiteBalanceAdjustmentRasterNode: boolean;
  readonly parameters: any;
}

export class WhiteBalanceAdjustmentRasterNodeDefinition extends AdjustmentRasterNodeDefinition {
  constructor(handle?: any);
  readonly isWhiteBalanceAdjustmentRasterNodeDefinition: boolean;
  parameters: any;
  setParameters(parameters?: any): this;
  static create(parameters?: any): WhiteBalanceAdjustmentRasterNodeDefinition;
  static createDefault(): WhiteBalanceAdjustmentRasterNodeDefinition;
}

export { BlackAndWhiteAdjustmentParameters } from 'affinity:dom';
export { BrightnessContrastAdjustmentParameters } from 'affinity:dom';
export { ColourBalanceAdjustmentParameters } from 'affinity:dom';
export { ColourBalanceValues } from 'affinity:dom';
export { ExposureAdjustmentParameters } from 'affinity:dom';
export { HSLShiftAdjustmentChannelParameters } from 'affinity:dom';
export { HSLShiftAdjustmentColourRange } from 'affinity:dom';
export { LevelsAdjustmentChannelParameters } from 'affinity:dom';
export { LevelsAdjustmentParameters } from 'affinity:dom';
export { NormalsAdjustmentParameters } from 'affinity:dom';
export { PosteriseAdjustmentParameters } from 'affinity:dom';
export { RecolourAdjustmentParameters } from 'affinity:dom';
export { ShadowsHighlightsAdjustmentParameters } from 'affinity:dom';
export { SelectiveColourAdjustmentParameters } from 'affinity:dom';
export { SplitToningAdjustmentParameters } from 'affinity:dom';
export { ThresholdAdjustmentParameters } from 'affinity:dom';
export { ToneCompressionAdjustmentParameters } from 'affinity:dom';
export { ToneStretchAdjustmentParameters } from 'affinity:dom';
export { VibranceAdjustmentParameters } from 'affinity:dom';
export { WhiteBalanceAdjustmentParameters } from 'affinity:dom';
export { AddNoiseFilterParameters } from 'affinity:dom';
export { BilateralBlurFilterParameters } from 'affinity:dom';
export { BloomFilterParameters } from 'affinity:dom';
export { BoxBlurFilterParameters } from 'affinity:dom';
export { ClarityFilterParameters } from 'affinity:dom';
export { DefringeFilterParameters } from 'affinity:dom';
export { DenoiseFilterParameters } from 'affinity:dom';
export { DiffuseFilterParameters } from 'affinity:dom';
export { DiffuseGlowFilterParameters } from 'affinity:dom';
export { DustAndScratchFilterParameters } from 'affinity:dom';
export { EllipticalDepthOfFieldParameters } from 'affinity:dom';
export { FieldBlurItemParameters } from 'affinity:dom';
export { GaussianBlurFilterParameters } from 'affinity:dom';
export { HalftoneFilterParameters } from 'affinity:dom';
export { ShadowsHighlightsFilterParameters } from 'affinity:dom';
export { HighPassFilterParameters } from 'affinity:dom';
export { LensBlurFilterParameters } from 'affinity:dom';
export { MedianBlurFilterParameters } from 'affinity:dom';
export { MaximumBlurFilterParameters } from 'affinity:dom';
export { MinimumBlurFilterParameters } from 'affinity:dom';
export { MotionBlurFilterParameters } from 'affinity:dom';
export { PinchPunchFilterParameters } from 'affinity:dom';
export { PixelateFilterParameters } from 'affinity:dom';
export { RadialBlurFilterParameters } from 'affinity:dom';
export { RippleFilterParameters } from 'affinity:dom';
export { SphericalFilterParameters } from 'affinity:dom';
export { TiltShiftDepthOfFieldParameters } from 'affinity:dom';
export { TwirlFilterParameters } from 'affinity:dom';
export { UnsharpMaskFilterParameters } from 'affinity:dom';
export { VignetteFilterParameters } from 'affinity:dom';
export { VoronoiFilterParameters } from 'affinity:dom';
export function createTypedNode(handle?: any): any;
export { AddNoiseType } from 'affinity:dom';
export { ColourSpaceType } from 'affinity:colours';
export { DepthOfFieldMode } from 'affinity:dom';
export { PageBoundingBoxType } from 'affinity:dom';
export { RasterExtendType } from 'affinity:raster';
export { RasterFormat } from 'affinity:raster';
export { RasterResamplerType } from 'affinity:raster';
export { ShadowsHighlightsVersion } from 'affinity:dom';
export { SelectiveColour } from 'affinity:dom';
export { TonalRangeType } from 'affinity:dom';
export { ToneCompressionMethod } from 'affinity:dom';
export { ToneStretchMethod } from 'affinity:dom';
export { BloomMethod } from 'affinity:dom';
export { HalftoneScreenType } from 'affinity:dom';
export { HalftoneDotType } from 'affinity:dom';
export { NodeChildType } from 'affinity:dom';
export const getNodeSiblings: any;
export const getNodeChildren: any;
export const getNodesRecursive: any;
export const getNodeChildrenRecursive: any;
