// Auto-generated by tools/generate_types.py. Do not edit.

export class OS {
  constructor(...args: any[]);
  static readonly arch: any;
  static readonly Eol: any;
  static readonly machine: any;
  static readonly platform: any;
  static readonly release: any;
  static readonly osName: string;
  static readonly osVersion: string;
}

