// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class PageBoxInterface extends HandleObject {
  constructor(handle?: any);
  getPageBoundingBox(pageBoundingBoxType?: any): any;
}

export { PageBoundingBoxType } from 'affinity:dom';
