// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class ParagraphAtts extends HandleObject {
  constructor(handle?: any);
  static create(): ParagraphAtts;
  clone(): ParagraphAtts;
  alignXType: any;
  leadingType: any;
  startAtHardBreakType: any;
  useSpaceBeforeMode: any;
  pdfExportTagType: any;
  lineBreakModeType: any;
  isKeepWithPrevious: boolean;
  isKeepTogether: boolean;
  isPreventWidows: boolean;
  isPreventOrphans: boolean;
  alignToBaselineGrid: any;
  isAutoHyphenate: boolean;
  isIndex: boolean;
  useSpaceBetweenSameStyles: any;
  isSumBeforeAndAfterSpace: boolean;
  isBookEndnotes: boolean;
  useModernLeading: any;
  keepWithNext: any;
  hyphenateMinLength: number;
  hyphenateMinPrefix: any;
  hyphenateMinSuffix: any;
  maxConsecutiveHyphens: any;
  relativeLeading: any;
  absoluteLeading: any;
  leftIndent: any;
  rightIndent: any;
  firstLineIndent: any;
  spaceBefore: any;
  spaceAfter: any;
  defaultTabStops: any;
  minWordSpacing: any;
  desiredWordSpacing: any;
  maxWordSpacing: any;
  minLetterSpacing: any;
  desiredLetterSpacing: any;
  maxLetterSpacing: any;
  minHyphenScore: any;
  hyphenationZone: any;
  hyphenationZoneCapitals: any;
  hyphenationZoneParagraphEnd: any;
  hyphenationZoneColumnEnd: any;
  lastLineOutdent: any;
  spaceBetweenSameStyles: any;
  getDoubleValue(att?: any): any;
  setDoubleValue(att?: any, value?: any): this;
  styleName: string;
  getStringValue(att?: any): any;
  setStringValue(att?: any, value?: any): this;
}

export { ParagraphAlignXType } from 'affinity:story';
export { ParagraphLeadingType } from 'affinity:story';
export { ParagraphStartAtHardBreakType } from 'affinity:story';
export { ParagraphUseSpaceBeforeMode } from 'affinity:story';
export { ParagraphPDFExportTagType } from 'affinity:story';
export { ParagraphLineBreakModeType } from 'affinity:story';
export { ParagraphAttDoubleType } from 'affinity:story';
export { ParagraphAttStringType } from 'affinity:story';
