// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class PhysicalRootPropertiesInterface extends HandleObject {
  constructor(handle?: any);
  readonly pageCount: any;
  readonly pageBoxInterface: any;
  readonly node: any;
}

