// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { PhysicalRootPropertiesInterface } from '/physicalrootpropertiesinterface';

export class PhysicalRootInterface extends HandleObject {
  constructor(handle?: any);
  readonly physicalRootProperties: PhysicalRootPropertiesInterface;
  readonly node: any;
}

