// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { PageBoxInterface } from '/pageboxinterface';

export class PhysicalRootPropertiesInterface extends HandleObject {
  constructor(handle?: any);
  readonly pageCount: number;
  readonly pageBoxInterface: PageBoxInterface;
  readonly node: any;
}

