// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class PhysicalRootInterface extends HandleObject {
  constructor(handle?: any);
  readonly physicalRootProperties: any;
  readonly node: any;
}

