// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class PictureFrameInterface extends HandleObject {
  constructor(handle?: any);
  readonly enabled: any;
  readonly description: any;
  readonly hasFrameContents: any;
  readonly frameContents: any;
  readonly anchor: any;
  readonly isClearFillOnPopulate: any;
  readonly originalContentRectangle: any;
  readonly dataMergeFieldId: any;
  calculateAnchor(node?: any, hint?: any): any;
  calculateConstraints(node?: any, hint?: any): any;
  readonly node: any;
}

export { ConstraintType } from 'affinity:dom';
export { SpatialAnchor } from 'affinity:dom';
