// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class PixelReaderCMYKA8 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderCMYKA8;
}

export class PixelReaderIA16 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderIA16;
}

export class PixelReaderIA8 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderIA8;
}

export class PixelReaderLABA16 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderLABA16;
}

export class PixelReaderM16 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderM16;
}

export class PixelReaderM8 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderM8;
}

export class PixelReaderMf extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderMf;
}

export class PixelReaderRGBA16 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderRGBA16;
}

export class PixelReaderRGBA8 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderRGBA8;
}

export class PixelReaderRGBAuf extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderRGBAuf;
}

export class PixelReaderWriterCMYKA8 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  writePixel(x?: any, y?: any, rgba8?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderWriterCMYKA8;
}

export class PixelReaderWriterIA16 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  writePixel(x?: any, y?: any, rgba8?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderWriterIA16;
}

export class PixelReaderWriterIA8 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  writePixel(x?: any, y?: any, rgba8?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderWriterIA8;
}

export class PixelReaderWriterLABA16 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  writePixel(x?: any, y?: any, rgba8?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderWriterLABA16;
}

export class PixelReaderWriterM16 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  writePixel(x?: any, y?: any, rgba8?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderWriterM16;
}

export class PixelReaderWriterM8 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  writePixel(x?: any, y?: any, rgba8?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderWriterM8;
}

export class PixelReaderWriterMf extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  writePixel(x?: any, y?: any, rgba8?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderWriterMf;
}

export class PixelReaderWriterRGBA16 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  writePixel(x?: any, y?: any, rgba8?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderWriterRGBA16;
}

export class PixelReaderWriterRGBA8 extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  writePixel(x?: any, y?: any, rgba8?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderWriterRGBA8;
}

export class PixelReaderWriterRGBAuf extends HandleObject {
  constructor(handle?: any);
  readPixel(x?: any, y?: any): any;
  writePixel(x?: any, y?: any, rgba8?: any): any;
  dispose(): any;
  static create(bitmap?: any): PixelReaderWriterRGBAuf;
}

