// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class BrushDynamic extends HandleObject {
  constructor(handle?: any);
  clone(): BrushDynamic;
  value: any;
  variance: any;
  controllerType: any;
  readonly dynamicMax: any;
  readonly dynamicMin: any;
  spline: any;
}

export class RasterBrush extends HandleObject {
  constructor(handle?: any);
  static createDefault(): any;
  clone(): RasterBrush;
  size: any;
  accumulation: any;
  flow: any;
  angle: any;
  scatterX: any;
  scatterY: any;
  hardness: any;
  shape: any;
  hueShift: any;
  satShift: any;
  lumShift: any;
  spacing: any;
  opacity: any;
  blendMode: any;
  wetEdges: any;
  shouldApplyWetEdges: any;
  shouldInterpolateTips: any;
  maskTextureMode: any;
  maskTextureScale: any;
}

export { BlendMode } from 'affinity:common';
export { BrushDynamicControllerType } from 'affinity:brushes';
export { RasterBrushTextureMode } from 'affinity:brushes';
