// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { RasterFormat } from 'affinity:raster';
import { RasterObjectType } from 'affinity:raster';

export class Bitmap extends RasterObject {
  constructor(handle?: any);
  static create(width?: any, height?: any, format?: any): Bitmap;
  static loadFromFile(path?: string, format?: RasterFormat): Bitmap;
  static loadFromFileAsync(path?: string, format?: any, callback?: (...args: any[]) => any): any;
}

export class NodeRenderingEngine extends RasterObject {
  constructor(handle?: any);
  static createDefault(node?: any, format?: any): NodeRenderingEngine;
  static create(node?: any, format?: any, options?: any): NodeRenderingEngine;
}

export class PixelBuffer extends RasterObject {
  constructor(handle?: any);
  static create(width?: any, height?: any, format?: any): PixelBuffer;
  readonly buffer: any;
}

export class RasterObject extends HandleObject {
  constructor(handle?: any);
  readonly width: number;
  readonly height: number;
  readonly format: any;
  readonly pixelSize: any;
  readonly type: RasterObjectType;
  createCompatibleBitmap(copyContents?: any): Bitmap;
  createCompatibleBuffer(copyContents?: any): PixelBuffer;
  copyTo(dest?: any, destRect?: any, srcX?: any, srcY?: any): any;
  clone(): RasterObject;
  cloneEmpty(): RasterObject;
}

export function createTypedRasterObject(handle?: any): any;
export { RasterExtendType } from 'affinity:raster';
export { RasterFormat } from 'affinity:raster';
export { RasterIntent } from 'affinity:raster';
export { RasterObjectType } from 'affinity:raster';
export { RasterResamplerType } from 'affinity:raster';
