// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class RasterSelection extends HandleObject {
  constructor(handle?: any);
  readonly isCurrentPixelSelection: boolean;
  readonly isSelectAllOrNone: boolean;
  readonly isSelectNone: boolean;
}

