// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { Spline } from '/geometry';
import { BlendMode } from 'affinity:common';
import { BrushDynamicControllerType } from 'affinity:brushes';

export class BrushDynamic extends HandleObject {
  constructor(handle?: any);
  clone(): BrushDynamic;
  value: any;
  variance: any;
  controllerType: BrushDynamicControllerType;
  readonly dynamicMax: any;
  readonly dynamicMin: any;
  spline: Spline;
}

export class RasterBrush extends HandleObject {
  constructor(handle?: any);
  static createDefault(): any;
  clone(): RasterBrush;
  size: BrushDynamic;
  accumulation: BrushDynamic;
  flow: BrushDynamic;
  angle: BrushDynamic;
  scatterX: BrushDynamic;
  scatterY: BrushDynamic;
  hardness: BrushDynamic;
  shape: BrushDynamic;
  hueShift: BrushDynamic;
  satShift: BrushDynamic;
  lumShift: BrushDynamic;
  spacing: any;
  opacity: any;
  blendMode: BlendMode;
  wetEdges: any;
  shouldApplyWetEdges: boolean;
  shouldInterpolateTips: boolean;
  maskTextureMode: any;
  maskTextureScale: any;
}

export { BlendMode } from 'affinity:common';
export { BrushDynamicControllerType } from 'affinity:brushes';
export { RasterBrushTextureMode } from 'affinity:brushes';
