// Auto-generated by tools/generate_types.py. Do not edit.

import { Bitmap } from '/rasterobject';
import { HandleObject } from '/handleobject';
import { PixelBuffer } from '/rasterobject';

export class RasterInterface extends HandleObject {
  constructor(handle?: any);
  readonly width: number;
  readonly height: number;
  readonly format: any;
  readonly pixelSize: any;
  createCompatibleBitmap(copyContents?: any): Bitmap;
  createCompatibleBuffer(copyContents?: any): PixelBuffer;
  copyTo(dest?: any, destRect?: any, srcX?: any, srcY?: any): any;
  readonly node: any;
}

export { RasterFormat } from 'affinity:raster';
