// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class CurveEdgeSubSelection extends SubSelection {
  constructor(handle?: any);
  static create(items?: any): CurveEdgeSubSelection;
  readonly isEmpty: any;
  readonly itemCount: any;
  getItem(index?: any): any;
  enumerateItems(callback?: (...args: any[]) => any): any;
  readonly items: any;
  enumerateItemsWithCurveID(curveID?: any, callback?: (...args: any[]) => any): any;
  getItemsWithCurveID(curveID?: any): any;
  cloneAndAddItems(items?: any): CurveEdgeSubSelection;
  cloneAndRemoveItems(items?: any): CurveEdgeSubSelection;
  cloneAndRemoveCurves(curveIDs?: any): CurveEdgeSubSelection;
  clone(): CurveEdgeSubSelection;
}

export class CurveNodeSubSelection extends SubSelection {
  constructor(handle?: any);
  static create(items?: any): CurveNodeSubSelection;
  readonly isEmpty: any;
  readonly itemCount: any;
  getItem(index?: any): any;
  enumerateItems(callback?: (...args: any[]) => any): any;
  readonly items: any;
  enumerateItemsWithCurveID(curveID?: any, callback?: (...args: any[]) => any): any;
  getItemsWithCurveID(curveID?: any): any;
  cloneAndAddItems(items?: any): CurveNodeSubSelection;
  cloneAndRemoveItems(items?: any): CurveNodeSubSelection;
  cloneAndRemoveCurves(curveIDs?: any): CurveNodeSubSelection;
  clone(): CurveNodeSubSelection;
}

export class FillMeshSubSelection extends SubSelection {
  constructor(handle?: any);
  readonly isFillMeshSubSelection: any;
  readonly isEmpty: any;
  readonly itemCount: any;
  enumerateItems(callback?: (...args: any[]) => any): any;
  readonly items: any;
  static fromSubSelection(subSelection?: any): FillMeshSubSelection;
}

export class FillSubSelection extends SubSelection {
  constructor(handle?: any);
  readonly index: any;
  static fromSubSelection(subSelection?: any): FillSubSelection;
  clone(): FillSubSelection;
  cloneAsFillSubSelection(): FillSubSelection;
}

export class LineFillMeshSubSelection extends SubSelection {
  constructor(handle?: any);
  readonly isLineFillMeshSubSelection: any;
  readonly isEmpty: any;
  readonly itemCount: any;
  enumerateItems(callback?: (...args: any[]) => any): any;
  readonly items: any;
  static fromSubSelection(subSelection?: any): LineFillMeshSubSelection;
}

export class LineFillSubSelection extends SubSelection {
  constructor(handle?: any);
  readonly index: any;
  static fromSubSelection(subSelection?: any): LineFillSubSelection;
  clone(): LineFillSubSelection;
  cloneAsLineFillSubSelection(): LineFillSubSelection;
}

export class Selection extends HandleObject {
  constructor(handle?: any);
  readonly length: any;
  at(index?: any): SelectionItem;
  readonly items: any;
  readonly nodes: any;
  readonly firstNode: any;
  add(nodeOrItem?: any): any;
  addNode(node?: any): any;
  addItem(item?: any): any;
  addSelectable(selectable?: any): any;
  addSubSelectionForNode(node?: any, subSelection?: any): any;
  readonly isSelection: any;
  getFirstSubSelectionOfType(subSelectionType?: any): any;
  removeNested(): any;
  containsItem(item?: any): any;
  static create(document?: any, items?: any, removeNested?: any): any;
  static createEmpty(document?: any): Selection;
  clear(): any;
}

export class SelectionItem extends HandleObject {
  constructor(handle?: any);
  readonly isSelectionItem: any;
  readonly node: any;
  getSubSelection(index?: any): any;
  getSubSelectionOfType(subSelectionType?: any): any;
  readonly subSelectionCount: any;
  enumerateSubSelections(callback?: (...args: any[]) => any): any;
  readonly subSelections: any;
}

export class SubSelection extends HandleObject {
  constructor(handle?: any);
  readonly isSubSelection: any;
  readonly subSelectionType: any;
}

export class TableSubSelection extends SubSelection {
  constructor(handle?: any);
  readonly isEmpty: any;
  readonly isRectangle: any;
  readonly anchor: any;
  readonly caret: any;
  readonly boundingBox: any;
  enumerateCells(callback?: (...args: any[]) => any): any;
  enumerateEdges(tableAxis?: any, tableEdgeSelector?: any, callback?: (...args: any[]) => any): any;
  readonly cells: any;
  getEdges(tableAxis?: any, tableEdgeSelector?: any): any;
  static fromSubSelection(subSelection?: any): TableSubSelection;
}

export class TextSelection extends SubSelection {
  constructor(handle?: any);
  static create(rangesOrNull?: any): TextSelection;
  readonly isEmpty: any;
  readonly hasMarkedText: any;
  readonly caret: any;
  readonly anchor: any;
  readonly markedTextBegin: any;
  readonly markedTextEnd: any;
  readonly rangeCount: any;
  getRange(index?: any): any;
  enumerateRanges(callback?: (...args: any[]) => any): any;
  readonly ranges: any;
}

export class TransparencyMeshSubSelection extends SubSelection {
  constructor(handle?: any);
  readonly isTransparencyMeshSubSelection: any;
  readonly isEmpty: any;
  readonly itemCount: any;
  enumerateItems(callback?: (...args: any[]) => any): any;
  readonly items: any;
  static fromSubSelection(subSelection?: any): TransparencyMeshSubSelection;
}

export class TransparencySubSelection extends SubSelection {
  constructor(handle?: any);
  readonly index: any;
  static fromSubSelection(subSelection?: any): TransparencySubSelection;
  clone(): TransparencySubSelection;
  cloneAsTransparencySubSelection(): TransparencySubSelection;
}

export function createTypedSubSelection(subSelectionHandle?: any): any;
export { CurveNodeSubSelectionItem } from 'affinity:dom';
export { CurveEdgeSubSelectionItem } from 'affinity:dom';
export { MeshSubSelectionItem } from 'affinity:dom';
export { SubSelectionType } from 'affinity:dom';
export { TableAxis } from 'affinity:story';
export { TableEdgeSelector } from 'affinity:dom';
