// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class Selectable extends HandleObject {
  constructor(handle?: any);
  readonly isSelectable: any;
}

