// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class QRPayload extends HandleObject {
  constructor(handle?: any);
  clone(): QRPayload;
  readonly payloadType: any;
  readonly payloadString: any;
  readonly payloadDisplayString: any;
  readonly isPayloadValid: any;
  clearPayload(): any;
  static create(type?: any): QRPayload;
  static parse(payloadString?: any): QRPayload;
}

export class QRPayloadEmail extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadEmail;
  clone(): QRPayloadEmail;
  address: any;
  subject: any;
  body: any;
  readonly isAddressValid: any;
}

export class QRPayloadFaceTime extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadFaceTime;
  clone(): QRPayloadFaceTime;
  recipient: any;
}

export class QRPayloadLocation extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadLocation;
  clone(): QRPayloadLocation;
  latitude: any;
  longitude: any;
  elevation: any;
  readonly isLatitudeValid: any;
  readonly isLongitudeValid: any;
  readonly isElevationValid: any;
}

export class QRPayloadPhone extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadPhone;
  clone(): QRPayloadPhone;
  number: any;
}

export class QRPayloadSMS extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadSMS;
  clone(): QRPayloadSMS;
  content: any;
  number: any;
  readonly isNumberValid: any;
}

export class QRPayloadText extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadText;
  clone(): QRPayloadText;
  text: any;
}

export class QRPayloadURL extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadURL;
  clone(): QRPayloadURL;
  url: any;
  readonly isURLValid: any;
}

export class QRPayloadVCard extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadVCard;
  clone(): QRPayloadVCard;
  getpPrefixes(): any;
  firstName: any;
  lastName: any;
  suffixes: any;
  phone: any;
  email: any;
  website: any;
  company: any;
  jobTitle: any;
  birthday: any;
  streetAddress: any;
  city: any;
  postalCode: any;
  region: any;
  country: any;
  notes: any;
  readonly isFullNameValid: any;
  readonly isFirstNameValid: any;
  readonly isLastNameValid: any;
  readonly isEmailValid: any;
  readonly isWebsiteValid: any;
  prefixes: any;
}

export class QRPayloadWhatsApp extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadWhatsApp;
  clone(): QRPayloadWhatsApp;
  content: any;
  number: any;
}

export class QRPayloadWifi extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadWifi;
  clone(): QRPayloadWifi;
  ssid: any;
  password: any;
  encryption: any;
  hidden: any;
  readonly isSSIDValid: any;
}

export class Shape extends HandleObject {
  constructor(handle?: any);
  static create(shapeType?: any): any;
  readonly shapeType: any;
  readonly displayName: any;
  readonly majorAxis: any;
  readonly isAffectedByScale: any;
  getCurves(bounds?: any, transform?: any): any;
  readonly rotationOrder: any;
  getTransformedBounds(bounds?: any, xf?: any): any;
  clone(): any;
  static getTypeBaseType(shapeType?: any): any;
  static getTypeDisplayName(shapeType?: any): any;
}

export class ShapeArrow extends Shape {
  constructor(handle?: any);
  static create(): ShapeArrow;
  clone(): ShapeArrow;
  readonly leftEnd: any;
  readonly rightEnd: any;
  thickness: any;
  setLeftEnd(value?: any, width?: any, height?: any): any;
  setRightEnd(value?: any, width?: any, height?: any): any;
}

export class ShapeArrowLeftEndProxy extends HandleObject {
  constructor(shapeArrowHandle?: any);
  style: any;
  readonly length: any;
  readonly innerOffset: any;
  readonly isProportional: any;
  setLength(value?: any, width?: any, height?: any): any;
  setInnerOffset(value?: any, width?: any, height?: any): any;
  setIsProportional(value?: any, width?: any, height?: any): any;
  assign(src?: any, width?: any, height?: any): any;
}

export class ShapeArrowRightEndProxy extends HandleObject {
  constructor(shapeArrowHandle?: any);
  style: any;
  readonly length: any;
  readonly innerOffset: any;
  readonly isProportional: any;
  setLength(value?: any, width?: any, height?: any): any;
  setInnerOffset(value?: any, width?: any, height?: any): any;
  setIsProportional(value?: any, width?: any, height?: any): any;
  assign(src?: any, width?: any, height?: any): any;
}

export class ShapeCalloutEllipse extends Shape {
  constructor(handle?: any);
  static create(): ShapeCalloutEllipse;
  clone(): ShapeCalloutEllipse;
  readonly absoluteSizes: any;
  setAbsoluteSizes(value?: any, boundsWidth?: any, boundsHeight?: any): any;
  tail: any;
}

export class ShapeCalloutEllipseTail extends HandleObject {
  constructor(shapeHandle?: any);
  angle: any;
  endPosition: any;
  height: any;
  assign(src?: any): any;
}

export class ShapeCalloutRectangle extends Shape {
  constructor(handle?: any);
  static create(): ShapeCalloutRectangle;
  clone(): ShapeCalloutRectangle;
  getCornerRadius(cornerIndex?: any): any;
  readonly absoluteSizes: any;
  useSingleRadius: any;
  tail: any;
  setCornerRadius(cornerIndex?: any, radius?: any, boundsWidth?: any, boundsHeight?: any): any;
  setAbsoluteSizes(value?: any, width?: any, height?: any): any;
}

export class ShapeCalloutRectangleTailProxy extends HandleObject {
  constructor(shapeCalloutRectangleHandle?: any);
  startPosition: any;
  endPosition: any;
  width: any;
  height: any;
  assign(src?: any): any;
}

export class ShapeCat extends Shape {
  constructor(handle?: any);
  static create(): ShapeCat;
  clone(): ShapeCat;
}

export class ShapeCat2 extends Shape {
  constructor(handle?: any);
  static create(): ShapeCat2;
  clone(): ShapeCat2;
}

export class ShapeCat3 extends Shape {
  constructor(handle?: any);
  static create(): ShapeCat3;
  clone(): ShapeCat3;
}

export class ShapeCat4 extends Shape {
  constructor(handle?: any);
  static create(): ShapeCat4;
  clone(): ShapeCat4;
}

export class ShapeCloud extends Shape {
  constructor(handle?: any);
  static create(): ShapeCloud;
  clone(): ShapeCloud;
  bubbles: any;
  innerRadius: any;
}

export class ShapeCog extends Shape {
  constructor(handle?: any);
  static create(): ShapeCog;
  clone(): ShapeCog;
  innerRadius: any;
  holeRadius: any;
  toothSize: any;
  notchSize: any;
  curvature: any;
  teeth: any;
}

export class ShapeCrescent extends Shape {
  constructor(handle?: any);
  static create(): ShapeCrescent;
  clone(): ShapeCrescent;
  leftArc: any;
  rightArc: any;
}

export class ShapeDiamond extends Shape {
  constructor(handle?: any);
  static create(): ShapeDiamond;
  clone(): ShapeDiamond;
  position: any;
}

export class ShapeDoubleStar extends Shape {
  constructor(handle?: any);
  static create(): ShapeDoubleStar;
  clone(): ShapeDoubleStar;
  innerRadius: any;
  pointRadius: any;
  points: any;
}

export class ShapeEllipse extends Shape {
  constructor(handle?: any);
  static create(): ShapeEllipse;
  clone(): ShapeEllipse;
}

export class ShapeHeart extends Shape {
  constructor(handle?: any);
  static create(): ShapeHeart;
  clone(): ShapeHeart;
  spread: any;
}

export class ShapePie extends Shape {
  constructor(handle?: any);
  static create(): ShapePie;
  clone(): ShapePie;
  innerRadius: any;
  startAngle: any;
  endAngle: any;
  sweep: any;
  readonly isClosed: any;
  closePie(): any;
}

export class ShapePolygon extends Shape {
  constructor(handle?: any);
  static create(): ShapePolygon;
  clone(): ShapePolygon;
  curve: any;
  sides: any;
  smoothPoints: any;
  readonly minCurve: any;
}

export class ShapeQRCode extends Shape {
  constructor(handle?: any);
  static create(): ShapeQRCode;
  clone(): ShapeQRCode;
  payload: any;
}

export class ShapeRectangle extends Shape {
  constructor(handle?: any);
  static create(): ShapeRectangle;
  clone(): ShapeRectangle;
  readonly topLeft: any;
  readonly topRight: any;
  readonly bottomLeft: any;
  readonly bottomRight: any;
  readonly isPlainRectangle: any;
  readonly absoluteSizes: any;
  useSingleRadius: any;
  setTopLeft(value?: any, width?: any, height?: any): any;
  setTopRight(value?: any, width?: any, height?: any): any;
  setBottomLeft(value?: any, width?: any, height?: any): any;
  setBottomRight(value?: any, width?: any, height?: any): any;
  setAbsoluteSizes(value?: any, width?: any, height?: any): any;
}

export class ShapeRectangleCornerProxy extends HandleObject {
  constructor(shapeRectangleHandle?: any, cornerIndex?: any);
  readonly radius: any;
  cornerType: any;
  setRadius(value?: any, width?: any, height?: any): any;
  assign(src?: any, width?: any, height?: any): any;
}

export class ShapeSegment extends Shape {
  constructor(handle?: any);
  static create(): ShapeSegment;
  clone(): ShapeSegment;
  angle: any;
  lowerLine: any;
  upperLine: any;
}

export class ShapeSpiral extends Shape {
  constructor(handle?: any);
  static create(): ShapeSpiral;
  clone(): ShapeSpiral;
  style: any;
  flip: any;
  turns: any;
  partTurn: any;
  decay: any;
  segmentAngle: any;
  divisions: any;
  innerRadius: any;
  decayPerSegment: any;
  cusped: any;
  choke: any;
  capChoke: any;
  bias: any;
}

export class ShapeSquareStar extends Shape {
  constructor(handle?: any);
  static create(): ShapeSquareStar;
  clone(): ShapeSquareStar;
  sides: any;
  cutout: any;
}

export class ShapeStar extends Shape {
  constructor(handle?: any);
  static create(): ShapeStar;
  clone(): ShapeStar;
  readonly maxInnerRadius: any;
  innerRadius: any;
  leftCurve: any;
  rightCurve: any;
  circleInnerRadius: any;
  circleOuterRadius: any;
  points: any;
  curvedEdges: any;
}

export class ShapeTear extends Shape {
  constructor(handle?: any);
  static create(): ShapeTear;
  clone(): ShapeTear;
  ball: any;
  curve: any;
  bend: any;
  tailPosition: any;
}

export class ShapeTearBallProxy extends HandleObject {
  constructor(shapeTearHandle?: any);
  size: any;
  fixedSize: any;
  assign(src?: any): any;
}

export class ShapeTrapezoid extends Shape {
  constructor(handle?: any);
  static create(): ShapeTrapezoid;
  clone(): ShapeTrapezoid;
  left: any;
  right: any;
  setPositions(left?: any, right?: any): any;
}

export class ShapeTriangle extends Shape {
  constructor(handle?: any);
  static create(): ShapeTriangle;
  clone(): ShapeTriangle;
  position: any;
}

export function createTypedQRPayload(payloadHandle?: any): any;
export function createTypedShape(shapeHandle?: any): any;
export const QRPayloadType: any;
export { ShapeArrowEndStyle } from 'affinity:geometry';
export { ShapeBoolParam } from 'affinity:geometry';
export { ShapeCornerIndex } from 'affinity:geometry';
export { ShapeCornerType } from 'affinity:geometry';
export { ShapeEnumParam } from 'affinity:geometry';
export { ShapeFloatParam } from 'affinity:geometry';
export { ShapeIntParam } from 'affinity:geometry';
export { ShapeMajorAxis } from 'affinity:geometry';
export { ShapeSpiralStyle } from 'affinity:geometry';
export { ShapeType } from 'affinity:geometry';
export { WifiEncryptionType } from 'affinity:geometry';
