// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { ContentType } from 'affinity:dom';
import { NoteType } from 'affinity:story';
import { ShapeMajorAxis } from 'affinity:geometry';
import { ShapeSpiralStyle } from 'affinity:geometry';
import { ShapeType } from 'affinity:geometry';

export class QRPayload extends HandleObject {
  constructor(handle?: any);
  clone(): QRPayload;
  readonly payloadType: any;
  readonly payloadString: any;
  readonly payloadDisplayString: any;
  readonly isPayloadValid: boolean;
  clearPayload(): any;
  static create(type?: any): QRPayload;
  static parse(payloadString?: any): QRPayload;
}

export class QRPayloadEmail extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadEmail;
  clone(): QRPayloadEmail;
  address: any;
  subject: any;
  body: any;
  readonly isAddressValid: boolean;
}

export class QRPayloadFaceTime extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadFaceTime;
  clone(): QRPayloadFaceTime;
  recipient: any;
}

export class QRPayloadLocation extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadLocation;
  clone(): QRPayloadLocation;
  latitude: any;
  longitude: any;
  elevation: any;
  readonly isLatitudeValid: boolean;
  readonly isLongitudeValid: boolean;
  readonly isElevationValid: boolean;
}

export class QRPayloadPhone extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadPhone;
  clone(): QRPayloadPhone;
  number: any;
}

export class QRPayloadSMS extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadSMS;
  clone(): QRPayloadSMS;
  content: ContentType;
  number: any;
  readonly isNumberValid: boolean;
}

export class QRPayloadText extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadText;
  clone(): QRPayloadText;
  text: string;
}

export class QRPayloadURL extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadURL;
  clone(): QRPayloadURL;
  url: any;
  readonly isURLValid: boolean;
}

export class QRPayloadVCard extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadVCard;
  clone(): QRPayloadVCard;
  getpPrefixes(): any;
  firstName: string;
  lastName: string;
  suffixes: any;
  phone: any;
  email: any;
  website: any;
  company: any;
  jobTitle: string;
  birthday: any;
  streetAddress: any;
  city: any;
  postalCode: any;
  region: any;
  country: number;
  notes: NoteType;
  readonly isFullNameValid: boolean;
  readonly isFirstNameValid: boolean;
  readonly isLastNameValid: boolean;
  readonly isEmailValid: boolean;
  readonly isWebsiteValid: boolean;
  prefixes: any;
}

export class QRPayloadWhatsApp extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadWhatsApp;
  clone(): QRPayloadWhatsApp;
  content: ContentType;
  number: any;
}

export class QRPayloadWifi extends QRPayload {
  constructor(handle?: any);
  static create(): QRPayloadWifi;
  clone(): QRPayloadWifi;
  ssid: number;
  password: any;
  encryption: any;
  hidden: any;
  readonly isSSIDValid: boolean;
}

export class Shape extends HandleObject {
  constructor(handle?: any);
  static create(shapeType?: any): Shape;
  readonly shapeType: ShapeType;
  readonly displayName: string;
  readonly majorAxis: ShapeMajorAxis;
  readonly isAffectedByScale: boolean;
  getCurves(bounds?: any, transform?: any): any;
  readonly rotationOrder: any;
  getTransformedBounds(bounds?: any, xf?: any): any;
  clone(): Shape;
  static getTypeBaseType(shapeType?: any): any;
  static getTypeDisplayName(shapeType?: any): string;
}

export class ShapeArrow extends Shape {
  constructor(handle?: any);
  static create(): ShapeArrow;
  clone(): ShapeArrow;
  readonly leftEnd: ShapeArrowLeftEndProxy;
  readonly rightEnd: ShapeArrowRightEndProxy;
  thickness: any;
  setLeftEnd(value?: any, width?: any, height?: any): this;
  setRightEnd(value?: any, width?: any, height?: any): this;
}

export class ShapeArrowLeftEndProxy extends HandleObject {
  constructor(shapeArrowHandle?: any);
  style: any;
  readonly length: number;
  readonly innerOffset: any;
  readonly isProportional: boolean;
  setLength(value?: any, width?: any, height?: any): this;
  setInnerOffset(value?: any, width?: any, height?: any): this;
  setIsProportional(value?: any, width?: any, height?: any): this;
  assign(src?: any, width?: any, height?: any): any;
}

export class ShapeArrowRightEndProxy extends HandleObject {
  constructor(shapeArrowHandle?: any);
  style: any;
  readonly length: number;
  readonly innerOffset: any;
  readonly isProportional: boolean;
  setLength(value?: any, width?: any, height?: any): this;
  setInnerOffset(value?: any, width?: any, height?: any): this;
  setIsProportional(value?: any, width?: any, height?: any): this;
  assign(src?: any, width?: any, height?: any): any;
}

export class ShapeCalloutEllipse extends Shape {
  constructor(handle?: any);
  static create(): ShapeCalloutEllipse;
  clone(): ShapeCalloutEllipse;
  readonly absoluteSizes: any;
  setAbsoluteSizes(value?: any, boundsWidth?: number, boundsHeight?: number): this;
  tail: ShapeCalloutEllipseTail;
}

export class ShapeCalloutEllipseTail extends HandleObject {
  constructor(shapeHandle?: any);
  angle: any;
  endPosition: any;
  height: number;
  assign(src?: any): any;
}

export class ShapeCalloutRectangle extends Shape {
  constructor(handle?: any);
  static create(): ShapeCalloutRectangle;
  clone(): ShapeCalloutRectangle;
  getCornerRadius(cornerIndex?: number): any;
  readonly absoluteSizes: any;
  useSingleRadius: any;
  tail: ShapeCalloutRectangleTailProxy;
  setCornerRadius(cornerIndex?: number, radius?: any, boundsWidth?: number, boundsHeight?: number): this;
  setAbsoluteSizes(value?: any, width?: any, height?: any): this;
}

export class ShapeCalloutRectangleTailProxy extends HandleObject {
  constructor(shapeCalloutRectangleHandle?: any);
  startPosition: any;
  endPosition: any;
  width: number;
  height: number;
  assign(src?: any): any;
}

export class ShapeCat extends Shape {
  constructor(handle?: any);
  static create(): ShapeCat;
  clone(): ShapeCat;
}

export class ShapeCat2 extends Shape {
  constructor(handle?: any);
  static create(): ShapeCat2;
  clone(): ShapeCat2;
}

export class ShapeCat3 extends Shape {
  constructor(handle?: any);
  static create(): ShapeCat3;
  clone(): ShapeCat3;
}

export class ShapeCat4 extends Shape {
  constructor(handle?: any);
  static create(): ShapeCat4;
  clone(): ShapeCat4;
}

export class ShapeCloud extends Shape {
  constructor(handle?: any);
  static create(): ShapeCloud;
  clone(): ShapeCloud;
  bubbles: number;
  innerRadius: any;
}

export class ShapeCog extends Shape {
  constructor(handle?: any);
  static create(): ShapeCog;
  clone(): ShapeCog;
  innerRadius: any;
  holeRadius: any;
  toothSize: any;
  notchSize: any;
  curvature: any;
  teeth: number;
}

export class ShapeCrescent extends Shape {
  constructor(handle?: any);
  static create(): ShapeCrescent;
  clone(): ShapeCrescent;
  leftArc: any;
  rightArc: any;
}

export class ShapeDiamond extends Shape {
  constructor(handle?: any);
  static create(): ShapeDiamond;
  clone(): ShapeDiamond;
  position: any;
}

export class ShapeDoubleStar extends Shape {
  constructor(handle?: any);
  static create(): ShapeDoubleStar;
  clone(): ShapeDoubleStar;
  innerRadius: any;
  pointRadius: any;
  points: number;
}

export class ShapeEllipse extends Shape {
  constructor(handle?: any);
  static create(): ShapeEllipse;
  clone(): ShapeEllipse;
}

export class ShapeHeart extends Shape {
  constructor(handle?: any);
  static create(): ShapeHeart;
  clone(): ShapeHeart;
  spread: any;
}

export class ShapePie extends Shape {
  constructor(handle?: any);
  static create(): ShapePie;
  clone(): ShapePie;
  innerRadius: any;
  startAngle: any;
  endAngle: any;
  sweep: any;
  readonly isClosed: boolean;
  closePie(): any;
}

export class ShapePolygon extends Shape {
  constructor(handle?: any);
  static create(): ShapePolygon;
  clone(): ShapePolygon;
  curve: any;
  sides: number;
  smoothPoints: any;
  readonly minCurve: any;
}

export class ShapeQRCode extends Shape {
  constructor(handle?: any);
  static create(): ShapeQRCode;
  clone(): ShapeQRCode;
  payload: QRPayload;
}

export class ShapeRectangle extends Shape {
  constructor(handle?: any);
  static create(): ShapeRectangle;
  clone(): ShapeRectangle;
  readonly topLeft: ShapeRectangleCornerProxy;
  readonly topRight: ShapeRectangleCornerProxy;
  readonly bottomLeft: ShapeRectangleCornerProxy;
  readonly bottomRight: ShapeRectangleCornerProxy;
  readonly isPlainRectangle: boolean;
  readonly absoluteSizes: any;
  useSingleRadius: any;
  setTopLeft(value?: any, width?: any, height?: any): this;
  setTopRight(value?: any, width?: any, height?: any): this;
  setBottomLeft(value?: any, width?: any, height?: any): this;
  setBottomRight(value?: any, width?: any, height?: any): this;
  setAbsoluteSizes(value?: any, width?: any, height?: any): this;
}

export class ShapeRectangleCornerProxy extends HandleObject {
  constructor(shapeRectangleHandle?: any, cornerIndex?: number);
  readonly radius: any;
  cornerType: any;
  setRadius(value?: any, width?: any, height?: any): this;
  assign(src?: any, width?: any, height?: any): any;
}

export class ShapeSegment extends Shape {
  constructor(handle?: any);
  static create(): ShapeSegment;
  clone(): ShapeSegment;
  angle: any;
  lowerLine: any;
  upperLine: any;
}

export class ShapeSpiral extends Shape {
  constructor(handle?: any);
  static create(): ShapeSpiral;
  clone(): ShapeSpiral;
  style: ShapeSpiralStyle;
  flip: any;
  turns: any;
  partTurn: any;
  decay: any;
  segmentAngle: any;
  divisions: any;
  innerRadius: any;
  decayPerSegment: any;
  cusped: any;
  choke: any;
  capChoke: any;
  bias: any;
}

export class ShapeSquareStar extends Shape {
  constructor(handle?: any);
  static create(): ShapeSquareStar;
  clone(): ShapeSquareStar;
  sides: number;
  cutout: any;
}

export class ShapeStar extends Shape {
  constructor(handle?: any);
  static create(): ShapeStar;
  clone(): ShapeStar;
  readonly maxInnerRadius: any;
  innerRadius: any;
  leftCurve: any;
  rightCurve: any;
  circleInnerRadius: any;
  circleOuterRadius: any;
  points: number;
  curvedEdges: any;
}

export class ShapeTear extends Shape {
  constructor(handle?: any);
  static create(): ShapeTear;
  clone(): ShapeTear;
  ball: ShapeTearBallProxy;
  curve: any;
  bend: any;
  tailPosition: any;
}

export class ShapeTearBallProxy extends HandleObject {
  constructor(shapeTearHandle?: any);
  size: any;
  fixedSize: any;
  assign(src?: any): any;
}

export class ShapeTrapezoid extends Shape {
  constructor(handle?: any);
  static create(): ShapeTrapezoid;
  clone(): ShapeTrapezoid;
  left: any;
  right: any;
  setPositions(left?: any, right?: any): this;
}

export class ShapeTriangle extends Shape {
  constructor(handle?: any);
  static create(): ShapeTriangle;
  clone(): ShapeTriangle;
  position: any;
}

export function createTypedQRPayload(payloadHandle?: any): any;
export function createTypedShape(shapeHandle?: any): any;
export const QRPayloadType: any;
export { ShapeArrowEndStyle } from 'affinity:geometry';
export { ShapeBoolParam } from 'affinity:geometry';
export { ShapeCornerIndex } from 'affinity:geometry';
export { ShapeCornerType } from 'affinity:geometry';
export { ShapeEnumParam } from 'affinity:geometry';
export { ShapeFloatParam } from 'affinity:geometry';
export { ShapeIntParam } from 'affinity:geometry';
export { ShapeMajorAxis } from 'affinity:geometry';
export { ShapeSpiralStyle } from 'affinity:geometry';
export { ShapeType } from 'affinity:geometry';
export { WifiEncryptionType } from 'affinity:geometry';
