// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class ShapeInterface extends HandleObject {
  constructor(handle?: any);
  readonly isShapeInterface: any;
  readonly boundingBox: any;
  shape: any;
  readonly type: any;
  readonly domainTransform: any;
  readonly node: any;
  setShape(shape?: any, preview?: any): any;
  setShapeAsync(shape?: any, callback?: any, preview?: any): any;
}

export { ShapeType } from 'affinity:geometry';
