// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { Shape } from '/shapes';

export class ShapeInterface extends HandleObject {
  constructor(handle?: any);
  readonly isShapeInterface: boolean;
  readonly boundingBox: any;
  shape: Shape;
  readonly type: any;
  readonly domainTransform: any;
  readonly node: any;
  setShape(shape?: any, preview?: any): any;
  setShapeAsync(shape?: any, callback?: (...args: any[]) => any, preview?: any): any;
}

export { ShapeType } from 'affinity:geometry';
