// Auto-generated by tools/generate_types.py. Do not edit.

import { GlyphAtts } from '/glyphatts';
import { HandleObject } from '/handleobject';
import { ParagraphAtts } from '/paragraphatts';

export class StoryBuilder extends HandleObject {
  constructor(handle?: any);
  static create(): StoryBuilder;
  setToFrameTextDefaultStyle(dpi?: any, format?: any): this;
  setToArtisticTextDefaultStyle(dpi?: any, format?: any): this;
  clearText(): this;
  addText(text?: string): this;
  addParagraphBreak(): this;
  setGlyphAtts(glyphAtts?: GlyphAtts): this;
  setParagraphAtts(paragraphAtts?: ParagraphAtts): this;
  applyGlyphDelta(delta?: any): this;
  applyParagraphDelta(delta?: any): this;
  readonly glyphAtts: GlyphAtts;
  readonly paragraphAtts: ParagraphAtts;
}

export { RasterFormat } from 'affinity:raster';
