// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class StoryBuilder extends HandleObject {
  constructor(handle?: any);
  static create(): StoryBuilder;
  setToFrameTextDefaultStyle(dpi?: any, format?: any): this;
  setToArtisticTextDefaultStyle(dpi?: any, format?: any): this;
  clearText(): this;
  addText(text?: any): this;
  addParagraphBreak(): this;
  setGlyphAtts(glyphAtts?: any): this;
  setParagraphAtts(paragraphAtts?: any): this;
  applyGlyphDelta(delta?: any): this;
  applyParagraphDelta(delta?: any): this;
  readonly glyphAtts: any;
  readonly paragraphAtts: any;
}

export { RasterFormat } from 'affinity:raster';
