// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class StoryInterface extends HandleObject {
  constructor(handle?: any);
  readonly domainTransform: any;
  readonly scalarDomainTransform: any;
  readonly textDefaultType: any;
  readonly textRenderScale: any;
  readonly textUiScale: any;
  readonly isMultiFrameTextFlow: any;
  readonly story: any;
  readonly storyRange: any;
  getText(startPos?: any, maxLength?: any, format?: any): any;
  readonly text: any;
  readonly glyphIndexes: any;
  readonly glyphs: any;
  readonly anchorGlyphs: any;
  readonly charGlyphs: any;
  readonly crossReferenceSubGlyphs: any;
  readonly documentFieldGlyphs: any;
  readonly fieldGlyphs: any;
  readonly crossReferenceGlyphs: any;
  readonly fillerTextGlyphs: any;
  readonly formattableFieldGlyphs: any;
  readonly capturedDateTimeGlyphs: any;
  readonly customFieldGlyphs: any;
  readonly dataMergeGlyphs: any;
  readonly dataMergeFieldGlyphs: any;
  readonly dataMergeSourceGlyphs: any;
  readonly runningHeaderGlyphs: any;
  readonly pageNumberGlyphs: any;
  readonly rangenoteBodyGlyphs: any;
  readonly rangenoteReferenceGlyphs: any;
  readonly sectionNameGlyphs: any;
  readonly glyphIndexGlyphs: any;
  readonly hardBreakGlyphs: any;
  readonly indentToHereGlyphs: any;
  readonly indexMarkGlyphs: any;
  readonly listNumberGlyphs: any;
  readonly noteNumberGlyphs: any;
  readonly pinGlyphs: any;
  readonly rangenoteEndGlyphs: any;
  readonly rightIndentTabGlyphs: any;
  readonly node: any;
}

export { TextDefaultType } from 'affinity:dom';
