// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';
import { Story } from '/story';
import { CrossReferenceSubGlyphType } from 'affinity:story';
import { GlyphType } from 'affinity:story';
import { StoryIoFormat } from 'affinity:story';
import { TextDefaultType } from 'affinity:dom';

export class StoryInterface extends HandleObject {
  constructor(handle?: any);
  readonly domainTransform: any;
  readonly scalarDomainTransform: any;
  readonly textDefaultType: TextDefaultType;
  readonly textRenderScale: any;
  readonly textUiScale: any;
  readonly isMultiFrameTextFlow: boolean;
  readonly story: Story;
  readonly storyRange: any;
  getText(startPos?: number, maxLength?: any, format?: StoryIoFormat): string;
  readonly text: string;
  readonly glyphIndexes: any;
  readonly glyphs: GlyphType;
  readonly anchorGlyphs: any;
  readonly charGlyphs: any;
  readonly crossReferenceSubGlyphs: CrossReferenceSubGlyphType;
  readonly documentFieldGlyphs: any;
  readonly fieldGlyphs: any;
  readonly crossReferenceGlyphs: any;
  readonly fillerTextGlyphs: any;
  readonly formattableFieldGlyphs: any;
  readonly capturedDateTimeGlyphs: any;
  readonly customFieldGlyphs: any;
  readonly dataMergeGlyphs: any;
  readonly dataMergeFieldGlyphs: any;
  readonly dataMergeSourceGlyphs: any;
  readonly runningHeaderGlyphs: any;
  readonly pageNumberGlyphs: any;
  readonly rangenoteBodyGlyphs: any;
  readonly rangenoteReferenceGlyphs: any;
  readonly sectionNameGlyphs: any;
  readonly glyphIndexGlyphs: any;
  readonly hardBreakGlyphs: any;
  readonly indentToHereGlyphs: any;
  readonly indexMarkGlyphs: any;
  readonly listNumberGlyphs: any;
  readonly noteNumberGlyphs: any;
  readonly pinGlyphs: any;
  readonly rangenoteEndGlyphs: any;
  readonly rightIndentTabGlyphs: any;
  readonly node: any;
}

export { TextDefaultType } from 'affinity:dom';
