// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class TagInterface extends HandleObject {
  constructor(handle?: any);
  hasKey(key?: any): any;
  getValueForKey(key?: any): any;
  readonly isMarkAsDecoration: any;
  hasPredefinedKey(key?: any): any;
  getValueForPredefinedKey(key?: any): any;
  readonly node: any;
}

export { PredefinedTagKey } from 'affinity:dom';
