// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class TextFrameInterface extends HandleObject {
  constructor(handle?: any);
  readonly canHideOverflow: any;
  readonly canUseBaselineGrid: any;
  readonly canUseTextWraps: any;
  readonly hasScaledText: any;
  readonly ignoreBaselineGrid: any;
  readonly ignoreTextWraps: any;
  readonly isMultiFrameTextFlow: any;
  readonly isTextFlowBack: any;
  readonly isTextFlowFront: any;
  readonly isWrappingText: any;
  readonly textBegin: any;
  readonly textFlowIndex: any;
  readonly scalarStoryToDomainTransform: any;
  readonly storyToDomainTransform: any;
  readonly textRenderScale: any;
  readonly textUiScale: any;
  readonly node: any;
  readonly spreadNode: any;
}

