// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class TextFrameInterface extends HandleObject {
  constructor(handle?: any);
  readonly canHideOverflow: boolean;
  readonly canUseBaselineGrid: boolean;
  readonly canUseTextWraps: boolean;
  readonly hasScaledText: boolean;
  readonly ignoreBaselineGrid: any;
  readonly ignoreTextWraps: any;
  readonly isMultiFrameTextFlow: boolean;
  readonly isTextFlowBack: boolean;
  readonly isTextFlowFront: boolean;
  readonly isWrappingText: boolean;
  readonly textBegin: any;
  readonly textFlowIndex: number;
  readonly scalarStoryToDomainTransform: any;
  readonly storyToDomainTransform: any;
  readonly textRenderScale: any;
  readonly textUiScale: any;
  readonly node: any;
  readonly spreadNode: any;
}

