// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class Timer extends HandleObject {
  constructor(handle?: any);
  static create(): Timer;
  cancel(): any;
  static cancelAll(): any;
  static readonly now: any;
  static readonly nowBigInt: any;
  expiry: any;
  expiryBigInt: any;
  moveExpiry(integerOrBigInt?: any): any;
  expiryFromNow: any;
  readonly expiryFromNowBigInt: any;
  waitAsync(callback?: (...args: any[]) => any): any;
  dispose(): any;
  expiresFromNow: any;
  readonly expiresFromNowBigInt: any;
}

export function setImmediate(callback?: (...args: any[]) => any, ...args: any): any;
export function setTimeout(delay?: any, callback?: (...args: any[]) => any, ...args: any): any;
export function setInterval(delay?: any, callback?: (...args: any[]) => any, ...args: any): any;
