// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class Timer extends HandleObject {
  constructor(handle?: any);
  static create(): Timer;
  cancel(): any;
  static cancelAll(): any;
  static readonly now: any;
  expiry: any;
  expiryBigInt: any;
  moveExpiry(value?: any): any;
  expiryFromNow: any;
  waitAsync(callback?: any): any;
  dispose(): any;
  expiresFromNow: any;
}

export function setImmediate(callback?: any, args?: any): any;
export function setTimeout(delay?: any, callback?: any, args?: any): any;
export function setInterval(delay?: any, callback?: any, args?: any): any;
