// Auto-generated by tools/generate_types.py. Do not edit.

import { FillDescriptor } from '/fills';
import { HandleObject } from '/handleobject';
import { ContentType } from 'affinity:dom';

export class TransparencyInterface extends HandleObject {
  constructor(handle?: any);
  readonly fillDescriptor: FillDescriptor;
  readonly isTransparencyNone: boolean;
  readonly domainTransform: any;
  readonly contentType: ContentType;
  readonly node: any;
  isAnchoredToSpread: boolean;
  setIsAnchoredToSpread(anchored?: any, applyToAllFills?: any, preview?: any): any;
}

export { ContentType } from 'affinity:dom';
