// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class UnitValueConverter extends HandleObject {
  constructor(handle?: any);
  static create(dpi?: any, viewDpi?: any): UnitValueConverter;
  clone(): UnitValueConverter;
  readonly dpi: number;
  readonly viewDpi: number;
  getConversionFactor(from?: any, to?: any): any;
}

export { UnitType } from 'affinity:common';
export { UnitValue } from 'affinity:common';
export { UserUnitType } from 'affinity:common';
