// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class UnitValue {
  constructor(...args: any[]);
  value: any;
  units: any;
  assign(source?: any): this;
  makeZero(): this;
  makeInfinity(): this;
  getValueAsDegrees(): any;
  getValueAsRadians(): any;
  getValueAsNumber(): any;
  getValueAsPixels(converter?: any): any;
  getValueAsUnitType(converter?: any, unitType?: any): any;
  getValueAsUnitTypePower(converter?: any, unitTypePower?: any): any;
  readonly isFinite: boolean;
  static getTypeCategory(unitType?: any): any;
}

export class UnitValueConverter extends HandleObject {
  constructor(handle?: any);
  static create(dpi?: any, viewDpi?: any): UnitValueConverter;
  clone(): UnitValueConverter;
  readonly dpi: number;
  readonly viewDpi: number;
  getConversionFactor(from?: any, to?: any): number;
}

export { UnitCategory } from 'affinity:common';
export { UnitType } from 'affinity:common';
export { UserUnitType } from 'affinity:common';
