// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class VectorBrush extends HandleObject {
  constructor(handle?: any);
  static createDefault(): any;
  clone(): VectorBrush;
  brushWidth: any;
  sizeVariance: any;
  sizeControllerType: any;
  sizeSpline: any;
  opacityVariance: any;
  tailOffset: any;
  headOffset: any;
  isRepeat: any;
  cornerStrategy: any;
}

export { VectorBrushDynamicControllerType } from 'affinity:brushes';
export { CornerStrategy } from 'affinity:brushes';
