// Auto-generated by tools/generate_types.py. Do not edit.

import { HandleObject } from '/handleobject';

export class TextVisibilityOptions extends HandleObject {
  constructor(handle?: any);
  static create(): TextVisibilityOptions;
  clone(): TextVisibilityOptions;
  equals(other?: any): any;
  anySet(): any;
  setNone(): this;
  setNewViewDefaults(): this;
  showSpecialCharacters: any;
  showIndexMarks: any;
  showAnchors: any;
  showNoteMarks: any;
  highlightFields: any;
}

export class VisibilityInterface extends HandleObject {
  constructor(handle?: any);
  readonly globalOpacity: any;
  readonly fillOpacity: any;
  readonly isVisible: boolean;
  readonly isVisibleInExport: boolean;
  readonly isVisibleInDomain: boolean;
  testVisibility(options?: any): any;
  readonly node: any;
}

export class VisibilityTestOptions extends HandleObject {
  constructor(handle?: any);
  static create(): VisibilityTestOptions;
  clone(): VisibilityTestOptions;
  textVisibilityOptions: TextVisibilityOptions;
  ignoreVisibilityFlags: any;
  applyExportableVisibility: any;
  showEmptyRects: any;
  showPictureFrames: any;
  clipToSpread: any;
  allowInvisibleLayers: any;
}

export const VisibilityTestOptionsApi: any;
export const TextVisibilityOptionsApi: any;
